### ISSUE TITLE
Page transition cause delay in page title change

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt/nuxt#10626]
### Versions

- nuxt: 2.15.8
- node: 16.14.0

### Steps to reproduce
- Create a projet
- Add a head function qui a titleTemplate like so:
```
titleTemplate: (titleChunk) => {
    return titleChunk ? `${titleChunk} | ${$i18n.t('app.name')}` : `${$i18n.t('app.name')} | ${$i18n.t('app.sn')}`;
},
```
- The title change when we switch lang correctly
- Add a page transition
- Now the title goes to the default value before going to the other lang title while the page transition is taking place.

### What is Expected?
The page title should change from `Accueil | Rapport d'activité` to `Home | Activity report` directly
![2022-08-05 11 27 46](https://user-images.githubusercontent.com/17392251/183110850-f61171fc-c806-4895-b242-66c7d212fbef.gif)

### What is actually happening?
The page title change from `Accueil | Rapport d'activité` to `Rapport d'activité | Sentinelle Nord` and then to `Home | Activity report`
![2022-08-05 11 26 32](https://user-images.githubusercontent.com/17392251/183110871-3ea84e18-7fdb-435f-a794-69dc74641e3c.gif)

**Comment by bianliuzhu** [comment]
Nice to talk to you. I am a developer in China, I like the framework of NUXT very much， But it also brings me some troubles Because we do not know much about the bottom implementation and operating principle of NUXT.
About the following four issues, I hope to get a little inspiration from you  thank you very much

I use NUXT2


Will using Vuex reduce performance?
Will Vuex run on the server? and will vuex data be downloaded from the server to the client?
Does the use of Vuex increase the memory?
The same state, what is the difference between storing in vuex and storing in components

**Comment by harlan-zw** [comment]
This is fixed in Nuxt 3 and will unlikely go unfixed in Nuxt 2.
