### ISSUE TITLE
Edge side Includes (ESI) in nuxt

### ISSUE THREAD

**Issue by rafaelragib** [nuxt/nuxt#10867]
Currently we are trying to work with varnish and Nuxt 2 application. We want to use the edge side includes feature (esi:include) in our application. But for hydration issue, it is not possible to use it. Is there any way to solve this issue in nuxt? Any sort of feature creation for this issue will be appreciated. 
Thanks

**Comment by manniL** [comment]
Let's discuss in https://github.com/nuxt/nuxt.js/issues/10867

**Comment by Abrar535** [comment]
**The problem is:**  When using <esi:include/> tag with nuxt ssr, in the server side varnish is properly replacing the <esi:include/> tag with the resolved html, But during the **client-side hydration phase** done by nuxt js, there is a mismatch of html (since there is no varnish to replace the <esi:include/> in the client side obviously) and that mismatched html is getting removed by nuxtjs. Thats why the html rendered by <esi:include/> tags will appear for a short moment and then it gets removed by the vue/nuxt js scripts for failing hydration. 
ReactJs/NextJs has a good integration for esi with react-esi library [check here](https://github.com/vercel/next.js/pull/6225).
It would be really nice if such a feature/integration is possible with nuxt js also. Thanks

**Comment by danielroe** [comment]
This should now be possible with a server component in Nuxt 3: https://stackblitz.com/edit/github-erjee7.
