### ISSUE TITLE
hybrid islands (with remote sources)

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxt#12343]
### Describe the feature

We currently have support for rendering [component islands](https://github.com/nuxt/framework/pull/5689) and a [server components implementation](https://github.com/nuxt/framework/pull/9972) of island rendering.

It would be nice to support remote sources for island rendering - e.g. a separate API endpoint that can render server components for multisite implementations.

This issue is to discuss feature set and implementation details.

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by Baroshem** [comment]
Interesting feature.

I will try to explain in my word how this functionality is supposed to work and if I am wrong, please let me know so that I can get the idea correctly.

The point is to have an api endpoint (registered in nuxt by default?) that when sending request to it it will return rendered server components that can be then used in this app or another?

Am I correct?

From your description, I see mamy benefits for ecommerce -> supporting multiple stores by serving server rendered components for better performance (for example ProductCard that can look the same for multiple brands while other functionality and theme of the multistore can be generated from current project).

**Comment by pi0** [comment]
NuxtIsland component is universal. Meaniny it can render both in client and server and also hydrate components.

Indeed one of the main benefits would be CMS systems that provide dynamic components without need to rebuild and directly rendered. 

I would probably couple this feature with an external library for cms support side.
