### ISSUE TITLE
Extending prerender routes

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#13949]
In Nuxt 2, using `nuxt generate`, we could either manually provide routes to generate or depend on the (later added) crawler to find them.

For manual mode, it was possible to use `generate.routes` option to provide an async function prefetching them. While this functionality is needed in general, adding async logic to `nuxt.config` is kinda an anti pattern that we are trying to avoid in Nuxt 3 so there might be better ideas.

Ref: nuxt/nuxt.js#13939

**Comment by devzom** [comment]
This solution works for me:

```ts
import { ofetch } from 'ofetch'

const getPlanetsRoutes = async () => {
    const response = await ofetch("https://api.nuxtjs.dev/planets");
    return response.map((planets) => `/planets/${planets.slug}`);
}

export default defineNuxtConfig({
    nitro: {
        prerender: {
            crawlLinks: true,
            routes: [
                'planets'
            ]
        }
    },
    hooks: {
        async 'nitro:config'(nitroConfig) {
            if (nitroConfig.dev) { return }
            const planetsRoutes = await getPlanetsRoutes();
            nitroConfig.prerender.routes.push(...planetsRoutes);
        }
    }
});
```

**Comment by nomadoda** [comment]
> > @TotomInc As a workaround, You can also use `nitro:config` hook to add custom (async) routes to prerenderer:
> > ```js
> > import { defineNuxtConfig } from 'nuxt'
> > 
> > export default defineNuxtConfig({
> >   hooks: {
> >     async 'nitro:config' (nitroConfig) {
> >       if (nitroConfig.dev) { return }
> >       // ..Async logic..
> >       nitroConfig.prerender.routes.push('/custom')
> >     }
> >   }
> > })
> > ```
> 
> Issue with this is I cannot import composables from modules into this. Whereas in generate I believe that works.
> 
> For example, I have an issue where I'm trying to [dynamically add routes to Nuxt Content module](https://github.com/nuxt/content/discussions/1784). I [made a workaround](https://github.com/mohsin/iMoz-Web/commit/db126d2df7293a84322ab925fdfb21685d1ae5a0) which includes these routes using Nuxt's crawler but it's an inelegant solution. I'd like to be able to do something like:
> 
> ```
>   hooks: {
>     async 'nitro:config' (nitroConfig) {
>       if (nitroConfig.dev) { return }
>       var projects = (await queryContent('/data/projects').findOne());
>       projects.forEach((project) => {
>           nitroConfig.prerender.routes.push('/api/_content/query/data/projects/' + project.slug)   
>       })
>     }
>   }
> ```
> 
> Or something in that effect that would resolve my issue and enable me to prerender dynamic routes in non-SSR mode.

This is my workaround I'm using for a statically server-rendered site. List all links during prerendering, so that it's picked up by the crawler and remove the template after mount so that it's not included in the final output. For example, in `app.vue`:

```vue
<template>
  <NuxtPage />
  <template v-if='isPrerendering'>
    <NuxtLink v-for='route in routes' :to='route' />
  </template>
</template>

<script lang="ts">
const useIsMounted = () => {
  const isMounted = ref(true)
  onMounted(() => {
    isMounted.value = false
  })
  return isMounted
}

export default defineNuxtComponent({
  setup() {
    const routes = useRoutesComposable()
    const isPrerendering = useIsMounted()
    return { routes, isPrerendering }
  },
})
</script>
```

**Comment by rafaelmagalhaes** [comment]
This works great, thank you

> I think your ID would be the key for this, not a payload. Your file/route would be something like `/products/[id].vue` where ID is each product ID. The prerendered routes would generate a static page for each product. You wouldn't pass the product ID as a parameter if you wanted it to be prerendered.
> 
> Here's an example: [nuxt.config.ts](https://github.com/Smef/nuxt-ssg-issue-demo/blob/main/nuxt.config.ts)
> 
> In this file we're getting fake blog posts, but it would be the same thing for your real products. You'd use an async function to retrieve the list of product IDs so that you have your full array of routes, pass the array to the nitro hook, and then each of your products would have a static page generated.


but how would this work for websites that have thousands of articles?  its great for personal blog sites and works fine so far, but if we have an endpoint with pagination for example, should we just hit  it until we get all the data?

**Comment by Smef** [comment]
Yep. That's how full SSG works and it's totally fine to SSG paginated data. With SSG there's no database and no server to return data, such as the contents of a single article, the contents of page 1, page 2, etc. so everything you want to see in your deployed site must be prerendered, including all pages of a paginated list and all of the contents of those listed pages. You end up with a folder with a bunch of HTML, CSS, and JS files and those files make up your whole site. Nuxt builds your site and then you can dump it on any static file hosting you want, even including something like basic file storage like Amazon S3. There's no Nuxt after the generate step.

If you have an article list view, for example, you'd need to statically generate every single page of your list view. The full set of pages of the list view should cover all of the actual articles, and so the SSG process should follow all of the links and discover all of the articles, so you actually don't need to add your own prerender routes in this case.

Full SSG will get you the best performance and the lightest server load, but your application may require a server for some functionality still. In those cases you may want to use AJAX requests to retrieve data from a CMS or something like that, such as search results for someone searching articles for specific terms. 

If you still have way, way too much data that are very unlikely to be viewed, but still need to be served, you may look at a hybrid approach where you have something like Incremental Static Generation. You still use run your site on an actual Nuxt server, but it pre-renders a lot of the content at build time and only certain routes are actually processed by the Nuxt app, or pages may be cached, expired, and re-generated periodically when they are requested. Nuxt's hybrid rendering rules allows you to set this up. https://nuxt.com/docs/guide/concepts/rendering#route-rules. You'll need to find the rendering strategy that works best for you.

**Comment by HollyCreep** [comment]
I'm facing this problem even with `ssr:false`. I was able to partially solve it with the @Smef guide, but the app I'm working on has multiple tags and settings based on the current tag (URL based).

My goal is to build full SPA application (no static, no ssr), I'm using `ssr:false + nuxi generate`, am I missing something?

**Comment by danielroe** [comment]
@mrniamster Nuxt/Vue composables are not usable within your nuxt config, which is running in a pure node environment.

**Comment by mrniamster** [comment]
THank @danielroe  for this, but now the question is still exist how to generate routes for md files without manually typing inside the pre-render , coming in nuxt 3.6.2 / 3.5.3

**Comment by supakornkim** [comment]
ssr:true
npm run generate not generate page under folder /pages

**Comment by Velka-DEV** [comment]
> Yep. That's how full SSG works and it's totally fine to SSG paginated data. With SSG there's no database and no server to return data, such as the contents of a single article, the contents of page 1, page 2, etc. so everything you want to see in your deployed site must be prerendered, including all pages of a paginated list and all of the contents of those listed pages. You end up with a folder with a bunch of HTML, CSS, and JS files and those files make up your whole site. Nuxt builds your site and then you can dump it on any static file hosting you want, even including something like basic file storage like Amazon S3. There's no Nuxt after the generate step.
> 
> If you have an article list view, for example, you'd need to statically generate every single page of your list view. The full set of pages of the list view should cover all of the actual articles, and so the SSG process should follow all of the links and discover all of the articles, so you actually don't need to add your own prerender routes in this case.
> 
> Full SSG will get you the best performance and the lightest server load, but your application may require a server for some functionality still. In those cases you may want to use AJAX requests to retrieve data from a CMS or something like that, such as search results for someone searching articles for specific terms.
> 
> If you still have way, way too much data that are very unlikely to be viewed, but still need to be served, you may look at a hybrid approach where you have something like Incremental Static Generation. You still use run your site on an actual Nuxt server, but it pre-renders a lot of the content at build time and only certain routes are actually processed by the Nuxt app, or pages may be cached, expired, and re-generated periodically when they are requested. Nuxt's hybrid rendering rules allows you to set this up. https://nuxt.com/docs/guide/concepts/rendering#route-rules. You'll need to find the rendering strategy that works best for you.

Is there actually a way to pre-render routes like https://example.com/?page=1?

Without such a method, creating files like index.vue & page/[page].vue becomes cumbersome. This process also leads to the problem of shared boilerplate code between pages. Another challenge could be the necessity of sharing pagination logic across different routes.

**Comment by nhan-ho-saltovn** [comment]
> From the [Nuxt3 config schema file](https://github.com/nuxt/framework/blob/main/packages/schema/src/config/generate.ts)
> 
> > You can pass a function that returns a promise or a function that takes a callback. It should
> > return an array of strings or objects with `route` and (optional) `payload` keys.
> 
> About returning objects with a `route` and `payload` keys: is this still possible in Nuxt3?
> 
> I tried doing this
> 
> ```
> nitroConfig.prerender.routes.push({route: '/custom'})
> ```
> 
> Which resulting in the route showing as `├─ [object Object] (undefinedms) (TypeError [ERR_INVALID_URL]: Invalid URL)`

Have you found the solution for this issue? Im encountering the same issue as you and struggling to fix it OTL 
<img width="1002" alt="image" src="https://github.com/nuxt/nuxt/assets/109122792/a4990ec9-22e3-456c-9d86-b7502fa67f7e">

**Comment by T-Mike** [comment]
> This solution works for me, limited process to do not run on `dev`
> 
> ```ts
> import { ofetch } from 'ofetch'
> 
> const getPlanetsRoutes = async () => {
>     const response = await ofetch("https://api.nuxtjs.dev/planets");
>     return response.map((planet) => `/planets/${planet.slug}`);
> }
> 
> export default defineNuxtConfig({
>     hooks: {
>         async 'nitro:config'(nitroConfig) {
>             if (nitroConfig.dev) { return }
>             const planetsRoutes = await getPlanetsRoutes();
>             nitroConfig.prerender.routes.push(...planetsRoutes);
>         }
>     }
> });
> ```
> 
> @pi0 @danielroe **Unlucky noticed that this hook is also run during packages install ex `pnpm i`**
> 
> ```
> pnpm i
> Lockfile is up to date, resolution step is skipped
> Already up to date
> 
> > @ postinstall /Users/admin/dev/Vue/nuxt3-gen
> > nuxt prepare
> 
> Nuxi 3.2.2                                                                                                     09:18:01
> {                                                                                                              09:18:02
>   response: [
>     {
>       title: 'Earth',
>       ...
> 	}
> ```
> 
> ofc, the documentation need to contain a bit more information for newcomers. It'll be nice to have maybe some built-in battle-tested approach for that.


If found you can add this conditional to run your script only when you launch `nuxt generate` (and should work with any package manager)

```js
if (process.argv?.includes('generate')) {
    const myRoutes = await getAllRoutes()
    nitroConfig.prerender.routes.push(...myRoutes)
}
```

**Comment by captain-zsa** [comment]
> Yep. That's how full SSG works and it's totally ...

I understand correctly, if in blog (shop) I create new page (and my hosting havent node.js), I run `nuxt generate` in my local pc, after download (ftp) new file .html on my host?

Maybe somehow we can do automatic generation if a new dynamic page is added?

**Comment by Smef** [comment]
Yes. That is correct. You get a fold of HTML files which you can upload to your host. There is no Nuxt server running or deployed anywhere.

It's also possible configure automatic generation when a new page is added, though triggering the process is not something Nuxt would do since there's no Nuxt server running. We do that for our site, for example (https://gearboxgo.com) and trigger a new build and deploy every time someone adds a post in our CMS. You can read about that process here: [https://gearboxgo.com/articles/web-application-development/building-our-jamstack-site-with-laravel-statamic-and-nuxt](https://gearboxgo.com/articles/web-application-development/building-our-jamstack-site-with-laravel-statamic-and-nuxt)

**Comment by wanxe** [comment]
I'm having one issue that don't know if is related.

I am fetching a CMS to bring me all the slugs, to later add them as pages (by using a module with hook `pages:extend`). The fact is that everything works fine until I do `npm run generate ` to generate the static ones. My problem starts when I try to run the statics on any server and navigate routes (with `NuxtLink`), where each route embeds the home page again instead of displaying the content of that page. However, when landing directly on that URL everything seems to work correctly. Obviously if I use a `<a href` or ` NuxtLink` with external prop everything works. But I feel like I'm doing something wrong.

**Comment by maximepvrt** [comment]
@pi0 for nuxt 4 ? 🙈

**Comment by mimikn** [comment]
Well isn't the [`prerender:routes`](https://nuxt.com/docs/api/advanced/hooks#nuxt-hooks-build-time) lifecycle route done for that ?
I'm using it and I've not encountered any issues so far.

```js
export default defineNuxtConfig({
  hooks: {
      // fetch async routes to prerender
      'prerender:routes': async function (ctx) {
        const routes = await getYourAsyncRoutes();
        if (routes && routes.length) {
          routes.forEach((route) => {
            // for what I remember `ctx.routes` is a Set()
            ctx.routes.add(route.url);
          });
        }
      },
    },
 })
```

**Comment by danielroe** [comment]
I think this is resolved.

Either use the `prerender:routes` hook. Or use the `prerenderRoutes` _runtime_ utility to add to the routes list, using any runtime configuration you have (such as a configured API client, etc.)...

**Comment by Aravinda93** [comment]
@pi0 @TotomInc @danielroe @T-Mike @kasperjha 

[How to pre-render all the routes in Nuxt 3 application .output automatically (without hard coding and specifying them specifically)?](https://stackoverflow.com/questions/78658283/how-to-pre-render-all-the-routes-in-nuxt-3-application-output-automatically-wi) Is there a way to pre-render all the routes automatically rather than defining the individual routes? I don't wish to add a method to identify the routes, but rather try to find a way where `nuxt generate` can automatically figure out the routes and pre-render them into the `.output/public`.

**Comment by Smef** [comment]
The default behavior for Nuxt prerendering is to run a crawler starting from your site index and then following and rendering all the links that it discovers as well as to prerender the pages in your `/pages` directory. The only time you need to manually specify the routes is if the routes are dynamic and the specific dynamic route pages are unreachable through the regular crawling of your site links.

From [the docs about prerendering](https://nuxt.com/docs/getting-started/prerendering#crawl-based-pre-rendering)
1. Load the HTML of your application's root route (/), any non-dynamic pages in your ~/pages directory, and any other routes in the nitro.prerender.routes array.
2. Save the HTML and payload.json to the ~/.output/public/ directory to be served statically.
3. Find all anchor tags (<a href="...">) in the HTML to navigate to other routes.
4. Repeat steps 1-3 for each anchor tag found until there are no more anchor tags to crawl.

If, for some reason, you have a page you wish to prerender which is both a dynamic route and not linked to anywhere on your site you can [manually specify the page to be prerendered in your defineNuxtConfig](https://nuxt.com/docs/getting-started/prerendering#selective-pre-rendering). Be aware, though, that if you have to do this for content on your site it means that there isn't any way for users to get to that content from the regular browsing of your site, and this can indicate a discoverability problem. It may be a better idea to fix the lack of discoverability of your content rather than forcing the prerendering directly.
