### ISSUE TITLE
`nuxi analyze`: Nitro server bundle stats unavailable

### ISSUE THREAD

**Issue by Atinux** [nuxt/nuxt#14066]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@1.22.15`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

- `nuxi init nuxt3-app`
- `cd nuxt3-app`
- `yarn install`
- `npx nuxi analyze`

Open http://localhost:3000/ and click on [Nitro server bundle stats](http://localhost:3000/nitro)

### Describe the bug

```
 ERROR  [h3] ENOENT: no such file or directory, open '/Users/atinux/Downloads/ams-demo/.nuxt/stats/nitro.html'
```

![Screenshot 2022-05-31 at 20 36 34](https://user-images.githubusercontent.com/904724/171261189-d1d7376a-20fa-4f35-8813-eea3a7fed34b.png)

**Comment by GaborTorma** [comment]
This bug is still here. 

### Environment

- Operating System: Darwin
- Node Version: v18.17.1
- Nuxt Version: 3.6.5 with Nitro 2.5.2
- Package Manager: pnpm@8.6.12
- Builder: vite

### Reproduction

- nuxi init nuxt3-app
- cd nuxt3-app
- pnpm install
- npx nuxi analyze

The client.html and nitro.html file generated to `.nuxt/analyze` folder, but the server find it in `.nuxt/stats` folder.

![Snag_37c37545](https://github.com/nuxt/nuxt/assets/11255009/32cce715-4403-42c6-8b94-5a32f725f869)

**Comment by GaborTorma** [comment]
Sorry, it was my mistake.
I used globally installed Nuxi@3.4.3.
