### ISSUE TITLE
Auto reload page when chunk assets are not found

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#14594]
References: nuxt/nuxt.js#14591

We had this feature in Nuxt 2. Basically what happens is with a new deployment, hashes of old js chunks will be changed. And if users already loaded the page with manifest and chunks of the last deployment, they fail when navigating on client-side that tries to load dynamic chunks.

There are several ways to resolve this issue but probably the safest and easiest, is that same as Nuxt 2 we make use of a global error handler that identifies such errors and reload pages. (Note for implementation: We should set a LocalStorage key to avoid infinity page reloads)

Bonus: We could new offer a new `nuxtApp` hook such as `app:chunkError` that allows graceful HMR alike handling by end-user.

**Comment by jastaffen** [comment]
@danielroe thanks for pointing me to this issue! :) I mean this with all due respect, but how is this issue just a "p2-nice-to-have"? If I can't employ a CI/CD flow on a heavy traffic site with nuxt3 without worrying about this sort of issue that is a fairly large discrepancy between something baked into nuxt2 that's not present in nuxt3 and was not mentioned anywhere clearly in the documentation then why is this not a larger/greater priority issue? Perhaps I'm missing something very obvious here, but I'm just curious.

**Comment by MDileg** [comment]
Hello Developers, I have a question, how are u using loading, during fetch data, 


methods:{
async fetchHome() {
	loading.setLoading(true);
        // some fetching data ...
	loading.setLoading(false);
} }

I am using like this but loading was false during fetching data, in nuxt3

**Comment by IlyaSemenov** [comment]
I keep old hashes on the CDN living for some time, but use a custom Nuxt module that detects app update and shows a notification suggesting to reload the page.

I have been using this approach for years (even since pre-bridge Nuxt 2) privately. Today I published the module as a reusable npm package: [nuxt-update](https://github.com/ilyaSemenov/nuxt-update). Hope someone finds it useful, too. ✌️

**Comment by edwh** [comment]
Posting for anyone who finds this via Google.   I've not opened a new issue because the on going work to add hooks like `app:chunkError` is probably the Nuxt solution.

I find that if I hammer at the refresh and cancel icons in my browser, I can reproduce similar errors, e.g. `Failed to fetch dynamically imported module` even in local dev.   I _think_ what may be happening is related to the cancellation of network requests that happens when a page is reloaded.

In that case Nuxt bombs out and ends up on my custom error page.  It doesn't reload,.  However you can spot the error in `script setup` of a custom error page, and trigger a reload there.

**Comment by TouchSek** [comment]
> I keep old hashes on the CDN living for some time, but use a custom Nuxt module that detects app update and shows a notification suggesting to reload the page.
> 
> I have been using this approach for years (even since pre-bridge Nuxt 2) privately. Today I published the module as a reusable npm package: [nuxt-update](https://github.com/ilyaSemenov/nuxt-update). Hope someone finds it useful, too. ✌️

Does it work with nuxt 2?

**Comment by nandi95** [comment]
So if I hook into the `'app:chunkError'` then my plugin will be called after plugin `'nuxt:chunk-reload'`? Meaning by the time I hook in, page errors have been handled by the automatic reload?

https://github.com/nuxt/nuxt/blob/24c5af328f94bb3cba26121530406ee5ac124dfe/packages/nuxt/src/app/plugins/chunk-reload.client.ts#L28-L32

If this isn't the case, what's the recommended way to handle chunk errors from lazy loaded components?

@danielroe

**Comment by nandi95** [comment]
It seems that this hook will be called on page chunk error too. How would I differentiate between lazy loaded components and pages?

**Comment by danielroe** [comment]
@nandi95 Would you open a new issue with some suggestions or a reproduction if you're encountering a bug or something you can't achieve with the current approach?

**Comment by gurgenhakobyan** [comment]
I'm getting this error as well. And happens randomly, the error is not gone after hard reload. And it's the same in different browsers. It gets fixed after I make a different commit and deploy again. Any ideas?

**Comment by manniL** [comment]
@gurgenhakobyan please refer [to the comment above yours](https://github.com/nuxt/nuxt/issues/14594#issuecomment-1757162054)
