### ISSUE TITLE
Server Routes documentation : ~/server/api vs ~/server/routes

### ISSUE THREAD

**Issue by provok-it** [nuxt/nuxt#14743]
### Describe the feature

The v3 documentation doesn't really explain the real difference between `routes` and `api` directories inside the `server` dir.

Apart from "If you don't want to use `~/server/api`, you can use `~/server/routes` instead", we can't really understand their meaning. 

• Why were they created in the first place?
• When should I use `routes` instead of `api`?

The Nitro doc doesn't answer these questions either.

PS It may be great to add a "✍️ Doc upgrade" option to this list.

![Capture d’écran 2022-08-30 à 09 08 31](https://user-images.githubusercontent.com/37068300/187372577-dd6d6dd1-a623-4cb2-a27e-5a8821187128.png)

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by danielroe** [comment]
Closing as I think this is explained - but PR or a more specific explanation of what can be improved is definitely welcome if there's still something to do.

**Comment by thomassittig** [comment]
as someone who looks newly in the nuxt world, but coming from other areas, this is really confusing.
i was crawling through the docs to find a clear explanation what pattern is used for what. but if this is really just as explained earlier, that is is a "if you like to put it somewhere else"-situation, without a clear conceptional meaning behind both of them, i'm a bit disappointed. it feels like a conceptional leftover that no one wanted to clean up before releasing the final version!?

because if you have two approaches to resolve exactly the same thing, why are there even 2 approaches?
