### ISSUE TITLE
Failed to resolve component: NuxtLink and ClientOnly

### ISSUE THREAD

**Issue by 516310460** [nuxt/nuxt#14862]
### Environment

All

### Reproduction

https://stackblitz.com/edit/github-cr9hwc?file=components%2Ftest.tsx,app.vue

### Describe the bug

All `Nuxt` components do not support `TSX` and `JSX`, such as `NuxtLink`, `ClientOnly`

Failed to resolve component: NuxtLink and ClientOnly

Highest priority bug

**Comment by fogfire** [comment]
I have a component library. In order to support vue2/vue3 at the same time, the vue file is compiled into two versions of the render function, and the external export is a js file. The use of resolveComponent('client-only') will also encounter this problem. It seems that the file name does not meet the `transformInclude hook` conditions of `nuxt:components-loader`, so `transform hook` will not be executed. It would be great if the `exclude, include` attributes here can be passed in through configuration.
