### ISSUE TITLE
[Kit] Ensure a specific module in installed

### ISSUE THREAD

**Issue by Rigo-m** [nuxt/nuxt#15322]
### Describe the feature

I'm building a module with some configurable Formkit forms inside it. Since the parent application can already have a configured formkit module, how can I ensure the Formkit nuxt module is installed (sort of like a peer-dependency module)?

I don't want to install the module twice and I think that the parent application Formkit configuration should remain the main source-of-truth for Formkit.

I think an additional kit utility could be the solution, but maybe there's another way :) 

cc @justin-schroeder 

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by justin-schroeder** [comment]
FWIW — I'd be happy to add dedupe logic in our nuxt module in the meantime. Haven’t looked into it enough to know if this is doable but from my brief exposure to writing nuxt modules it seems anything is possible 😂

**Comment by harryyaprakov** [comment]
I have something similar:

Im building a custom module and I want it to install a child module, like @nuxtjs/i18n for example. I want the user to pass the inner module's configuration through my custom/parent one.

I have found `installModule` and I call it inside my module's `setup`. I think the module gets 'installed' , but the problem is that the _composables_ that the inner module provides _are not auto-imported_, so I cannot use them properly in my project.

Does the nuxt dev/build process only auto-import modules installed through the modules array?
Are modules even meant to install child modules?

**Comment by danielroe** [comment]
@harryyaprakov Modules can indeed install child modules and this shouldn't affect auto-import functionality. I suspect it might be related to your specific situation/config? Maybe the module needs a certain option to enable the auto-imports?

**Comment by harryyaprakov** [comment]
Hey, you are right - I was not getting the imports in the _playground_ , but then I tried in an actual project and it works.

I have other issues with the playground with imports that I mentioned here [#app not found in components](https://github.com/vuejs/language-tools/issues/586#issuecomment-1505616677)

ps - Great job on Nuxt! It is just pure joy to work with it...

**Comment by danielroe** [comment]
By default we disable auto-imports within module playgrounds as the types from there are used to inform module creation as well: https://github.com/nuxt/starter/blob/module/.nuxtrc#L1.

This is something we are likely to improve.
