### ISSUE TITLE
Adding hashes to the _payload.js files

### ISSUE THREAD

**Issue by kilobyte2007** [nuxt/nuxt#15427]
### Describe the feature

When using a CDN like Cloudflare it's normal to use hashes on .js files in order for the cache to be automatically cleared on redeployment as the file name (and the hash) changes.

Now it's not really possible to do that so it's hard to manage re-deployment as we have to manually clean the cache each time. At least that's what I see from the docs.

It would be nice if Nuxt would generate the payload files with a hash, like this: `_payload.{hash}.js` by default. Or at least an option to specify the file name would be nice to have.

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by Saquith** [comment]
We are currently using a full static build for our production website, which uses build-time data for everything including the payloads. We'd like to cache these as well, but we're currently opting out of it due to having the same file urls.

It'd be nice to have the option to generate them including the hash, so we can cache all of the generated files without having to worry when switching back/forth on-release.

**Comment by hamonCordova** [comment]
Something new about this issue? I'm having problem with _payload cache

**Comment by pislarm** [comment]
Experiencing the same issue. For now with ssg v3.7 I see we can only switch between generating json or js files via experimental.payloadExtraction = false.
It's strange that it seems like payload is expected to have a hash in filename here: 
 https://github.com/nuxt/framework/blob/19a2cd14929ca9b55720cb81f71687830a9e59a4/packages/nuxt/src/app/composables/payload.ts#L48C17-L48C17
Setting this would really enable us to improve client caching strategy as now we're seeing a lot of problems with stale content. Thnaks!

**Comment by pislarm** [comment]
Experiencing the same issue. For now with ssg nuxt v3.7 I see we can only switch between generating json or js files via experimental options.
It's strange that it seems like payload is expected to have a hash in filename but no way of setting it.
This would really enable us to improve caching since we're seeing a lot of problems with stale content. Thanks!

**Comment by konstanzzz** [comment]
Is there any way to include a hash now? I'm having issues with stale content.

**Comment by fabianwohlfart** [comment]
+ 1 for adding hashes, either default or by choice. For my use case having a hashed payload name would help me deal with cache aswell.

**Comment by kangelopoulos** [comment]
Is there any workaround to stop delivering stale content, is there any way to at least disable the cache?

**Comment by codeflorist** [comment]
> Is there any workaround to stop delivering stale content, is there any way to at least disable the cache?

Caching is done by the browser according to the `Cache-Control` and `Expires` headers the webserver hosting your app is sending. So you will have to setup your hosting server to send the appropriate headers for all `_payload.js` so the browser does not cache them. See my post above on how to accomplish this with an apache server using a `.htaccess` file.

**Comment by codeflorist** [comment]
Attention: It seems sometime in the past, payload files have switched from JS to JSON (`_payload.json` instead of `_payload.js`).

People might have to adapt their caching-workarounds.
