### ISSUE TITLE
cache support for useFetch/useAsyncData

### ISSUE THREAD

**Issue by lucassimines** [nuxt/nuxt#15445]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.14-27802701.2f53495`
- Nitro Version:    `0.6.2-27796963.837f894`
- Package Manager:  `npm@8.8.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-ccqtvp?file=pages%2Fabout.vue,pages%2Findex.vue,package.json

As you can see, on `rc.14 edge` if you click "Go to about page" then "Go to home", you will see that the data will be fetched again.
 If you change to `rc.13`,  the data won't be fetched again, loading from cache.

### Describe the bug

Everytime `useFetch` is being called, it ma dke a new request, it is not checking for the fetched cached data, as it used to be working by `rc.13`

**Comment by AndrewSparrowww** [comment]
@danielroe Would be nice to hear your thoughts on this topic as I believe it was very useful feature to have cached version of useAsyncData out of the box.

**Comment by vanling** [comment]
@MikeBellika awsome, learned a lot from you code :) There is one small issue im trying to fix, when using `transform` the 'fresh' data is working fine, but the returned cache is not being transformed. i guess we have to run the transform on `return cachedData.value`

**Comment by MikeBellika** [comment]
> @MikeBellika awsome, learned a lot from you code :) There is one small issue im trying to fix, when using `transform` the 'fresh' data is working fine, but the returned cache is not being transformed.
> 
> _I guess we have to run the transform on `return cachedData.value`_ ^ edit: scrap that, i think it caches the transformed data, and tries to run transform again on the cached data. edit2: still not sure.. bottomline is once i try to add the transform option it boinks on the cached value

@vanling I see. I didn't consider the transform option. The transformed data is not cached. I've put this together quickly, I hope it solves your problem.

```typescript
import { NuxtApp } from '#app';
import { AsyncData } from 'nuxt/dist/app/composables';
import {
  AsyncDataExecuteOptions,
  AsyncDataOptions,
  KeyOfRes,
  PickFrom,
  _Transform,
} from 'nuxt/dist/app/composables/asyncData';
/**
 * Composable for caching data across client requests. Prevents refetching of data when navigating on client side
 * Takes the same arguments as `useAsyncData`, with cacheKey being used to deduplicate requests
 */
export function useCachedAsyncData<Data>(
  cacheKey: string,
  handler: (ctx?: NuxtApp) => Promise<Data>,
  options?: AsyncDataOptions<Data>
): AsyncData<
  PickFrom<ReturnType<_Transform<Data>>, KeyOfRes<_Transform<Data>>>,
  Error | null
> {
  // Used to prevent collisions in nuxt data. Low likelyhood that another property in nuxt data starts with this
  const CACHE_KEY_PRREFIX = 'CACHED_ASYNC_DATA';
  const { data: cachedData } = useNuxtData(cacheKey);
  const cacheKeyAsync = `${CACHE_KEY_PRREFIX}${cacheKey}`;
  const shouldRefresh = ref<boolean>(false);

  // We need to cache transformed value to prevent value from being transformed every time.
  const transform = options?.transform;
  // Remove transform from options, so useAsyncData doesn't transform it again
  const optionsWithoutTransform = { ...options, transform: undefined };

  const asyncData = useAsyncData<Data, Error>(
    cacheKey,
    async () => {
      await refreshNuxtData(cacheKeyAsync);
      // If we already have data, and we're not being forced to refresh, return cached data
      if (cachedData.value && !shouldRefresh.value) {
        return cachedData.value;
      }
      const result = await handler();
      shouldRefresh.value = false;
      if (transform) {
        return transform(result);
      }
      return result;
    },
    optionsWithoutTransform
  );
  const refresh: (opts?: AsyncDataExecuteOptions | undefined) => Promise<void> =
    async (opts?: AsyncDataExecuteOptions) => {
      shouldRefresh.value = true;
      await asyncData.refresh(opts);
      shouldRefresh.value = false;
    };
  return { ...asyncData, refresh };
}
```

@bootsmann1995 Usage should be the same as `useAsyncData`. I've made a Stackblitz where you can see it in action: https://stackblitz.com/edit/github-npgyaf?file=pages/page1.vue

**Comment by vanling** [comment]
! @MikeBellika awsome! thank you.. i was looking at how i could fix it myself. Never thought about the way you fixed it :) thanks for the learnings

**Comment by MikeBellika** [comment]
@danielroe When the team comes agreement on how to do this, I would love to contribute

**Comment by Tummerhore** [comment]
Unfortunately, the posted  solution from @MikeBellika doesn't seem to work correctly when passing the options `{lazy: true, server: false}`: When getting the page from the server the data stays `null`. However, after client side navigation to the page the data is loaded correctly. My own attempt had the same problem. Does anyone know why this is happening and how this can be fixed?

**Comment by bcspragu** [comment]
Just learned about this the hard way when I noticed we were making 37 (!!) calls to our get current user endpoint, and none of a few dozen variations on `useAsyncData` did what I expected.

In our case, we have a `useSession` composable that, when we wrote the code mid-last year, did what we expected, where the first caller hit `useSession`, the user was loaded, and the subsequent components using `useSession` just got the cached user. I guess the "correct" way to do this would be load user info at the page level and pass it down into relevant components as a prop, but for an existing app with hundreds of components and pages, that's a heavy lift. Plus, isn't the whole point of composables to encapsulate relevant state to more composably add functionality to pages?

It looks like the behavior (i.e. removing caching) was changed because of a race condition, which is surprising to me. Is there some architectural limitation that prevented fixing the race condition? Plus, (and my JavaScript internals knowledge is quite limited feel free to tell me I have no idea what I'm talking about), I'd expect the [Node/JavaScript event loop](https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick#what-is-the-event-loop) to avoid any race conditions in the traditional sense, since all the code actually setting variables and whatnot is happening in a single thread, and no promises and whatnot are being preempted mid-execution.

**Comment by talaxasy** [comment]
@MikeBellika how to revalidate such a cache after a certain time?

**Comment by Sandros94** [comment]
Just discovered this the hard way. I was trying to access a payload vai `useNuxtData` from a different (much smaller) component, and I was getting an hydration mismatch. While digging I've noticed that it was due to `useAsyncData` refetching every time, filling the payload late for server side, but fast enough for client side.

**Comment by ilyadh** [comment]
I was trying to implement this [workaround](https://github.com/nuxt/nuxt/issues/15445#issuecomment-1439939658) and it does not work for me (I don't use SSR) because of this [bug](https://github.com/nuxt/nuxt/issues/22696).

Also for what it's worth, I think it's not unreasonable to expect some level of builtin caching from useFetch. 
Other frameworks cache fetch requests by default, and I think Nuxt should too. 
Especially when it [was](https://github.com/nuxt/framework/pull/8885) a feature at some point, even if not intentional.

**Comment by broox** [comment]
to easily cache requests on the client side, check out the new `getCachedData` option on `useFetch` and `useAsyncData`.

simple example using the default `key`:
```
const nuxtApp = useNuxtApp();
const { data, error, pending } = await useFetch('/api/data', {
  getCachedData(key) {
    return nuxtApp.payload.data[key] || nuxtApp.static.data[key]
  },
});
```

**Comment by manniL** [comment]
And for more info, I've created a ~10 min [video about the new `getCachedData` feature](https://www.youtube.com/watch?v=aQPR0xn-MMk) ☺️

**Comment by Arecsu** [comment]
Thank you all so much for making this possible! Especially to @manniL, @danielroe and @darioferderber 🤗

**Comment by AdrianFahrbach** [comment]
Just came across this issue and the suggested solution from @broox (and @manniL video) worked flawlessly. Thanks guys!
I would agree with @Arecsu though: Shouldn't this be an option of `useAsyncData`?
