### ISSUE TITLE
scrollBehavior gets called two times on initial page load

### ISSUE THREAD

**Issue by antony-k1208** [nuxt/nuxt#15568]
### Environment

Nuxi 3.0.0                                                                                                                                                                             

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-drvjtv?file=app%2Frouter.options.ts,app.vue

### Describe the bug

When using `app/router.options.ts` to set a `scrollBehavior` callback for example to restore the old scroll position or scroll to an anchor it gets called two times on initial page load. 

Check the console output for `from` and `to` route information. It seems that the layout system is somehow messing with the routing as you can see in `to.meta` for the first and second call. Also `from.name`, `from.path` and `from.fullPath` are different.

Let me know if I can be of further help.

**Comment by yuriystasiv** [comment]
@danielroe I am facing the same problem. Because of this, when I scroll down and reload the page, it scrolls up instead of staying in the same position. When `scrollBehavior` runs for the first time, it returns the correct `savedPosition`, and on the second run it returns `null`. I think that's why after reloading, the page can't stay in the same position.

I simply tried to use code below from Vue router [documentation](https://router.vuejs.org/guide/advanced/scroll-behavior.html#:~:text=const%20router%20%3D%20createRouter(%7B%0A%20%20scrollBehavior(to%2C%20from%2C%20savedPosition)%20%7B%0A%20%20%20%20if%20(savedPosition)%20%7B%0A%20%20%20%20%20%20return%20savedPosition%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20return%20%7B%20top%3A%200%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%2C%0A%7D)) in `app/router.options.ts`:

```
scrollBehavior(to, from, savedPosition) {
    if (savedPosition) {
      return savedPosition
    } else {
      return { top: 0 }
    }
  },
```

**Reproduction:**
https://stackblitz.com/edit/nuxt-starter-fs4lsj?file=app%2Frouter.options.ts

**Comment by ChrisGV04** [comment]
Exact same issue here!
Even if I use the [default `router.options.ts` Nuxt 3 uses](https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/pages/runtime/router.options.ts), the first call to `scrollBehavior` after a page refresh does contain the correct `savedPosition` info, but the second call returns `undefined`, so it jumps back to the top of the page instead of restoring the previous scoll position.

My logs right after a page refresh from `scrollBehavior`:
```
19:10:28.596 Saved position:  { left: 0, top: 874 }
19:10:28.604 Saved position: undefined
```

Is there any news on this? I see it's tagged as `p3-minor-bug` but I don't know how soon could it be fixed.

**Comment by danielroe** [comment]
The issue here, almost certainly, is that we perform two navigations on initial load:

1. push url into vue router so that when other plugins access the route they get the accurate info
2. 'replace' the url so that any middleware added by plugins gets a chance to run

This may be something we need to ask for a feature from `vue-router` upstream for or there may be a better way of doing things (cc: @posva).

**Comment by posva** [comment]
Wouldn't customizing the `scrollBehavior()` provided by nuxt on the first navigation be enough? It's even possible to use `START_LOCATION`
