### ISSUE TITLE
Scrolling to component with hash return error

### ISSUE THREAD

**Issue by ArthurDanjou** [nuxt/nuxt#15669]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.4.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `srcDir`, `app`, `modules`, `css`, `components`
- Runtime Modules:  `@nuxtjs/color-mode@3.2.0`, `@vueuse/nuxt@9.6.0`, `@nuxt/content@2.2.2`, `nuxt-icon@0.1.8`, `@nuxtjs/supabase@0.3.0`, `@pinia/nuxt@0.4.6`, `@pinia-plugin-persistedstate/nuxt@1.0.0`, `@nuxtjs/robots@3.0.0`, `nuxt-windicss@2.6.0`
- Build Modules:    `-`

### Reproduction

[https://github.com/arthurdanjou/artdanj-website-v2](https://github.com/arthurdanjou/artdanj-website-v2)

### Describe the bug

In this [line](https://github.com/ArthurDanjou/artdanj-website-v2/blob/main/src/app/router.options.ts#L26) in the router config, the element is null so the router can't scroll to the element with the hash when I switch page, but it scroll well when I reload the page

**Comment by madebyfabian** [comment]
Hey there! Please add a [minimal reproduction](https://nuxt.com/docs/community/reporting-bugs) so we can look into that properly, thank you 🙏🏻💚

**Comment by danielroe** [comment]
Looking, it seems like the issue you're reporting is with your custom scrollBehavior, rather than Nuxt.

In this case you will need to wait for the page to be fully loaded before scrolling to the element. See Nuxt's scrollBehavior for example: https://github.com/nuxt/nuxt/blob/6016aef859efe485871fe007d9b572304916ebba/packages/nuxt/src/pages/runtime/router.options.ts#L35-L46.
