### ISSUE TITLE
changing the nuxt "dir" option through a module doesn't work

### ISSUE THREAD

**Issue by fahmifitu** [nuxt/nuxt#15686]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `()`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-m8hu6q?file=nuxt.config.ts

### Describe the bug

Customizing the dir options using a module doesn't work anymore.

**Comment by clarkdo** [comment]
@pi0 This is because layout is resloved from [nuxt.options.layers[number].config.dir](https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/core/app.ts#L87), but the config in layer is not reactive when `nuxt.options.dir` is updated in modules, I have a few ideas on fixing the issue, what do you think ?

- Update `c12` to support reactive config between layers and root config
- Or use `nuxt.options` when resolving layouts, pages and ....
- Or change modules api to update layer config
- Or re-calculate layer config after modules execution
