### ISSUE TITLE
devProxy not work

### ISSUE THREAD

**Issue by KaiEi1020** [nuxt/nuxt#15804]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `ssr`, `nitro`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/KaiEi1020/nuxt-app.git

### Describe the bug

i'm use ssr mode。and i want proxy client and sever side request to another server。here is my config of  `nuxt.config.ts`，but now it not work。and if i want Authorization for my request both client and server side only in dev mode?
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  runtimeConfig: {
    apiSecre: '125',
    public: {
      apiBase: '/api/2345ty'
    }
  },
  ssr: true,
  nitro: {
    devProxy: {
      '/api/itable': {
        target: 'http://idata-staging.cai-inc.com',
        changeOrigin: true,
      },
    }
  },
})
```

**Comment by userquin** [comment]
With Nuxt 3.2.2 and Nitro 2.2.2, it only works with `ssr: false`: 
```ts
  ssr: false,
  nitro: {
    devProxy: {
      '/api/': {
        target: 'http://localhost:8080/api/',
        prependPath: true,
      },
    },
  },
```

**Comment by manniL** [comment]
Nitro's `devProxy` won't work during SSR because the call to the internal API won't be made. It will only be "emulated" to avoid an additional (and unnecessary) HTTP roundtrip. In the case of proxying though, the roundtrip would be beneficial to actually apply the proxy.

As a workaround, use the `proxy` route rule or a custom Nitro API endpoint - [as shown e.g. here](https://www.youtube.com/watch?v=J4E5uYz5AY8).
