### ISSUE TITLE
nuxt config type mismatch when using edge versions

### ISSUE THREAD

**Issue by lucassimines** [nuxt/nuxt#18512]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.1.1-rc.0-27910725.fdb31f4`
- Nitro Version:    `2.0.0-27909628.d73998e`
- Package Manager:  `npm@8.8.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-3rnspb?file=nuxt.config.ts

### Describe the bug

'tailwindcss' does not exist in type 'NuxtConfig'.ts(2345)

**Comment by RomanHrynevych** [comment]
I think that you might go with this steps and everything will be ok)
https://tailwindcss.com/docs/guides/nuxtjs#3

If you want preview, add it separately: https://github.com/rogden/tailwind-config-viewer

I made like this, because TailwindCSS will update, and i will not waiting for @nuxtjs/tailwindcss to update dependencies, do it by myself)

**Comment by manniL** [comment]
> This error is occurring on the 3.1.1 edge and not on 3.0 and 3.1

This seems to be a general problem with the edge channel  as I can also reproduce this with e.g. [3.0.1-rc.0-27905722.0236a79](https://www.npmjs.com/package/nuxt3/v/3.0.1-rc.0-27905722.0236a79)
