### ISSUE TITLE
SWR does not work in per route setup. Node preset

### ISSUE THREAD

**Issue by oneart-dev** [nuxt/nuxt#18745]
### Environment

Tested on:

- Node.js version: 16.14.2 && v18.13.0
- Nuxt ^3.1.2

### Reproduction

Minimal Reproduction:
https://stackblitz.com/edit/github-fuonyg?file=pages/index.vue

```bash
npm run build && npm run preview
```

### Describe the bug

SWR setting of 1800 seconds do not work as every page refresh we still getting freeze while promise resolved.
**Not working**
```js
routeRules: {
   '/': { swr: 1800 },
},
```

**Working**
Instant refresh as expected
```js
routeRules: {
   '/**': { swr: 1800 },
},
```

### Additional context

As mentioned in this issue (https://github.com/unjs/nitro/issues/905) nitro support per route swr and should work. But for some reasons id doesn't. No errors in the build

**Comment by danielroe** [comment]
I believe this issue is actually upstream, and is because the Nuxt renderer endpoint can render lots of different routes. The code that handles creating a cached handler is here: https://github.com/unjs/nitro/blob/ed3a48026e8a27ecfb86e406ba39bdeb418f8573/src/runtime/app.ts#L55-L64

But this isn't creating a cached event handler for `/` because `/` is only one of many paths that can be rendered by the Nuxt handler. Instead, Nitro should probably create an additional cached handler for each route rule, pointing to the same core.

I've opened a PR upstream that is one way to solve this issue: https://github.com/unjs/nitro/pull/906
