### ISSUE TITLE
Modules that import .ts files must be imported in `nuxt.config.ts`

### ISSUE THREAD

**Issue by huang-julien** [nuxt/nuxt#18793]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.1`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-jvrsel?file=nuxt.config.ts

### Describe the bug

Hi :wave: , 

I ran into an issue with my module. It need to dynamically import `.ts` files within the module.

Setting the module as a string in `modules` within `nuxt.config.ts` does not work when the module tries to import a ts file with `await import(/*   */)`.

The only workaround is to directly import the module within the `nuxt.config` and add it into the `modules` array.

Why is there a difference between declaring the module with the module name and declaring the module by directly importing it ?

### Logs

```shell-script
Unknown file extension ".ts" for ".........."
```

**Comment by madebyfabian** [comment]
If you check in the module author guide and the playground in the modules repo, you can just do import it without an extension:

https://github.com/nuxt/starter/blob/module/playground/nuxt.config.ts

**Comment by huang-julien** [comment]
Maybe did i badly explain my issue :joy: . Did you check my reproduction?
What i'm saying is that within my module [here](https://github.com/huang-julien/nuxt-runtime-compiler/blob/8e2f871afdfa2d637d8352d04f92e2c177d72b2e/src/module.ts#L146), i'm doing a dynamic import (without file extension) by using `await import(/* */)` but if my module is declared with its package name thourhg a string :
````ts
 
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  modules: [
     'nuxt-runtime-compiler', // this don't work
  ],
});
````
It won't work. This also triggers a 
`[ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs.` on windows even if i use `filePathToURL` then `thePath.href`
  
  
However directly importing it allows the module to import TS files
````ts
import nuxtRuntimeCompiler from 'nuxt-runtime-compiler';

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  modules: [
    nuxtRuntimeCompiler, // this works,
   //  'nuxt-runtime-compiler', // this don't
  ],
});
````

**Comment by harlan-zw** [comment]
Without digging into it too deeply, I believe this is because it uses jiti to pass the module when it's a string, which has a slightly different way of resolving than the node runtime.

Not sure of the exact fix, might need to include the `.ts`. 

Saying that, not exactly sure why you're trying to support build time config from app.config. Seems like you should just use the nuxt.config or am I missing something

**Comment by danielroe** [comment]
We shouldn't support importing from a runtime file like `~/.nuxt/app.config` into a build-time module. I'm more than happy to help with your particular module, separately.

As far as this issue is concerned, as long as your module is `.ts` it can import other `.ts` files. Otherwise we assume it's a built file and we use native ESM loading.
