### ISSUE TITLE
First load setting cookie in middleware fails

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#18990]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@9.3.1`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `tailwindcss`, `vite`, `schemaOrg`, `telemetry`, `algolia`, `head`, `auth`, `viewport`, `css`, `build`, `runtimeConfig`
- Runtime Modules:  `genesis-design-system/nuxt`, `@nuxtjs/algolia@1.5.0`, `@nuxtjs/tailwindcss@6.3.1`, `formidable@2.1.1`, `nuxt-viewport@2.0.3`, `@nuxtjs/partytown@1.3.0`, `@vueuse/nuxt@9.12.0`, `@nuxtjs/i18n-edge@8.0.0-beta.4-27812700.b832f07`, `nuxt-schema-org@1.1.0-beta.6`, `nuxt-icon@0.1.8`, `@pinia/nuxt@0.4.6`, `@nuxtjs/i18n@8.0.0-beta.9`, `@sidebase/nuxt-auth@0.3.4`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-agg7l3

### Describe the bug

I'm try to create cookie with h3 event functions in a server middleware, but not runs.

**Comment by danielroe** [comment]
As I commented on your previous issue:

> This is normally how it works. Cookies are set by adding a 'set-cookie' to the response object, not by modifying the incoming request. You might set an internal property on `event.context` for consumption 'within' the request.
>
> https://github.com/nuxt/nuxt/issues/18744#issuecomment-1415917259

In other words, calling `setCookie(event, /* */)` will not be read back by `getCookie(event, /* */)` because they are modifying/reading from different things. You will probably want to set `event.context.myCookie` as well as calling `setCookie` and then check with `getCookie()` as well as `event.context.myCookie`.
