### ISSUE TITLE
使用computed中的值 当值为空时 会导致重新渲染 plugins中的插件会被重复执行多次

### ISSUE THREAD

**Issue by MyJacking** [nuxt/nuxt#19170]
### Environment

https://codesandbox.io/p/sandbox/nuxt3-shu-ju-wei-kong-hui-chu-fa-plugins-7ehq1o

### Reproduction

https://codesandbox.io/p/sandbox/nuxt3-shu-ju-wei-kong-hui-chu-fa-plugins-7ehq1o

### Describe the bug

init被触发会被执行多次 具体请看简单示例

**Comment by danielroe** [comment]
The issue is that in that (prerelease) version of Nuxt, the additional request for a `favicon.ico` from the browser is being rendered as HTML (it's the second request). It's not a bug; the plugin is not running twice on the same request.

However, in the current version of Nuxt 3.2.0, favicon.ico requests are rendered with a blank GIF so you won't experience this.
