### ISSUE TITLE
Reference error when using a variable to set a custom meta property with "definePageMeta" macro

### ISSUE THREAD

**Issue by marcor2196** [nuxt/nuxt#19190]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.2`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `ssr`, `imports`, `css`, `build`, `modules`
- Runtime Modules:  `@pinia/nuxt@0.4.7`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-ttfvx1?file=pages/index.vue

### Describe the bug

If I use the macro "definePageMeta" to define a custom meta property from a variable, I receive a reference error.

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/19126

**Comment by danielroe** [comment]
Sorry, rereading that issue, it's not the same. In your case, the issue is that `definePageMeta` is a compiler macro, whereas `pageTitle` is a variable within the context of your component's setup function. `definePageMeta` does support preserving references to imports but not variables within the local scope of a `<script setup>` block.
