### ISSUE TITLE
[netlify] public folder is not generated (or used by Netlify)

### ISSUE THREAD

**Issue by championswimmer** [nuxt/nuxt#19241]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v19.6.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.2`
- Package Manager:  `npm@9.4.0`
- Builder:          `vite`
- User Config:      `modules`, `app`, `srcDir`, `alias`, `css`, `pwa`, `delayHydration`
- Runtime Modules:  `nuxt-delay-hydration@1.1.4`, `@vite-pwa/nuxt@0.0.5`
- Build Modules:    `-`
------------------------------

### Reproduction

This repository can be used for reproduction 
https://github.com/championswimmer/sharetime.zone 

Netlify Deploy Logs 
https://app.netlify.com/sites/sharetime-zone/deploys 

### Describe the bug

The contents of the public folder are not copied to the dist folder that Netlify uses. 

I am using this nitro config 

```ts
import { defineNitroConfig } from 'nitropack'
export default defineNitroConfig({
  preset: 'netlify'
})

```

**Comment by danielroe** [comment]
With Nuxt, you should not use a `nitro.config.ts`, which is ignored, but set the `nitro` property. (If you are deploying to netlify, you do not need to set this, however.)

In your case, the reason is that the `public` directory should be underneath your `src` directory. Or you can add this to your `nuxt.config`:

```js
  dir: {
    public: '../public'
  },
```
