### ISSUE TITLE
Vite Config ssr.noExternal erroring when true

### ISSUE THREAD

**Issue by CodyBontecou** [nuxt/nuxt#19254]
### Environment

Breaks in stackblitz

### Reproduction

https://stackblitz.com/edit/github-sooc2d?file=vite.config.js

### Describe the bug

I'm trying to disable SSR on a particular module using `https://vitejs.dev/config/ssr-options.html#ssr-noexternal`. Found it wasn't doing what was expected when my vite config looked like:

```js
export default {
  ssr: {
    noExternal: ['stripe'],
  },
};
```

So I tried to disable all with `noExternal: true` and saw it broke my Nuxt project.

**Comment by danielroe** [comment]
1. You should set vite options in `nuxt.config` under the `vite` key, not via a separate vite config file.
2. Instead of setting `vite.ssr.noExternal`, instead set `build.transpile` for a particular module, e.g.:

   ```ts
   export default defineNuxtConfig({
     build: {
       transpile: ['stripe']
     }
   })
   ```
3. You're right that `noExternal: true` doesn't work. Opening a PR to handle this.

**Comment by CodyBontecou** [comment]
Hmm, explicitly stating 
```js
export default defineNuxtConfig({
  build: {
    transpile: ['stripe']
  }
})
```

gives me the error `vue-router.mjs:3451 SyntaxError: The requested module '/_nuxt/node_modules/stripe/lib/stripe.worker.js?v=d75ecad6' does not provide an export named 'default'`
