### ISSUE TITLE
cancel pending `useAsyncData` requests on navigation

### ISSUE THREAD

**Issue by hymair** [nuxt/nuxt#19277]
### Environment

```
------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.2`
- Package Manager:  `pnpm@7.27.1`
- Builder:          `vite`
- User Config:      `ssr`, `app`, `modules`, `typescript`, `runtimeConfig`, `imports`, `vite`, `i18n`, `tailwindcss`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.10`, `@nuxtjs/tailwindcss@6.4.0`, `@pinia/nuxt@0.4.6`, `@vueuse/nuxt@9.12.0`
- Build Modules:    `-`
------------------------------
```

### Reproduction

https://stackblitz.com/edit/github-qs4kbe

### Describe the bug

1. Click a list item in `/items`
2. After navigation, click "Back to items" before async call is done
3. Observe console

I would expect the execution of asyncData to be cancelled if I navigate away from the route.

**Comment by danielroe** [comment]
I'm not sure this is desirable because `useAsyncData` may also be used in components that are independent of a route, like a header, or in a nested route context it may be rendered by a parent route but still present on the page even when child routes are changed.

Can you explain more about why you would like this feature, and what alternatives you have considered? 🙏

**Comment by danielroe** [comment]
You can pass an AbortController via `signal` in `$fetch` options. Here's how we do it in `useFetch`:

https://github.com/nuxt/nuxt/blob/9845467421687e5d2a588284388675fc86af63b2/packages/nuxt/src/app/composables/fetch.ts#L102-L116
