### ISSUE TITLE
Nitro - Issue importing useStorage from #imports 

### ISSUE THREAD

**Issue by JosukeH** [nuxt/nuxt#19348]
### Describe the feature

When install @vue-use and using useStorage from nitropack I need to import the useStorage from Nitro, problem that I can´t import from #imports

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by JosukeH** [comment]
import { defineEventHandler, H3Event, useStorage } from "h3";
                                                                         ^^^^^^ => this throw error 
import { useStorage } from "#imports";
 ^^^ this throw error

export default defineEventHandler(async (event: H3Event) => {
  // @ts-ignore
  const { id } = event.context.params;
  console.log(id);

  const user = await useStorage().removeItem(`${id}`);
  if (!user) {
    return {
      error: false,
      errorMessage: "Not user yet",
      auth: false,
    };
  }
  return user;
});

**Comment by Baroshem** [comment]
Hey, could you create a reproduction in stackblitz? :)

**Comment by JosukeH** [comment]
Of course, there is. 

the unique diference is  like i´m using air bnb eslint linter on my project. 

i'm using typescript with nuxt3 

https://stackblitz.com/edit/nuxt-starter-6xlxea?file=server%2Fapi%2Fhi.get.ts,package.json

**Comment by JosukeH** [comment]
is more than it  can find the module of useStorage of Nitro than other thing. because using eslint disable it works. 

I also try to create my types of nitro using yarn nuxi prepare

like the documentation but I could yet import succesfully my utilities from Nitro!

https://nitro.unjs.io/guide/introduction/typescript

**Comment by Baroshem** [comment]
I am afraid that I cannot run your reproduction link :(

![image](https://user-images.githubusercontent.com/37120330/222705113-b9aa4b21-c05a-46a2-8787-c16d7c7ad132.png)

**Comment by danielroe** [comment]
This seems to be working fine on the latest version of Nuxt v3.5: https://stackblitz.com/edit/nuxt-starter-mtzpn7.

Let me know if not and I'll happily reopen.

**Comment by arimaulana07** [comment]
> This seems to be working fine on the latest version of Nuxt v3.5: https://stackblitz.com/edit/nuxt-starter-mtzpn7.
> 
> Let me know if not and I'll happily reopen.

I had the same issue when developing nuxt module, as the doc said i need to explicitly import from '#imports'  but it seem useStorage is not exported in '#imports'. It works when i run on the playground without explicit import though, but when i publish and install it in my project it throw error "[nuxt] [request error] [unhandled] [500] useStorage is not defined".  Im using nuxt v3.8.2

**Comment by danielroe** [comment]
@arimaulana07 Within module runtime code you need to explicitly all auto-imports from `#imports` - even if it works in the playground without it. This is because, for performance reasons, once your modules code is bundled into `node_modules`, we do not scan it for auto-imports.

**Comment by rrd108** [comment]
@danielroe How do you do that in a module's test file?

I want to clear the storage before all my test cases, so I want to use `useStorage().clear()` in my test's `beforeEach`.

In my nuxt module's code `import {useStorage} from '#imports'` resolves and work as expected, but in my test file it does not, I get `'"#imports"' has no exported member named 'useStorage'`

**Comment by rrd108** [comment]
Hi @danielroe,

I apologize for pinging you in this closed issue, but I've been stuck on this problem for almost two days now and would greatly appreciate your help.

Here is my test case:  https://github.com/rrd108/nuxt-api-shield/blob/main/test/basic.test.ts

I need to test what gets stored in `useStorage` without mocking it, but I haven't been able to figure out how. If I don't clear the store (as it is right now), my test fails because the storage retains data from the first test when running the second test.

If I uncomment the `import` and add `clear` in the `setup`, I encounter this error:

`TypeError: Package import specifier "#internal/nitro/virtual/app-config" is not defined in package /home/rrd/nuxt-api-shield/node_modules/nitropack/package.json imported from /home/rrd/nuxt-api-shield/node_modules/nitropack/dist/runtime/config.mjs`

I'm pretty sure I'm just missing something simple here. Any guidance would be extremely helpful.

Thank you in advance for your assistance!

**Comment by danielroe** [comment]
@rrd108 Probably because we don't yet provide a way to test _server-side_ code in a runtime environment - but this is on the roadmap - see https://github.com/nuxt/test-utils/issues/531.
