### ISSUE TITLE
Warn when a page uses a layout but no `<NuxtLayout>` is created

### ISSUE THREAD

**Issue by Atinux** [nuxt/nuxt#19392]
Following nuxt/nuxt#19388

It happens to me as well, since we have the `app.vue`, people can easily forget to add the `<NuxtLayout>`.

What if we have a variable to track if the NuxtLayout is instanciated (default to `false` and we set to `true` once created) and check if the project has layouts (including layers).

**Comment by luc122c** [comment]
Hello, I'd love to have a go at this. Where would be the best place for this variable, does Nuxt have an internal store of some kind? Also, I presume we'd only like this warning to be during development, and excluded from a production build?

**Comment by danielroe** [comment]
Yes, I think this should be a dev-only warning.

I think we could have a property we set on the `nuxtApp` itself in development, when a layout is loaded. And maybe a plugin which is added in dev mode, if there are layouts, which uses a hook (maybe `page:finish` or in `onNuxtReady` callback?) to check whether a layout was instantiated...

**Comment by luc122c** [comment]
I've made a start in #24116. I still need to create the logic to detect the layouts, but the plugin and surrounding work is there. 

I've placed the variable in `nuxtApp.payload.isNuxtLayoutUsed`, if there is a better place please let me know. 

I got a warning about not being able to use `import.meta.env` outside of a module, but `isDevelopment` from 'std-env' worked and should have the same effect, so I've opted to use that instead. I hope that's ok?

Lastly, I attempted to use the consola logger from `@nuxt/kit`, rather than `console.log` but got a warning: "This module cannot be imported in the Vue part of your app."
