### ISSUE TITLE
this.$route updates in the current page before next page's 'asyncData' in defineNuxtComponent is resolved

### ISSUE THREAD

**Issue by fahmifitu** [nuxt/nuxt#19481]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `ssr`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-kou34x-c7cfxj?file=pages/posts/[id].vue

### Describe the bug

Reproduction:
1. From index,  go to the post page
2. Go to the mountain page.

It's caused by the change of `this.$route.params.id` inside the computed property in each [id] page before the route actually finishes navigation. you can even see that NuxtLoadingIndicator didn't finish the transition animation but `$route.params` is already updated while it's still on the old page.

Check the console log

### Additional context

This causes countless issues for me. especially when migrating my apps from nuxt 2. I have similar functionality based on route values.

**Comment by danielroe** [comment]
This is caused upstream Vue behaviour (suspense does not current support suspending injected properties like `$route`).

We have already implemented a workaround for this behaviour within Nuxt but you will need to use `useRoute()` in setup to get access to the route rather than using `$route` - or you can experimentally inject '_route' (but this is undocumented and may break in future).
