### ISSUE TITLE
Imports are not treeshaken when only called within onMounted

### ISSUE THREAD

**Issue by huang-julien** [nuxt/nuxt#19506]
### Environment

Nuxt 3.2.3

### Reproduction

https://stackblitz.com/edit/nuxt-starter-fczwwe?file=app.vue,oldapp.vue,components%2Fleaflet%2FMap.client.vue
Remove the `.client` from `Map.client.vue`

### Describe the bug

we expect the component to work normally in SSR since `onMounted` is supposed to be treeshaken (and so, the import with it). 
But Leaflet contains side-effects and is being inlined inside a server chunk, crashing the SSR.

**Comment by manniL** [comment]
You pointed the issue out already: As you import leaflet via `import L from 'leaflet'`, it exists on both, client- and server-bundle and because the package has side effects, errors will arise.
Not sure if there is a better way for Nuxt to handle this - but I'm curious for ideas 😋

A workaround would be importing Leaflet in `onMounted` via dynamic import instead.

**Comment by manniL** [comment]
As discussed in the weekly meeting, documenting such scenario for modules with side-effects depending on browser APIs would be most helpful (examples, non-exhaustive list of packages where it apples)

**Comment by huang-julien** [comment]
I'll do it probably this weekend :+1:
