### ISSUE TITLE
Nuxt 3 should append <style> in pages AFTER <style> in layout

### ISSUE THREAD

**Issue by duc2019** [nuxt/nuxt#19551]
### Describe the feature

In nuxt 2, <style> defined in pages will append after <styles> defined in layout.
But in nuxt 3 <style> defined in layout will come later which make overriding css in pages much more diffucult.

I know we can use scoped but that will mean styles in page will no longer applied to child components.
For now the workround we used is add !important for css rules defined both in page and layout.

Please change this to make people using nuxt 2 able to migrate to nuxt 3 eaiser.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
I'm sorry for the inconvenience, but I'm reluctant to do this for several reasons:

1. I don't think you should write code that depends on the order in which the layout or pages CSS is bundled.
2.  I don't want to commit to users that it will follow a certain order because this is likely upstream bundler behaviour (ie Vite) rather than directly within Nuxt's control.
3. It would be a breaking change if (heaven forbid!) someone is now depending on page CSS being loaded before layout CSS

**Comment by duc2019** [comment]
> I don't think you should write code that depends on the order in which the layout or pages CSS is bundled.
Order and priority of CSS matter, we need to handle css style overriding thus **this should be a defined behavior** for the framework and the bundler.
Sure we can use specificity and `!important` to improve compability, but if the framework combines style from layout, page and components out of order, things get complicate, there are high risk website design break after internal implementation changed.

Maybe I should report this to vite.

From a common sense standpoint, if people writing css style in both layout and page, I don't think there are situations they want css style in layout take the priority.
In Nuxt 2 and Webpack 4 this works out of box.

Anyway I don't have expectation that Nuxt or Vite will fix this issue, I will fix style breakage myself for the project I migrating from Nuxt 2. Web developers are paid for handling this kind of mess.

**Comment by dsvgl** [comment]
Just stumbled upon this. Tested this behaviour with a fresh nuxt app and it indeed behaves like @duc2019 described.

> I don't think you should write code that depends on the order in which the layout or pages CSS is bundled.

Are there some docs that describe this? I (naively) would assume, that layouts wrap pages and therefor when defining styles in both, layout styles would come before page styles. Without this being document, how should we know?
Could we add a hint to the layout docs? Maybe also to pages docs.

> Web developers are paid for handling this kind of mess

Yeah, that's true 😄 
I'm currently planing our migration from Nuxt 2 to Nuxt 3 (multi/whitelabel app). And we have exactly this situation. In a lot of places. 🙈

**Comment by duc2019** [comment]
After publish our project to testing environment with `nuxt generate` I found the bundle **will combine css styles from multiple pages into entry.xxx.css randomly**, even you use the `manualChunks` to return a unique id for each page vite will still ignore your chunk name and suck some of your pages into entry.xxx.css.

The implementation of Nuxt 3 and Vite is so broke,  did you guys even work for an actual project with Nuxt 3 or just create your toy projects for fun??? Can't you guys implement the logic with basic human common sense??? WHY combine css from multiple pages that is not scoped??? WHY???

I will suggest any people migrate to Nuxt 3 **must use style with scoped**, otherwise you will 100% shoot your foot.

**Comment by danielroe** [comment]
Nuxt is not involved in the creation of your CSS file. Vite is bundling your CSS assets together and if you feel this is a bug you should raise it upstream at https://github.com/vitejs/vite.

As I've said, it's best practice to use scoped styles in any Vue project (adopting scoped styles is also relatively simple as part of a migration). In my experience, in and out of Nuxt, you should not rely the _order_ of CSS from different components being loaded, only within a component's CSS. Otherwise you are very likely to produce flaky CSS that is tied to a particular build process. Consider the case, for example, where each layout styles the body tag differently. As a new layout CSS file is loaded, the body tag will change its style. But CSS will never be unloaded, and so when you switch back to the old layout nothing will change. That's not a bug in the bundler or framework - it's a user error in how the layout was written. And this is similar.

I hope that helps, and best of luck on your migration.

**Comment by dsvgl** [comment]
thx Daniel for the explanation. I still think it would be good to add this info to the docs of Layouts and Pages.
I'll try to make a PR next week...

**Comment by duc2019** [comment]
- We did isolated css in **components**, but not in **pages**, nuxt 2 (webpack) will never mix css styles from multiple pages, but nuxt 3 (vite) will and there are noway to prevent it
- Yes I should report this to vite, I will open an issue there later
- Please add docs to warning users never use style without scoped, because vite will mix your css style from anywhere with any order (it sucks)

**Comment by danielroe** [comment]
You might consider, in that case, to use the webpack builder in Nuxt 3 to keep consistency with Nuxt 2.
