### ISSUE TITLE
ERROR  [worker reload] [worker init] ENOENT: no such file or directory, mkdir '/tmp/nitro'

### ISSUE THREAD

**Issue by xdewx** [nuxt/nuxt#19564]
### Environment

```
- Operating System: `Linux`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `modules`, `fetch`, `env`, `runtimeConfig`, `publicRuntimeConfig`, `privateRuntimeConfig`, `nitro`, `alias`, `ssr`, `strapi`, `vite`, `meta`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.4.1`, `@vueuse/nuxt@9.13.0`, `@nuxtjs/strapi@1.6.3`
- Build Modules:    `-`
```

### Reproduction

1. `npm run dev` is normal
2. deploy in docker, and start with `npm run dev` failed

### Describe the bug

1. can't start in docker
```
ipa         |   at mkdirSync (node:fs:1334:3)
ipa         |   at getAddress (.nuxt/dev/index.mjs:824:5)
ipa         |   at .nuxt/dev/index.mjs:828:23
ipa         |   at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
ipa         |   at async Promise.all (index 0)
ipa         |   at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
ipa         |   at async loadESM (node:internal/process/esm_loader:88:5)
ipa         |   at async handleMainPromise (node:internal/modules/run_main:65:12)
```

**Comment by xdewx** [comment]
It turns out the problem was caused by `no enough disk space`. I would suggest that nuxt throws comprehensible errors

**Comment by danielroe** [comment]
Glad things were resolved. I suspect the error is coming from Node rather than Nuxt. Improving the error message would be nice if possible. I can't really tell without the full stack trace + error but it's likely coming from calling `mkdirSync` here:

https://github.com/unjs/nitro/blob/6541373545ee2716566bce46c7568ad2c3164cdf/src/runtime/entries/nitro-dev.ts#L13-L25

cc: @pi0 if he has any ideas, but I'm not personally sure there's a performant way to handle this edge casae
