### ISSUE TITLE
`nuxt build` changes NODE_ENV

### ISSUE THREAD

**Issue by rutgerbakker95** [nuxt/nuxt#19819]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.14.1`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `srcDir`, `runtimeConfig`, `vite`, `modules`, `i18n`, `tailwindcss`, `apollo`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.10`, `@nuxtjs/tailwindcss@6.6.0`, `@nuxtjs/apollo@5.0.0-alpha.5`
- Build Modules:    `-`

### Reproduction

[WARN] Changing `NODE_ENV` from `staging` to `production`, to avoid unintended behavior.

### Describe the bug

Is there a way to prevent Nuxt from automatically changing `NODE_ENV` to `production` when I use export `NODE_ENV=staging` in my pipeline?

**Comment by pi0** [comment]
This was a required workaround we needed to do because tools such as postcss(plugins) was having unexpected behavior when `NODE_ENV` is not `production`. (cc @Atinux if you remember more).

WHat is your main usage for `NODE_ENV = staging` is it used for runtimeConfig or other logic conditions? (we might think about a temporary restore of user-provided env to resolve both logics, however can be tricky and more info would be nice)

**Comment by danielroe** [comment]
I agree with @pi0. I don't think we can support alternative `NODE_ENV` values. This is not where you should set your app's environment; it's a protected Node environment variable with a limited list of valid values. I would recommend instead using `APP_ENV` or similar.

**Comment by rutgerbakker95** [comment]
@danielroe Ok, I'll try to make it work with `APP_ENV`
