### ISSUE TITLE
useFetch called twice When the network is disconnected

### ISSUE THREAD

**Issue by lssdo12** [nuxt/nuxt#19922]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@9.6.1`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

None

### Describe the bug

sever/api/hello.ts
```
export default defineEventHandler(() => {
  return {
    api: 'works'
  }
})
```

app.vue
```
  await useFetch('/api/hello', {
    onRequestError({ request, options, error }) {
      alert('error')
    }
  })
```
useFetch called twice When I use the developer tool to adjust my network to offline,Then the webpage popped up twice

![屏幕截图 2023-03-26 122828](https://user-images.githubusercontent.com/59727014/227755431-1ae4a233-dded-439e-8be1-fc357e1f3567.png)

**Comment by smorrin28** [comment]
As far as I'm aware, Nuxt uses [ofetch](https://github.com/unjs/ofetch) for fetching their data which by default does one retry if the request fails, thats why it probably does two tries in your case. To disable this behavior,  you fetch your data like this: 

```javascript
const { data } = await useAsyncData(() => $fetch("/api/hello", {
     onRequestError({ request, options, error }) {
      alert('error')
    },
   retry: 0,
}));
```

Notice the extra retry parameter which should disable the auto retry. I don't think there's a way to configure fetch so that it never retries a request for all your fetches, so if you need this kind of functionality often, I would suggest making your own composable in the composables directory like this: 


```javascript
const useFetchWithoutRetry = (url, options) => useAsyncData(() => $fetch(url, {
    ...options,
   retry: 0,
}));
```

Hope this helped. If you need more info about the $fetch hook, you'll find it here: https://nuxt.com/docs/api/utils/dollarfetch and if you need more infos about composables, you'll find them there: https://nuxt.com/docs/guide/directory-structure/composables
