### ISSUE TITLE
Page that gets redirected via navigateTo in a middleware still gets executed

### ISSUE THREAD

**Issue by prashantpalikhe** [nuxt/nuxt#20294]
### Environment

| Key              | Value       |
|------------------|-------------|
| Operating System | Linux       |
| Node Version     | v16.14.2    |
| Nuxt Version     | 3.4.1       |
| Nitro Version    | 2.3.3       |
| Package Manager  | npm@7.17.0  |
| Builder          | vite        |
| User Config      | -           |
| Runtime Modules  | -           |
| Build Modules    | -           |

### Reproduction

https://stackblitz.com/edit/nuxt-starter-7ebm3j

Go to the route `/i-get-redirected` 

### Describe the bug

There are two pages. 

1. i-get-redirected.vue
2. i-get-displayed.vue

`i-get-redirected` gets redirected to `i-get-displayed` via a global route middleware `redirect.global.ts`.  So I expect the code from the page `i-get-redirected` not to be executed. But it does.

<img width="478" alt="image" src="https://user-images.githubusercontent.com/2657709/232196796-961679c8-d44c-4016-91be-3493dfc5c3d9.png">

**Comment by danielroe** [comment]
Linking here https://github.com/nuxt/nuxt/pull/20244 which should have fixed this issue.

**Comment by davidstackio** [comment]
In my case, I have a link on my page (`/apply`) that gets redirected to an external URL in global middleware to a Google form.

Not sure if it's related to this, but I get a console warning. I understand that this is Vue Router saying that I don't have a route for the page, which I'm okay with, but it would be nice if it somehow checked for redirects too. This is the warning:
```
[Vue Router warn]: No match found for location with path "/apply"
```

My `01.redirects.global.ts` file looks like this:
```
const redirects = [
  {
    from: "/apply",
    to: "https://forms.gle/abc",
  },
];

export default defineNuxtRouteMiddleware((to) => {
  // Redirect the user if the route is in the redirects list
  redirects.forEach((path) => {
    if (to.path === path.from) {
      return navigateTo(path.to, { external: true });
    }
  });
});
```

**Comment by prashantpalikhe** [comment]
@davidstackio Can you create a repro for your issue? 

Looking into the current implementation of `navigateTo`, external links are direcly redirected. Unlike, internal links, which are deffered until `router.afterEach` (that causes the original issue).

So, the issue that you are experiencing should not happen in `3.4.1`

**Comment by davidstackio** [comment]
@prashantpalikhe I forgot to mention in my post, but I have a link to `/apply` on a page in my app. Since that page doesn't exist (it's the redirect), Nuxt briefly shows the 404 error page, but then correctly redirects to the external URL. The issue I'm encountering is the brief flash of the 404 error page.

However, when visiting the `/apply` route directly (pasting it in the browser address bar), it *does* seem to get correctly redirected (no 404 error page flash). This is the logic (which I think is why it's affected by this issue): internal link -> 404 page -> external redirection

Does that clarify?

**Comment by prashantpalikhe** [comment]
@davidstackio Clear! Could reproduce it in the Stackblitz I shared too.

**Comment by huihuilovekuikui** [comment]
> Linking here #20244 which should have fixed this issue.

v3.4.2 still has the problem

**Comment by Laruxo** [comment]
Thanks a lot @danielroe this appears to be fixed in v3.4.3 👏 However I see that now returning `navigateTo` inside middleware causes `app:error` hook to be called. [See this code](https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/app/plugins/router.ts#L243-L249). Is this expected, or should I create a new issue?

**Comment by danielroe** [comment]
No, I would only expect that hook to be called if it is an error (e.g. a 404).

**Comment by huihuilovekuikui** [comment]
@danielroe 
v3.4.3 use redirect still render twice
#20468 
https://stackblitz.com/edit/github-zefysc?file=pages%2Findex.vue,pages%2Fabc.vue,app.vue

**Comment by prashantpalikhe** [comment]
Also noticed the setup function of the destination page gets called twice. I will create a new issue for it.

**Comment by huihuilovekuikui** [comment]
#20468 @danielroe 
The issue should be reopened

**Comment by danielroe** [comment]
@huihuilovekuikui The reproduction you link does not show the setup function of the redirected page being executed at all.

**Comment by huihuilovekuikui** [comment]
@danielroe 
Because it only happens when you first enter the "index.vue" page, If you run and copy the following link to open it in a browser, you will find that the setup function of "abc.vue" is executed twice
![image](https://user-images.githubusercontent.com/66559869/236398194-9dc799ef-720d-4914-a9d3-61f7222bed49.png)
![image](https://user-images.githubusercontent.com/66559869/236398244-787e6f2e-a0ca-4c81-b524-1cc8b4555e68.png)

**Comment by danielroe** [comment]
That is a different issue, and referenced above by @prashantpalikhe , who is already creating a new issue to describe it.

**Comment by huihuilovekuikui** [comment]
Ok，Can you tell me the number of issue? I want to keep track of this problem.

**Comment by prashantpalikhe** [comment]
@huihuilovekuikui This is the issue.

#20703
