### ISSUE TITLE
`scrollToTop: true` doesn't work for nested pages

### ISSUE THREAD

**Issue by enkot** [nuxt/nuxt#20523]
### Environment

- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.2
- Nitro Version:    2.3.3
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-dnxhpa-aauftw?file=pages/account/address.vue

### Describe the bug

1. Go to the "Account" page
2. Scroll a little
3. Go to the "Address" page

The page should scroll to the top, because it is specified in `definePageMeta`. But it doesn't.

If change the condition in https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/pages/runtime/router.options.ts#L21 to:
```ts
if (!position && from && to && (to.meta.scrollToTop === true || _isDifferentRoute(from, to))) {
```
it works as expected.

**Comment by mercs600** [comment]
the same issue

**Comment by AndrewBogdanovTSS** [comment]
@danielroe could you check this one? Thank you.

**Comment by andysay** [comment]
approve , nested pages not accepted     if (process.client) {
      window.scrollTo(0, 0);
    }

**Comment by IsraelOrtuno** [comment]
The problem is here:
https://github.com/nuxt/nuxt/blob/95fab0a2dd59b7cce9f73c8d66b7f518b786aea6/packages/nuxt/src/pages/runtime/router.options.ts#L60-L69

It's comparing against parent routes only:

```ts
const samePageComponent = a.matched[0] === b.matched[0] 
```

Since `scropToTop` behaviour could be disabled per route using `definePageMeta({ scrolToTop: false })` couldn't we remove this compare function? Not sure if there are side effects.

cc @danielroe

**Comment by danielroe** [comment]
Nice find. I think probably we can update this compare function to respect nested routes 👍
