### ISSUE TITLE
Passing the data to layout returns _rawValue: null, useFetch, useAsyncData doesnt ssem to be working correctly

### ISSUE THREAD

**Issue by whAkira** [nuxt/nuxt#20540]
### Environment

Environment
Operating System: Windows 10
Node Version: v18.12.1
Nuxt Version: 3.4.2
Package Manager: npm@9.6.5
Builder: vite
User Config: -
Runtime Modules: -
Build Modules: -

### Reproduction

No repo

### Describe the bug

Try to fetch the data from laravel api, and then pass it as props to default layout, i used useFetch, useAsyncData, but the data is fetched on main page and when i pass it to layoyt i recieve _rawValue: null, when i do the same in my layout component the data returned is null, and after a few seconds the response changes, but the component has already been rendered without data, havent found the solution yet

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by whAkira** [comment]
![image](https://user-images.githubusercontent.com/119469450/234783205-c7d911a3-4a32-4c09-a24c-de30b994e55a.png)
![image](https://user-images.githubusercontent.com/119469450/234783348-d9a50455-7ec9-4c49-b1a9-785dac0703b3.png)
![image](https://user-images.githubusercontent.com/119469450/234783436-5d18e55c-741d-4472-841e-ffda4baa0ed1.png)
![image](https://user-images.githubusercontent.com/119469450/234783521-b32c8f85-dc9e-4230-9f9b-71ae9ab3878a.png)

there is a complex backend so i can not do a full reproduction but instead here are some screenshots, i can uncomment code press ctrl+s and then data is recieved i can do it an infinite number of times the result is the same but as sson i as i refresh the page the data is null

**Comment by whAkira** [comment]
Issue resolved, updating node to current node@v18.16.0

**Comment by marcin-iwanicki** [comment]
I do not confirm.
I have the same problem except that my request sends an authorization cookie and if I don't set setTimeount to 500 it doesn't include the cookie in the request. If I change something in the code then HMR works fine and cookies are added, same if I use NuxlLink it works fine too, the problem is when I refresh the page in the browser.
I have Nuxt 3.4.2 and node 18.16.0

This don't work

`<script lang="ts" setup>

import {useAuthToken} from "~/composables/useAuthToken";

onMounted(async () => {  

       const { data } = await useAuthToken();
      console.log('Index: Data: ', data.value);   

})`




This work
`<script lang="ts" setup>

import {useAuthToken} from "~/composables/useAuthToken";

onMounted(() => {

    nextTick(async () => {
        const { data } = await useAuthToken();
       
        console.log('Index: Data: ', data.value);
    
    })

})`

**Comment by danielroe** [comment]
@marcin-iwanicki Feel free to raise an issue with a reproduction.
