### ISSUE TITLE
`callWithNuxt` returns old params from `useRoute` after the await

### ISSUE THREAD

**Issue by darioferderber** [nuxt/nuxt#21283]
### Environment

RootDir: /home/projects/nuxt-starter-vpjjyq
Nuxt project info: 

------------------------------
- Operating System: Linux
- Node Version:  v16.14.2
- Nuxt Version:  3.5.2
- Nitro Version:  2.4.1
- Package Manager:  npm@7.17.0
- Builder:  vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-vpjjyq?file=pages%2Fdetail%2F%5Bid%5D.vue

### Describe the bug

When using top-level await, `callWithNuxt` returns "old" context(?)

Try navigating from `/category/category-id` to `/detail/detail-id`.
`params.id` will be `detail-id` at first, but it will change to `category-id` after the **await** 

```ts
await getID();

async function getID() {
  const nuxt = useNuxtApp();
  id.value = useRoute().params.id; // -> detail-id

  await new Promise((resolve) => setTimeout(resolve, 1));

  const route = await callWithNuxt(nuxt, useRoute); 
  id.value = route.params.id; // -> category-id
}
```

it seems like the old context is restored instead of new.

**Comment by danielroe** [comment]
The issue here is that the context we need during route transition is actually the _vue_ context rather than the Nuxt context, which is global.

During a route transition, we actually have two vue contexts, passed to the two forks of suspense:
1. fork for displaying current page
2. fork for displaying new route (in background until page is loaded)

Once the page loads, we then update the route within the Nuxt context to be the new route, but until that point it will display the old one. This is so that components located 'outside' of the Suspense don't update too early.

When you call `useRoute` directly in setup, we can correctly display the right fork. But when you explicitly use `callwithNuxt`, then we fall back to the 'global' Nuxt context which has the 'old' route.

I would suggest calling `useRoute` outside of the handler function (or at the beginning) and then _using_ this route data within it.

**Comment by darioferderber** [comment]
Thank you for the explanation! 🙂 

I've done exactly as you said, but I wasn't sure if there is a better workaround for this (or is this a bug). It seemed wrong to have 2 different contexts, but it makes sense now.

Cheers!
