### ISSUE TITLE
HMR in Gitpod + VS Code Browser

### ISSUE THREAD

**Issue by MehrdadKhnzd** [nuxt/nuxt#21341]
Hi,

I'm having a hard time fixing HMR while developing on Gitpod using VS Code Browser.
Apparently, it's working on Vite normally, but it doesn't with Nuxt.
I tried everything I found online, but it seems I'm stuck in a chicken-and-egg problem.

Please refer to this URL for the context:
https://www.gitpod.io/docs/introduction/languages/javascript#vite

Any ideas on what can be the problem and how to make it work in Nuxt?
I can let you know the specific behavior of specific settings if it helps.

Thanks!

**Comment by ghostdevv** [comment]
Nuxt is trying to connect over a different port (24678) than the one that the http server is on (3000), which isn't working here because of how Gitpod handles port connections (https://PORT-WORKSPACE.... instead of https://DOMAIN:PORT)

I remember when Vite 3 fixed this but never pin pointed the exact change that caused it, wonder if anyone from the nuxt team/community has any ideas

![image](https://github.com/nuxt/nuxt/assets/47755378/8cdc94e1-3a6d-42f7-be6c-f89ceb163519)

**Comment by ghostdevv** [comment]
Nuxt seems to be using the `24678` port [here](https://github.com/nuxt/nuxt/blob/63cf6a5d65e9742c5794c3904574a87fe000cf2c/packages/vite/src/client.ts#L111), from what I can tell the [behaviour in vite](https://github.com/vitejs/vite/blob/471fba2d1cf647a0bea747739d4d90def60e83ce/packages/vite/src/node/plugins/clientInjections.ts#L40) is to use the `clientPort` which would be `3000` here and if that isn't defined use `24678` - I think the behaviour there should be replicated into nuxt? If the extra code is needed at all

**Comment by ghostdevv** [comment]
I think it may be [this pr](https://github.com/vitejs/vite/pull/8650) that fixed the issue in vite 3 - by doing the behaviour described in my above comment (hmr over the server port - i.e. 3000 in nuxt)

**Comment by MehrdadKhnzd** [comment]
Any updates on this?

**Comment by MehrdadKhnzd** [comment]
#23206 Finally fixed the issue. Thanks!

**Comment by ghostdevv** [comment]
Amazing!
