### ISSUE TITLE
Page "scroll to top" when navigating to next route

### ISSUE THREAD

**Issue by zhuscat** [nuxt/nuxt#21502]
### Environment

- Operating System: Darwin
- Node Version:     v16.15.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.5.1
- Builder:          vite
- User Config:      app, devServer, build, vite, vue, modules, image, css, components, i18n, pinia, imports, routeRules, appConfig
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.11, @unocss/nuxt@0.51.13, @pinia/nuxt@0.4.11, @nuxt/image-edge@1.0.0-28059208.2abef1b, @nuxt/content@2.6.0
- Build Modules:    -

### Reproduction

The Nuxt official website can reproduce this BUG

### Describe the bug

Here is the screen record：
![20230610114715_rec_](https://github.com/nuxt/nuxt/assets/14963619/2f219b19-57fd-42f1-b651-e290b461c1f0)

After I clicked the "Try it now" button, the content on the page flashed suddenly, which looks like it scrolled to the top

**Comment by zhuscat** [comment]
Is this a BUG? Hope to receive response!

**Comment by ennioVisco** [comment]
Asked a billion times, check this thread https://github.com/nuxt/nuxt/discussions/16223

**Comment by danielroe** [comment]
This issue is about a quick scroll to the top before navigation, and I don't believe this is reproducible any more with basic Nuxt.

It is, however, reproducible with `@nuxt/ui-pro` apparently because of the custom scrollBehavior (cc: @benjamincanac).

If you're still encountering this and not using `@nuxt/ui-pro`, please do provide a minimal reproduction and I will happily investigate further. 🙏
