### ISSUE TITLE
teleport to specific element 

### ISSUE THREAD

**Issue by yaquawa** [nuxt/nuxt#21597]
### Describe the feature

I hope this works in SSR mode.
currently I have to wrap it in `<client-only>`.

```vue
<teleport to="#test">
  <div>test</div>
</teleport>
```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
Yes, you must wrap teleports in `<client-only>` unless you are teleporting to `body`, which Nuxt will handle for you.

**Comment by yaquawa** [comment]
Hi @danielroe, Yes I notice that limitation so I created this topic. I don't think this should be closed.

**Comment by danielroe** [comment]
No, we wouldn't support them fully. In order to 'render' such teleports on the server we would need to parse the HTML and insert them in the appropriate place in the DOM, which is a heavy performance cost.

Moreover, it's very clear that `<Teleport>` should _not_ be used to teleport to an element _within_ your Vue app unless you are quite sure you know what you are doing, so the potential benefit/use case seems small.

On the other hand, I would be up for improving the DX here, such as automatically wrapping `<Teleport>` with `<ClientOnly>`.

**Comment by yaquawa** [comment]
Got it, thanks:)
