### ISSUE TITLE
There is still external CSS when inlineSSRStyles is true

### ISSUE THREAD

**Issue by abdAbdaldeen** [nuxt/nuxt#21762]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.16.0
- Nuxt Version:     3.6.0
- Nitro Version:    2.5.1
- Package Manager:  pnpm@8.6.2
- Builder:          vite
- User Config:      devtools, experimental
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

repo: https://github.com/abdAbdaldeen/nuxt-3-inlineSSRStyles

### The current behavior:
The component style will be added as external CSS when it has been reused in more than one place even if `inlineSSRStyles: true,`

![image](https://github.com/nuxt/nuxt/assets/71769628/7aa1a7ac-4a48-469e-aeb4-8bda0029203c)

please note that:
1. component-1 is the reused component
2. component-2 is used only once

### The expected behavior:
all styles must be inline

same as NUXT 2 when you set `build.extractCSS = false`
https://v2.nuxt.com/docs/configuration-glossary/configuration-build/#extractcss

**Comment by danielroe** [comment]
By design, `inlineSSRStyles` doesn't inline all CSS. This is for several reasons:
* we want to keep CSS files external so the CSS does not have to be added to the JS bundle (for client-side navigation)
* therefore although we can inline CSS on server renders, we still have to have CSS files.
* as much as possible we want to reduce duplication, so if we inline styles we shouldn't also load them in CSS _if possible_

However, there's definitely space for improving this implementation. Contribution is very welcome, but this issue itself is not a bug.

**Comment by abdAbdaldeen** [comment]
@danielroe Thanks, but I still have a question, **is there any way to inline all CSS?**

**Comment by danielroe** [comment]
Not yet, no.
