### ISSUE TITLE
how to copy public folder when change dir.public

### ISSUE THREAD

**Issue by motea927** [nuxt/nuxt#21831]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.1
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      vite, dir
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-kf4vv3?file=nuxt.config.ts,app.vue

### Describe the bug

When change `dir.public` and `vite.publicDir`，it can work at dev, 
But `public` folder not copy at production, maybe just a config error

### Additional context

Step

1. `npm run dev` (can see image)
2. `npm run build`
3. `node .output/server/index.mjs` (can not see image)

**Comment by NozomuIkuta** [comment]
@motea927 

Nuxt seems to not resolve/normalize the paths (i.e. `vite.publicDir` and `dir.public`) on build.

At the moment, it works if the paths are relative.

```ts
export default defineNuxtConfig({
  vite: {
    publicDir: 'customPublic',
  },
  dir: {
    public: 'customPublic',
  },
});
```

---

@danielroe 

It this intended behavior?
If so, I would submit a PR to clarify it in documentation (I appreciate if you explains differences between `vite.publicDir` and `dir.public`, so that I could include it in my PR).

If this is a bug, I will look into the codebase.

**Comment by danielroe** [comment]
You should not (need to) configure `vite.publicDir`. (We should probably disallow setting this specifically to force people to set `dir.public` instead.)

If it is not working to set `dir.public` on its own, then that is something we should also fix.

**Comment by motea927** [comment]
After test, dir.public can not use `absolute path`(path.resolve), it will cause bundle public path error,
And use `/customPublic` can not work,
Only `customPublic`(without slash) can work.
