### ISSUE TITLE
nuxt.config.ts hooks listen not working

### ISSUE THREAD

**Issue by chaos-zhu** [nuxt/nuxt#22288]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.9
- Builder:          vite
- User Config:      devServer, hooks, devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-y8kzzg?file=nuxt.config.ts

### Describe the bug

Using dev is normal
![image](https://github.com/nuxt/nuxt/assets/44160914/82e62b84-c561-4090-9b92-f26e0b8711f7)

Use `npm run build`   `node .output/server/index.mjs`  is not executed, hooks No longer execute
```bash
Listening http://[::]:3000
```
not any more...

**Comment by chenyuncai** [comment]
accroding to old issues, the nitro node-server preset didnot fire a listen hook when server created just because of the dev mode using a local socket. But for real usse case, developer known the difference. In some cases, we will make a patch to nitro preset to fire the exact event or just make a custom preset. It's not easy to handle websocket request for now.

**Comment by chaos-zhu** [comment]
Yes, I checked the official guidelines carefully. nitro preset works for this situation, but how to launch nitro preset in nuxt dev mode, that's the question.  https://nitro.unjs.io/deploy/custom-presets

**Comment by danielroe** [comment]
This hook is only run in dev mode: https://nuxt.com/docs/api/advanced/hooks
