### ISSUE TITLE
I'm getting [Vue warn]: setup() return property "$hello" should not start with "$" or "_" which are reserved prefixes for Vue internals when using .client component

### ISSUE THREAD

**Issue by KamilBeda** [nuxt/nuxt#22435]
### Environment

- Operating System: Linux
- Node Version:     v18.16.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.10
- Builder:          vite
- User Config:      devtools, imports, modules, css, svgo, i18n, headlessui, image, components, extends, runtimeConfig, linkChecker, googleFonts, build, vite
- Runtime Modules:  @nuxtjs/eslint-module@4.1.0, @pinia/nuxt@0.4.11, @nuxtjs/i18n@8.0.0-beta.13, nuxt-svgo@3.4.0, nuxt-headlessui@1.1.4, @nuxt/image@1.0.0-rc.1, nuxt-typed-router@3.2.5, @formkit/nuxt@0.17.5, @nuxtjs/tailwindcss@6.8.0, nuxt-icon@0.4.2, @nuxtjs/google-fonts@3.0.2, @vueuse/nuxt@10.3.0
- Build Modules:    -

### Reproduction

[Stackblitz reproduction link](https://stackblitz.com/edit/github-6gkd6t?file=app.vue)

1. Add plugin exactly the same as in [docs about providing helpers](https://nuxt.com/docs/guide/directory-structure/plugins#automatically-providing-helpers)
2. Use `const { $hello } = useNuxtApp()` in .client component
3. Look at the warn in the browser console - `[Vue warn]: setup() return property "$hello" should not start with "$" or "_" which are reserved prefixes for Vue internals. `

### Describe the bug

I'm getting [Vue warn]: setup() return property "$hello" should not start with "$" or "_" which are reserved prefixes for Vue internals when using .client component.
When using "normal" component (without .client extension) there is no warn and everything works as expected

**Comment by danielroe** [comment]
Yes, Vue does not allow properties returned from setup to start with `$`. So probably you are getting `$hello` within your setup function and _also_ using it in the template. (You can directly use it in the template without destructuring it from NuxtApp.)

Instead, try `const { $hello: hello } = useNuxtApp()` within your setup function, if you need to use it there in addition to within the template.

**Comment by KamilBeda** [comment]
Hello Daniel, thank you for your response. Just to clarify, I am not using $hello in my template; it is only present in the setup function. For reference, please take a look at the [reproduction link](https://stackblitz.com/edit/github-6gkd6t?file=app.vue).

My intention here is to highlight the inconsistent behavior between .client and "normal" components. I'm still unsure why this issue was closed, as it appears to be some kind of bug (albeit low priority). Your further insights would be greatly appreciated.

**Comment by danielroe** [comment]
Ah, my apologies - I didn't look into your reproduction. That does sound like an issue.

**Comment by KamilBeda** [comment]
No problem at all 😉 please reopen the issue so it won't be forgotten

**Comment by danielroe** [comment]
cc: @huang-julien

**Comment by huang-julien** [comment]
It's possibly due to my last PR on `createClientOnly` i'll take a look tonight

**Comment by huang-julien** [comment]
strange I couldn't reproduce the issue on a Vue project. But there's definitively a strange behavior when compiling. Here's the result of a simple `$config` combine with a `console.log`
`$config` isn't used in template

````ts
const _sfc_main = /* @__PURE__ */ _defineComponent({
  __name: "SetupScript.client",
  props: {
    foo: { type: String, required: true }
  },
  setup(__props, { expose: __expose }) {
    const props = __props;
    const count = ref(0);
    const add = () => count.value++;
    const { $config } = useNuxtApp();
    console.log($config);
    __expose({ add });
    const __returned__ = { props, count, add, $config };
    Object.defineProperty(__returned__, "__isScriptSetup", { enumerable: false, value: true });
    return __returned__;
  }
});
````

This issue was probably here since a few versions

**Comment by KamilBeda** [comment]
What do you mean by "reproduce it on vue project"? The project without nuxt?
Here is the [reproduction link](https://stackblitz.com/edit/github-6gkd6t?file=app.vue) but it uses nuxt and as far as I know it's nuxt specific because there is no concept of client-only components in pure vue without ssr.

**Comment by huang-julien** [comment]
Yes. The issue is that during build step, the `vite-plugin-vue` is the one responsible of transforming the SFC into JS. On the screenshot above (the edited comment), we sse that at build time, `vite-plugin-vue` set `$config` into the `__returned__`object.

Doing the same thing on a non client component does not trigger the issue (on pages/index.vue)

**Comment by huang-julien** [comment]
Yes. The issue is that during build step, the `vite-plugin-vue` is the one responsible of transforming the SFC into JS. On the screenshot above (the edited comment), we sse that at build time, `vite-plugin-vue` set `$config` into the `__returned__`object.

Doing the same thing on a non client-only component does not trigger the issue (on pages/index.vue). We need to find out what makes the SFC transform plugin set `$...` into the returned object.
![image](https://github.com/nuxt/nuxt/assets/63512348/b8c50e7b-c672-4224-9141-d164561df58a)

I don't think this should trigger any issues in production as render functions are inlined within `setup()` with SFC. However, it can trigger some tests issues if you're doing some dev environment testing with warning and error checks.
