### ISSUE TITLE
wrong route paths generated with files with special characters

### ISSUE THREAD

**Issue by tendecade** [nuxt/nuxt#22660]
### Describe the feature

Scenes:
   My client needs to translate route names into Polish for use, so my directory looks something like this:
     
      |- pages
        |- odkryć
          |- kącikInfluencerów
            |- index.vue
          |- szybkiStart
            |- index.vue
     
   However, in the generated routing file, the 'ą', 'ń', and 'ł' symbols were translated, which caused me to fail to jump (reach the error page) when performing routing jumps.

   as follows:

   <img width="1523" alt="image" src="https://github.com/nuxt/nuxt/assets/73530157/83f3d96b-c8a3-4870-bbec-140b50bc73fe">

   I don't know how to perfectly solve this problem!

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by yuvalkarif** [comment]
I would love to help on this issue so after a bit of digging I found where we are encoding the path segments. 
It looks like the problem is that we need to support [IRI](https://en.wikipedia.org/wiki/Internationalized_Resource_Identifier) even though `unjs/ufo` does not support IRI conversions. should we open an issue on ufo?

@danielroe 

https://github.com/nuxt/nuxt/blob/fc7bbe92230526b9c8c117d7add1d60b3e1ae0f3/packages/nuxt/src/pages/utils.ts#L143-L156

**Comment by danielroe** [comment]
Yes, that sounds good 👍

**Comment by pi0** [comment]
@danielroe As long as vue-router allows, we can keep URLs not encoded internally, however we should consider a default decoding to make sure encoded URLs are handled and matched correctly. (HTTP requests are ASCII)

**Comment by Typ0genius** [comment]
Is there any news here?  I am unable to pre-render my pages because of that issue, so I can't deploy my page.
