### ISSUE TITLE
error `statusCode` is provided even if no status code is returned from fetch

### ISSUE THREAD

**Issue by wwwtony5488** [nuxt/nuxt#22724]
### Environment

Nuxi 3.5.0                                                                                                                 

------------------------------
- Operating System: Darwin
- Node Version:     v16.16.0
- Nuxt Version:     3.5.0
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.6.1
- Builder:          vite
- User Config:      modules, experimental, css, colorMode, nitro, app, pwa, devtools, gtag, gtm, runtimeConfig
- Runtime Modules:  @vueuse/nuxt@10.1.2, @unocss/nuxt@0.51.13, @pinia/nuxt@0.4.11, @nuxtjs/color-mode@3.2.0, @vite-pwa/nuxt@0.0.9, nuxt-gtag@0.5.7, @zadigetvoltaire/nuxt-gtm@0.0.13
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                            

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

https://stackblitz.com/edit/github-exbnmd?file=app.vue
Apologize for that I can't just expose our product api url to show you about the real case, hope the reproduction is enough to  help.

### Describe the bug

`const { error } = await useFetch(api)`
Normally `useFetch` and `error` worked perfectly.
But if the  request respond without any message, something went wrong.
In my case, we setup a proxy for blocking DDoS. 
So if you fetch too many times In a period of time, proxy response http code 429 (means 'too many requests') without error message, then do `console.log(error.value)` it output just like
```
{
  fatal: false,
  statusCode: 500,
  statusMessage: undefined,
  unhandled: false, 
}
```
As you can see  `statusCode` got overwrited by `500`, Besides including CORS and Timeout disconnect  those error without message body show the same result.

**Comment by wwwtony5488** [comment]
@danielroe Hello, the reproduction has been provided.

**Comment by danielroe** [comment]
As far as I can see, in this case the error is not actually a response error because the request never goes through. So the fact that there's an error code is confusing (thoughts @pi0?). But it's not 'overwriting' an existing error code - there is none because there is no domain.

cc: @pi0

**Comment by pi0** [comment]
Indeed second is a request error. Request errors are thrown by ofetch, have `statusCode: undefined`:

<img width="479" alt="image" src="https://github.com/nuxt/nuxt/assets/5158436/59cb3ec7-6f18-4acc-9bb1-dca6a8d42754">

But since we wrap it with `h3.createError`, it adds a [default `500` status](https://github.com/unjs/h3/blob/164f68e9cb89e011cd304dbe07b328611e3428a3/src/error.ts#L23) . So yes not overwriting it and IMO is valid behavior considering h3 utils are targeting servers first and a request error on the server-side is 500 by default.

But it might be also confusing for client-side request errors with `useFetch` as we auto wrap.  (we might think to somehow nullify default for nuxt universal wrapper as a fix)

BTW You can always access to the original (fetch/ofetch) error using `error.cause` (`error.value.cause`) which is like screenshot above and has only `statusCode` if is from response.

**Comment by wwwtony5488** [comment]
Thanks for answering!
Let me provide another screenshot

<img width="748" alt="截圖 2023-08-24 下午2 32 29" src="https://github.com/nuxt/nuxt/assets/14257585/14293669-1b60-413e-bec4-d6a5576c7d6b">

You may find that status code should be 429 on above case, but still output 500.
That's why I defined the condition as a 'overwrite'.

Of course, we could definitely use the native fetch or ofetch for debugging. However, considering we already engaged in 
 Nuxt, our expectation is to continue using useFetch.
 Sincerely hope that problem could be resolve . Thank you again!

**Comment by danielroe** [comment]
Any chance you could provide a reproduction of the error statusCode being _overwritten_? I can clearly see it defaults to `500`, which I think is reasonable in the absence of an explicit error code and might be tricky to eradicate.
