### ISSUE TITLE
Issue with Building Icons in Nuxt Layer

### ISSUE THREAD

**Issue by sync42johnny** [nuxt/nuxt#22742]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.15.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      css
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/sync42johnny/nuxt-3-layer-test

### Describe the bug

I have been trying to build my icon pack using Fantasticon within my Nuxt 3 layer, but I have been unsuccessful. The simple Nuxt 3 app runs perfectly fine.

### Logs

```shell-script
yarn run v1.22.19
warning package.json: No license field
$ fantasticon
Failed parsing configuration at '.fantasticonrc.js'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by danielroe** [comment]
This is not a Nuxt issue. The issue is that `fantasticon` doesn't seem to support `type: module` or indeed native ESM (https://github.com/tancredi/fantasticon#configuration-file).

you could remove `type: module` from the package.json or convert the config file to JSON or one of the other formats it supports.

I would raise an issue on their repo.
