### ISSUE TITLE
Fresh install error "Cannot find any path matching /."

### ISSUE THREAD

**Issue by MattFaz** [nuxt/nuxt#22896]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.7.0`
- CLI Version:      `3.7.2`
- Nitro Version:    `2.6.2`
- Package Manager:  `npm@9.6.4`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1. Create new Nuxt3 project by typing `npx nuxi@latest init xxxx`
2. Change directory to new project by typing `cd xxx`
3. Run development by typing `npm run dev`

### Describe the bug

Browse to localhost:3000 and I see:

```json
statusCode: 404
statusMessage: "Cannot find any path matching /."
stack:  []

```

**Comment by MattFaz** [comment]
Tried updating Node version and using Yarn as the package manager but still seeing the same behavior.

------------------------------
- Operating System: Darwin
- Node Version:     v18.17.1
- Nuxt Version:     3.7.0
- CLI Version:      3.7.2
- Nitro Version:    2.6.2
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

**Comment by MattFaz** [comment]
I upgraded an existing project to Nuxt 3.7 and faced the same issues.
Downgraded Nuxt Version to `3.6.5` and it is working successfully. Looks like an issue with Nuxt 3.7.

**Comment by MattFaz** [comment]
You can find a reproduction here: https://github.com/MattFaz/nuxt3-error-example
I screen recorded me creating this project as well so you can see the error:

https://github.com/nuxt/nuxt/assets/10377148/c2c5d9a8-4a0c-411a-9602-c1cfd22bc162

**Comment by MattFaz** [comment]
Just created another project, only change is the CLI version has increased but it's working successfully now 🤷 

------------------------------
- Operating System: Darwin
- Node Version:     v18.17.1
- Nuxt Version:     3.7.0
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

**Comment by 1bye** [comment]
> ### Environment
> * Operating System: `Darwin`
> * Node Version:     `v16.17.0`
> * Nuxt Version:     `3.7.0`
> * CLI Version:      `3.7.2`
> * Nitro Version:    `2.6.2`
> * Package Manager:  `npm@9.6.4`
> * Builder:          `-`
> * User Config:      `devtools`
> * Runtime Modules:  `-`
> * Build Modules:    `-`
> 
> ### Reproduction
> 1. Create new Nuxt3 project by typing `npx nuxi@latest init xxxx`
> 2. Change directory to new project by typing `cd xxx`
> 3. Run development by typing `npm run dev`
> 
> ### Describe the bug
> Browse to localhost:3000 and I see:
> 
> ```json
> statusCode: 404
> statusMessage: "Cannot find any path matching /."
> stack:  []
> ```
> 
> ### Additional context
> _No response_
> 
> ### Logs
> _No response_

Same error with nuxt 3.6.5 and nuxt 3.7 but I noticed this error also occurs when installing some plugins. Maybe the problem is in nitro.

**Comment by deleteme** [comment]
I encountered this error today with Nuxt 3.7. Downgrading to Nuxt 3.6.5 and adding this yarn resolution `"nuxt/nitropack": "~2.5.2",` is a temporary workaround.

**Comment by 1bye** [comment]
> I encountered this error today with Nuxt 3.7. Downgrading to Nuxt 3.6.5 and adding this yarn resolution `"nuxt/nitropack": "~2.5.2",` is a temporary workaround.

+ Also did this, but if you need some new features of nitro, you can use also nitropack 2.6.2 with nuxt 3.6.5

**Comment by deleteme** [comment]
Following up:

I realized that the the bigger impact of the nitropack resolution I mentioned above, was that it forced multiple versions of nitropack to be consolidated to only one.

So I removed the `"nuxt/nitropack": "~2.5.2"` yarn resolution in the Nuxt 3.6.5 app, ran `yarn dedupe`, and the original 404 error didn't appear.

Then I bumped up Nuxt 3.7, ran `yarn dedupe`, verified that there weren't multiple versions of nitropack, and the original 404 error also didn't appear.

**Comment by 1714080902120** [comment]
I meet the same problem when i sliced a file into chunks and upload with `Promise.all`. I think the problem was caused by multiple post requests in the same time. When i use `await` instead of `Promise.all`, it works well. But i  can not use `await` because of the efficiency.
By the way, the problem does not happen in `production` when use `npm run build && npm run preview`.

**Comment by MattFaz** [comment]
Still facing this issue with the below.

```
- Operating System: `Darwin`
- Node Version:     `v18.17.1`
- Nuxt Version:     `3.7.4`
- CLI Version:      `3.9.0`
- Nitro Version:    `2.6.3`
- Package Manager:  `npm@10.2.0`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

**Comment by MattFaz** [comment]
Completely fresh install, can see Nuxt and Nitro are both newer versions but still wont run.

```
------------------------------
- Operating System: Darwin
- Node Version:     v18.17.1
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

**Comment by soub4i** [comment]
Same here 
MacOS, fresh install

**Comment by danielroe** [comment]
Hm. I can't see any issue in the reproduction: https://stackblitz.com/github/MattFaz/nuxt3-error-example - or when I clone it. 🤔

**Comment by soub4i** [comment]
a clean 

> Same here MacOS, fresh install

cleaning npm cache .. worked for me

**Comment by MattFaz** [comment]
> cleaning npm cache .. worked for me

Wow... can't believe I didn't try that first. Confirming this solved the issue for me as well.
`npm cache clean --force`

**Comment by leithonenglish** [comment]
That doesn't work for me either. Each time I put my MacBook to sleep with the server running it produces the same error when I try to access a page or API endpoint.
```js
{
  "statusCode": 404,
  "statusMessage": "Cannot find any path matching /.",
  "stack": []
}
```
I have to restart my computer each time.

**Comment by 93lucasp** [comment]
> That doesn't work for me either. Each time I put my MacBook to sleep with the server running it produces the same error when I try to access a page or API endpoint.
> 
> ```js
> {
>   "statusCode": 404,
>   "statusMessage": "Cannot find any path matching /.",
>   "stack": []
> }
> ```
> 
> I have to restart my computer each time.

same here

**Comment by oscartbeaumont** [comment]
I'm getting this same error message when using [Solid Start](https://github.com/solidjs/solid-start) ([Vinxi](https://github.com/nksaraf/vinxi) under the hood) and I managed to work it was due to the presence of [`vite-plugin-html`](https://github.com/vbenjs/vite-plugin-html).

For me it seems to be coming from `connect-history-api-fallback` (dependency of `vite-plugin-html`) due to some issues parsing an invalid URL ([here](https://github.com/bripkens/connect-history-api-fallback/blob/74564d61c2db06e302923a23bd459bb5dd91712b/lib/index.js#L45)) and the issues only seems to occur for the `/` route (Eg. `/example` works).

[`parsedUrl`](https://github.com/bripkens/connect-history-api-fallback/blob/74564d61c2db06e302923a23bd459bb5dd91712b/lib/index.js#L45) is becoming ```Url {
  protocol: null,
  slashes: null,
  auth: null,
  host: null,
  port: null,
  hostname: null,
  hash: null,
  search: null,
  query: null,
  pathname: null,
  path: null,
  href: ''
}``` for some reason not sure why.

I know both Nuxt and Solid Start use Nitro + Vite so it's possible these issues are linked but I have not verified this myself so take it with a grain of salt.

**Comment by phillipmohr** [comment]
I was able to fix this by running `npx nuxi cleanup`

**Comment by celestialmk** [comment]
404 [GET] "/_nuxt/builds/meta/test.json": 404 Cannot find any path matching /_nuxt/builds/meta/test.json.
I cant seem to fix this. Only occurs on npm run dev but app works fine on npm run build. I have tried all the above suggestions. Any help will be highly appreciated.

**Comment by outlabsio** [comment]
I recently encountered this issue. Seems to have been caused by the following middleware route rules: 

  // routeRules: {
  //   "/**": {
  //     // or appMiddleware: 'auth'
  //     appMiddleware: ["auth"],
  //   },
  //   "/admin/login": {
  //     // You can 'turn off' middleware that would otherwise run for a page
  //     appMiddleware: {
  //       auth: false,
  //     },
  //   },
  // },

**Comment by ifiri** [comment]
Ran into the same issue. 

For me, helped to add values into my `.env`.

I use `runtimeConfig` and Terraform to put environment variables from SSM at runtime. The `.env` is empty by default (but variables listed only to know which variables used). These variables are not set locally, because Terraform works in the cloud, and when I fill it by local values, it _occasionally_ started to work. 

There are api keys, api urls, cdn urls. All this stuff used just to perform requests on server and frontend sides; but expected that if request cannot be performed, I just get empty data (I have fallbacks for that in my service layer). Moreover, these requests not required to start main page of application (it's static). Looks some of these requests called on Nitro preparation step and it causes this problem.

Mythic issue, kill whole day on that.

**Comment by A-Sumkin** [comment]
> {
>   "statusCode": 404,
>   "statusMessage": "Cannot find any path matching /.",
>   "stack": []
> }
> 

Have the same issue - fresh install, one simple route in server/api folder

Nuxt 3.11.2 with Nitro 2.9.6

Node version LTS

**Comment by LMarcinkowski** [comment]
Same here on MacBook PRO M3.

Nuxt 3.8.0
Node v20.12.0

**Comment by kohi25684** [comment]
I encountered the same error. The cause was that I unintentionally created a composable named `useState` under the `composables` directory. This seems to have conflicted with Nuxt's `useState`, causing strange behavior. The issue was resolved by changing the name.

**Comment by wiseadme** [comment]
faced with a similar problem. Sometimes after reloading the page nuxt takes a long time to load, which eventually leads to the same error "Cannot find any path matching /my-page/url"
