### ISSUE TITLE
Hydration error, rogue <span> being rendered

### ISSUE THREAD

**Issue by cmcnicholas** [nuxt/nuxt#22965]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.12.1
- Nuxt Version:     3.7.0
- CLI Version:      3.7.0
- Nitro Version:    2.6.1
- Package Manager:  npm@9.1.2
- Builder:          -
- User Config:      alias, devtools, modules, content, runtimeConfig, imports, typescript
- Runtime Modules:  @nuxt/content
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-v9wco7?file=app.vue

### Describe the bug

I get a consistent Hydration error for a very simple template (repro link above). The error is:

![image](https://github.com/nuxt/nuxt/assets/41394833/3b569f9b-6573-4a38-aea4-a0f62f5686d1)

And in the repro can be seen to warn about the same `span` element.

In my local build inspecting I can also the see the element present in the dom on the client:

![image](https://github.com/nuxt/nuxt/assets/41394833/df030db3-076d-4355-8c3a-3585e28f495d)

But the `span` is not part of my template.

I am unsure as to why this extra element is being injected, I have no additional plugins beyond core nuxt and the repro also shows this with a minimal project setup.

### Logs

```shell-script
[Vue warn]: Hydration node mismatch:
- Client vnode: table 
- Server rendered DOM: <span>​</span>​  
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouteProvider key="/authorities" vnode= Object route= Object  ... > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <Default ref=Ref< undefined > > 
  at <LayoutLoader key="default" layoutProps= Object name="default" > 
  at <NuxtLayoutProvider layoutProps= Object key="default" name="default"  ... > 
  at <NuxtLayout> 
  at <App key=3 > 
  at <NuxtRoot>
```
```

**Comment by madebyfabian** [comment]
Hi there! This is caused by the `<ClientOnly><tfoot>` element. Not an expert on this field, but I suspect that because of Nuxt trying to drop in a placeholder in this place, and <span> inside a <table> is invalid, the mismatch happens. You could move the `<ClientOnly>` to somewhere else:

```html
<tfoot>
          <tr v-show="more">
            <td colspan="3">
              <ClientOnly>
                <a href="#" @click.prevent.stop="onMoreClick">Load more</a>
              </ClientOnly>
            </td>
          </tr>
        </tfoot>
```

(see https://stackblitz.com/edit/github-v9wco7-jhapot?file=app.vue) or try something else with v-if/v-show.

**Comment by cmcnicholas** [comment]
> Hi there! This is caused by the `<ClientOnly><tfoot>` element. Not an expert on this field, but I suspect that because of Nuxt trying to drop in a placeholder in this place, and since `<span>` inside a ` <table>` is invalid, the mismatch happens. You could move the `<ClientOnly>` to somewhere else:
> 
> ```
> <tfoot>
>   <tr v-show="more">
>     <td colspan="3">
>       <ClientOnly>
>         <a href="#" @click.prevent.stop="onMoreClick">Load more</a>
>       </ClientOnly>
>     </td>
>   </tr>
> </tfoot>
> ```
> 
> (see https://stackblitz.com/edit/github-v9wco7-jhapot?file=app.vue) or try something else with v-if/v-show.

nailed it, I never knew it could be this opinionated, is there anywhere that lists these sort of issues or has the most common to watch out for? Haven't come across it in the documentation or is it a case of trial and error?

**Comment by madebyfabian** [comment]
@cmcnicholas good question. What works for me is: in General, if you go against semantic html rules (e.g. nesting <p> inside a <span> or a <div> inside a <table>) you will get ssr mismatches. In this particular example it was hard to catch, because it was no obvious error in your code. What also often works to debug SSR errors is to gradually remove parts of the HTML/Components until the error disappears. Which brings you to the cause. (Often it's some date that is getting rendered differently on server & client because of timezones.

But maybe a nuxt core maintainer has more insights on this :)

**Comment by manniL** [comment]
You can also define a placeholder (component or simply tag) via the template of `<ClientOnly>` to avoid such mismatches 👍 

See https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/app/components/client-only.ts#L17C71-L17C71

`<ClientOnly placeholder-tag="tfoot">...</ClientOnly>`

**Comment by madebyfabian** [comment]
@manniL thanks for pointing out! Did not know that. So you could set a tfoot as placeholder and it should work.
