### ISSUE TITLE
Incorrect types of auto-imports in modules

### ISSUE THREAD

**Issue by PatSosna** [nuxt/nuxt#22988]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.5.1
- Nuxt Version:     3.7.0
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  pnpm@8.7.1
- Builder:          -
- User Config:      modules, auth, security, typescript, devtools, i18n, postcss, tailwindcss, vue, vite
- Runtime Modules:  nuxt-security@0.14.4, @sidebase/nuxt-auth@0.5.0, @nuxtjs/tailwindcss@6.8.0, nuxt-svgo@3.5.0, @vueuse/nuxt@10.4.1, @nuxtjs/i18n@8.0.0-rc.4
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-xodh6t?file=modules%2Fexample%2Fpages%2Fsomething%2Findex.vue

### Describe the bug

There are missing types from auto-imports, and that the ref, $fetch, or other variables are being inferred as `any` in modules.

**Comment by danielroe** [comment]
This is caused by the fact that we are excluding modules from being covered from the generated tsconfig.

I still think that's a good idea, but it might be worth _either_ adding any added pages/composables/etc. base directories, or possibly automatically including a `./runtime` path within modules (though I realise that's opinionated).

thoughts @pi0 @lihbr @Atinux?

**Comment by Atinux** [comment]
I second @lihbr , I like the `./runtime` convention. And well, Nuxt is convention over configuration :)

**Comment by danielroe** [comment]
Okay, let's do it. We can add `./runtime` path of local module directories to `tsconfig.json`, while adding `./runtime/server` to exclude - and instead add to to the include of `tsconfig.server.json`.
