### ISSUE TITLE
RuntimeConfig does not display proper environment variable hint when already using UPPER_SNAKE_CASE

### ISSUE THREAD

**Issue by Aareksio** [nuxt/nuxt#23246]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.3
- CLI Version:      3.8.4
- Nitro Version:    2.6.3
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, runtimeConfig
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-uezcgs?file=nuxt.config.ts

### Describe the bug

Hint reads:
```
You can override this value at runtime with NUXT_PUBLIC_A_PP_NAME_S
```

Should be:
```
You can override this value at runtime with NUXT_PUBLIC_APP_NAMES
```

### Additional context

```ts
export default defineNuxtConfig({
  runtimeConfig: {
    public: {
      APP_NAMES: 'xyz'
    }
  }
})
```

Environment variable `NUXT_PUBLIC_APP_NAMES` is properly respected. The issue concerns the documentation exclusively.

**Comment by luc122c** [comment]
It seems to be an issue with the `UpperSnakeCase` type. I think i've figured out where the problem comes from. I'll open a PR to fix and add some more tests.

[Playground link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAogHsATgQwMbAKpkogwgCwFcA7AawB4AVKCBCYgEwGcomkBLYgcwD4oBeKNVrB6zKAAMAJAG9OAMwiIoAQQC+shUqgAhNRIBQUKAH5VNOoxZYcqZEwjkVPI8dO6Loq5Nk2ldh3I2RE5eDTliRWUAJQg2fVc3dx1PMRZpCKioXHDY+MMkpLMM9Vkc2XgkNExsJQISCjzgHgTCtwAuKGIIADclRI7VAc6AchHXTu6+xAMDUEgoAGUAG3ZUCAAZe2AqVO9g0L5BYUtxDK1lUsztPQLkvbPNSO1y6+UAEVa3M3eHljGBsYzCpAVBOiVwq8VmtNttyO8WndjKNxsiur1+nNwNA-IhFsRkKQILh7I4Tl5xAduAAaJbAZCiP5QEZsZCIYAjKAAH2ZywA9gB3JScnkjQi1RCcwQs+nskZHIRM87PS7hC66L7Apm4gKOZwDLUiNI+GQARm5UAATBaAMwWgAsFoArBaAGwWgDsFoAHBaAJwWgAMXyKJquuPxhOJpPIOlpI35QsliNBnUW9MZRu8CcFwotYolqLa9yzjxk0PWWzY5EqKHQuPqZFjPBaTyyTRDxbMFdh1dr1QbRCbOhbTIBxcKxVk4YlkaJJMCceZrLlKYnSXB0-CParO379YljYoI9bMgjBPnMaa8ZXHLX686KVL1gluuboLaxQA+lvZLcP4U4I-jIM44HO0aLvGibCvebRphm0DPsusocgBQJhuE55RgujhLjmSbyp2cHotMqZ0gyiGnP8t4iryuaSgBU5nq+MbOJhs4XhBuFQfRhFIoBkjATqrGnlhl6QXRBH3p0wmBJQLhYgsADy0QAJIAOKqQAcioGwCFAYlceQIwqAACqZX46QAsjAizygYAD0DlJAAeiYinQJQtnUIIhk4cZZmmfZTmue58yed51q+Rx2ExiMyDYMFzluG5HlCN5drRWBnH+SMXB8nyDDqSgPQgEloVpV5iyUI6WVKOBuVICAlD4OwTBKd0WkiOVKUmEAA)

**Comment by pi0** [comment]
Nice find @luc122c ❤️

**Comment by luc122c** [comment]
I'm not quite sure how to run [these tests](https://github.com/nuxt/nuxt/blob/1487c5631aa1f66fab21465fbfca11b4fa62b2f0/test/fixtures/basic-types/types.ts#L241). None of the test scripts in `package.json` seem to run them and I only see `./fixtures/basic` being setup, not `./fixtures/basic-test`?
