### ISSUE TITLE
Fresh nuxt install not work with Bun. Api work, front end no rendered 

### ISSUE THREAD

**Issue by imcm7** [nuxt/nuxt#23289]
### Environment

ubuntu
node 20
frsh nuxt installation with bun

### Reproduction

latest nuxt installation 
https://github.com/imcm7/nuxt-bun

### Describe the bug

Fresh nuxt install not work with Bun. Api work, front end no rendered.

**Comment by imcm7** [comment]
> Would you be able to provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-[reproduction)? 🙏

https://github.com/imcm7/nuxt-bun

**Comment by danielroe** [comment]
It's true, the response hangs. Not sure if this is a Bun issue or a Nuxt one; we'll need to check.

cc: @pi0

**Comment by pi0** [comment]
Likely same as https://github.com/nuxt/cli/issues/190 and an internal bug with Bun causing hanging requests. It is not easy to debug because chrome also provides not much information but let's track from one place (and feel free to open another issue in nuxt/cli if you feel this is a different issue)
