### ISSUE TITLE
Page components that should be loaded dynamically are loaded immediately

### ISSUE THREAD

**Issue by kilab** [nuxt/nuxt#23401]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.7.3
- CLI Version:      3.8.4
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.6.1
- Builder:          -
- User Config:      runtimeConfig, modules, piniaPersistedstate, viewport, css, vite, vue, app, build, nitro, swiper, typescript, devtools
- Runtime Modules:  @artmizu/nuxt-prometheus@2.2.0, @nuxt/content@2.8.2, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.2, @vee-validate/nuxt@4.11.6, @vueuse/nuxt@10.4.1, nuxt-viewport@2.0.6, nuxt-swiper@1.2.2, nuxt-vitest@0.10.2
- Build Modules:    -

### Reproduction

- Go to: https://stackblitz.com/edit/nuxt-dynamic-route-components?file=pages%2FPageOne.vue,pages%2FPageThree.vue,app%2Frouter.options.ts
- Open dev tools in web browser

### Describe the bug

I use dynamic imports in my router configuration to reduce the amount of data downloaded when entering a website. Unfortunately, Nuxt downloads other page components anyway.

```ts
export default <RouterConfig>{
  routes: () => [
    {
      name: 'page-one',
      path: '/',
      component: () => import('../pages/PageOne.vue'),
    },
    {
      name: 'page-two',
      path: '/two',
      component: () => import('../pages/PageTwo.vue'),
    },
    {
      name: 'page-three',
      path: '/three',
      component: () => import('../pages/PageThree.vue'),
    },
  ],
};
```

![image](https://github.com/nuxt/nuxt/assets/1648028/75aa8c07-e2f7-4ea7-9d38-bb1d0b5636da)

**Comment by warflash** [comment]
NuxtLink will automatically prefetch routes it's linking to so that's expected behaviour. [More info can be found in the docs as well](https://nuxt.com/docs/api/components/nuxt-link#props:~:text=prefetch%20and%20noPrefetch%3A%20Whether%20to%20enable%20prefetching%20assets%20for%20links%20that%20enter%20the%20view%20port.)
Here is your example with the prop applied, no longer prefetching: https://stackblitz.com/edit/nuxt-dynamic-route-components-fj8avp?file=pages%2FPageOne.vue,pages%2FPageThree.vue,app%2Frouter.options.ts
