### ISSUE TITLE
NODE_ENV explicitly specified

### ISSUE THREAD

**Issue by or2e** [nuxt/nuxt#23402]
### Describe the feature

I have experienced that when running a build project using `node ./.output/server/index.mjs` vue.js was running in dev mode, because if you don't define `NODE_ENV=production node ./.output/server/index.mjs`, then you will get a dev build of vue.js (by default) https://github.com/vuejs/core/blob/main/packages/runtime-core/index.js

Do you think it is necessary to add this note to the doc? (https://nuxt.com/docs/getting-started/deployment#nodejs-server)

### Additional information

- [x] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
cc: @pi0 It seems we have a regression with [tracing export conditions](https://github.com/unjs/nitro/issues/844) as the Vue dev build is also getting picked.

reproduction from linked issue: https://stackblitz.com/edit/nuxt-examples-tnmdbb?file=package.json.

**Comment by pi0** [comment]
Checking reproduction, it seems that `@vue/runtime-core` is not using any export conditions (was it before?) that nitro externals tracer could rewrite for. Since `@vue/runtime-core/index.js` uses two `require` for two builds, nitro also (correctly) traces two builds so I don't think it is a bug but something definitely worth to fix.

On vue side, we had been tracing it for a long time for supporting `exports` field in their `package.json` @danielroe do you remember why latestly it wasn't introduced? 

For a solution in Nitro we can:
- Add `NODE_ENV` by default in **runtime entry** for externals using it
- Add a new feature to allow manually rewriting written externals files in a hook and then use it for nuxt>vue deps

**Comment by danielroe** [comment]
This is now resolved (for vue) in the latest release of `@vue/runtime-core`! 🎉 

See bundle size diff in https://github.com/nuxt/nuxt/pull/25036/files#diff-04a7585c5d6ddd5cf80321c69bc6e07cd85e9e86ae35fa5f9c036651f137c312.
