### ISSUE TITLE
useRouter not map children

### ISSUE THREAD

**Issue by shadowaun** [nuxt/nuxt#23595]
### Environment

node : 18 
nuxt : v3.7.4

### Reproduction

main

### Describe the bug

create path

- pages/parent/chid.vue
- pages/parent.vue

console.log(useRouter().getRoutes())

item.children = []

**Comment by tommie** [comment]
Here's a repro: https://stackblitz.com/edit/github-kqrjpb?file=app.vue

**Comment by tommie** [comment]
I tried adding `experimental.typedPages: true` to the repro, but that doesn't seem to change anything. I also tried downgrading to 3.5.0 without change.

I was wondering why it works on the nuxt.com website, but it seems it uses Nuxt Content, which I think has its own files -> router mapping.

**Comment by tommie** [comment]
Actually... This is a deliberate change in Vue Router 4: https://github.com/vuejs/rfcs/blob/master/active-rfcs/0028-router-active-link.md#unrelated-but-similiar-routes

Summary is that "active" now refers to the nestedness (children), not the URL prefix. Since Nuxt doesn't use nesting for pages, we should only ever expect the exact-active class. Sadly the V4 documentation about these CSS classes are also pretty lacking. I found the RFC through [the V4 migration guide](https://router.vuejs.org/guide/migration/#Removal-of-the-exact-prop-in-router-link-)

The RFC has a suggested workaround. I think it would be nice if NuxtLink could handle this, but it also doesn't feel like a core thing for Nuxt to care about.

**Comment by tommie** [comment]
I should mention I tried rearranging routes in a hierarchy using `app/router.options.ts`, and that makes the active class work: https://gist.github.com/tommie/5645a135e788705f00fbc56314d77ada
