### ISSUE TITLE
NuxtErrorBoundary not rendering the error on ssr:false

### ISSUE THREAD

**Issue by DarioRega** [nuxt/nuxt#23917]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      ssr
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

Here is the reproduction example on [stackblitz](https://stackblitz.com/edit/github-wg3yu6-xyvmf5?file=pages%2Findex.vue)

### Describe the bug

When wrapping components in the **NuxtErrorBoundary** and one of the children throws an error (with createError but not fatal, or with a simple throw new Error() ) the error message is logged within the console but the error template does not take over the default slot.

This mostly when **ssr:false** is set in the config

<img width="367" alt="image" src="https://github.com/nuxt/nuxt/assets/48969740/ef169319-90ca-40c5-a899-0d41b78168ac">

**Comment by connerblanton** [comment]
This could be an upstream issue with Vue because the [onErrorCaptured](https://stackblitz.com/edit/github-wg3yu6-uvq9ad?file=components%2FChildComponent.vue) lifecycle hook isn't being triggered in the [NuxtErrorBoundary](https://github.com/nuxt/nuxt/blob/bd86e267639149d0a957deda65a43bdac70152dd/packages/nuxt/src/app/components/nuxt-error-boundary.ts#L14) component

Seems like the error being thrown inside the `settimeout` function is causing the issue. Triggering the same error from a button click like in this [stackblitz](https://stackblitz.com/edit/github-wg3yu6-uvq9ad?file=components%2FChildComponent.vue) has everything working correctly

**Comment by DarioRega** [comment]
> This could be an upstream issue with Vue because the [onErrorCaptured](https://stackblitz.com/edit/github-wg3yu6-uvq9ad?file=components%2FChildComponent.vue) lifecycle hook isn't being triggered in the [NuxtErrorBoundary](https://github.com/nuxt/nuxt/blob/bd86e267639149d0a957deda65a43bdac70152dd/packages/nuxt/src/app/components/nuxt-error-boundary.ts#L14) component
> 
> Seems like the error being thrown inside the `settimeout` function is causing the issue. Triggering the same error from a button click like in this [stackblitz](https://stackblitz.com/edit/github-wg3yu6-uvq9ad?file=components%2FChildComponent.vue) has everything working correctly

You're right, removing it works, that's strange because today i thought i experienced weird behaviors but seems i was dreaming. Im actually facing this problem on my project (without the setTimeout ofc) and i can't explain why this happens or what prevent it to populate the error slot while logging it to the console.

Any tips for debugging ? it's been hours 😆 .

Anyway, closing this issue, thanks a lot for your time

**Comment by connerblanton** [comment]
@DarioRega if you can share the repo with me or send me another stackblitz that resembles it without the settimeout, then I'd be more than happy to take a look for you. You can also message me on discord if you want, my username is the same one I have here
