### ISSUE TITLE
useRouter.hash isnt in SSR side

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#23948]
### Environment

Working directory: /home/projects/nuxt-starter-3zqnfv                                                              9:10:18
Nuxt project info:                                                                                                 9:10:18

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                        9:10:18

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

https://stackblitz.com/edit/nuxt-starter-3zqnfv

### Describe the bug

If i open this reproduction, the variable isHash is correct.

If i added "#description" the variable isHash is false, but there is a hash!!!

![image](https://github.com/nuxt/nuxt/assets/77386602/bad306dd-b47a-4759-ab91-68d562d0e412)

If i clicked the button works ok!

**Comment by okzmo** [comment]
Hey there! I have a suggestion that could help. Try adding "immediate: true" to the watch function like this:

```
watch(
  () => route.hash,
  () => {
    if (route.hash == `#description`) isHash.value = true;
  }, {immediate: true}
);
```

This adjustment will enable to execute your watcher on initial load which will check for the presence of "description" in the hash. Additionally, your button will continue to function properly when clicked. Hope this helps!

If you need more informations: https://vuejs.org/guide/essentials/watchers.html#eager-watchers

**Comment by agracia-foticos** [comment]
But route.hash in SSR mode is empty ¿really?

Why all parameters of route (useRouter()) are filled but hash is empty in SSR mode?

**Comment by okzmo** [comment]
The reason for this behavior is related to the functioning of SSR. When a page is rendered on the server side, the fragment identifiers (the part that comes after the hash symbol) are not sent to the server. These identifiers are used to identify specific sections within a page and scroll to it for example. Since this information is handled on the client side, the server doesn't need to be aware of it. As a result, when you use SSR, the initial page load will display everything including the full page, queries, etc., but the fragment identifier (hash) won't be visible.
