### ISSUE TITLE
nuxt3 404 page status code issue

### ISSUE THREAD

**Issue by YousafCityscape** [nuxt/nuxt#23977]
### Environment

I'm facing an issue in my Nuxt 3 app where the 404 page returns a status code of 200 instead of 404. My application is configured with ssr: false, and I need assistance in resolving this issue.

### Reproduction

![404 page status 200](https://github.com/nuxt/nuxt/assets/149146628/fede70e2-8b32-4bac-ae6d-1ffa371bed5c)
![404 page status 404](https://github.com/nuxt/nuxt/assets/149146628/340f1a1b-a78e-412b-8e24-2f1a20929391)

### Describe the bug

I have created a customized 404 page in nuxt3 and it's working fine then I noticed its status is 200, not 404 so I checked on the internet and found out that my app is ssr: false in nuxt.config.ts file and it's not giving me the correct status anybody knows how to resolve it

**Comment by okzmo** [comment]
Hello there! It seems like you've already identified the cause of your issue, which is related to SSR (Server-Side Rendering). When you render on the server, you have access to utilities like "setResponseStatus" that's why you get a 404 because you're setting this code yourself. However, in the absence of SSR, Nuxt will recognize that you're on a page that exists in your files, specifically "not-found.vue," and will simply send a 200 response. 

If you need more informations about error pages you might want to look here: https://nuxt.com/docs/getting-started/error-handling#error-page
