### ISSUE TITLE
Critical bug | useCookie resets previous options after been called in nuxt 3.8.0

### ISSUE THREAD

**Issue by RomanSkrypnik** [nuxt/nuxt#24041]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.5.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Nuxt 3.7.4 (works fine): [Screencast 2023-10-30 21-49-58.webm](https://github.com/nuxt/nuxt/assets/44501848/8408b217-77a0-4a89-bfee-4f7595884646)
Nuxt 3.8.0 (with issue): [Screencast 2023-10-30 21-54-21.webm](https://github.com/nuxt/nuxt/assets/44501848/ee492244-cbee-403a-983e-b3dd2801f3b9)

**Github**: https://github.com/RomanSkrypnik/nuxt-cookie-issue

### Describe the bug

**useCookie** resets previously set cookie options after been called again in nuxt 3.8.0
Nuxt 3.7.4 version works as expected

**Code**:

![image](https://github.com/nuxt/nuxt/assets/44501848/b6e6f90d-660a-4ef2-9bbe-bae4fd1f6d2c)

**Comment by danielroe** [comment]
I'm not sure the current behaviour is a bug; the options need to match between calls to `useCookie`. I think the previous behaviour (ignoring new options) would be the bug.

I'd recommend creating your own auto-imported composable, like so:

```ts
export const useTestCookie = () => useCookie('test-cookie', { /* shared options */ })
```

**Comment by RomanSkrypnik** [comment]
@danielroe I have created a composable like you said and it breaks logic with clearing cookies at all
Now, every time I call **useAuthCookie** just to get value from it - it creates cookie in the browser and gives it empty value - that's not an expected behavior
![image](https://github.com/nuxt/nuxt/assets/44501848/88d31012-bbc6-4ee3-b4b9-31684725512d)

**Comment by RomanSkrypnik** [comment]
@danielroe That's bad, is there any way to pass flag or smth?
As for me, I have an advanced authorization using **refreshToken** and **accessToken**
It would be ok if I make **maxAge** static for **refreshToken** but not acceptable for **accessToken** because its expiration is fetched from backend
Every time I call **useCookie** - it will just clear my previously set options, speaking of which **accessToken** **maxAge** value will be reset to "Session"

**Comment by danielroe** [comment]
@RomanSkrypnik Would you provide an example of the code that isn't working for you?

**Comment by RomanSkrypnik** [comment]
@danielroe for example login case:
Token composables:
![image](https://github.com/nuxt/nuxt/assets/44501848/bbb2cb21-0ad5-421b-a9b3-db92a0f9e2a6)
Login method:
![image](https://github.com/nuxt/nuxt/assets/44501848/975ae015-a640-4603-b00a-3bdc47037dde)
setRefreshToken and setAuthToken:
![image](https://github.com/nuxt/nuxt/assets/44501848/20883f4d-dcc7-4296-be8a-a472a667d994)
Cookie plugin:
![image](https://github.com/nuxt/nuxt/assets/44501848/472115bc-d3c8-48a5-a0c2-609b775a2f3b)
After this, If I call useAuthToken - it will just reset **maxAge** to "Session" value
For example, here it's called **onRequest** in **useFetch**:
![image](https://github.com/nuxt/nuxt/assets/44501848/d75d3f1b-3a10-429d-b093-007deb582581)
On this step maxAge of authToken will be reset:
![image](https://github.com/nuxt/nuxt/assets/44501848/564288d8-48bc-4d72-a116-08e664f30f1b)

**Comment by jony1993** [comment]
@danielroe

I've come across a similar issue in our project regarding the useCookie composable.

We manage various cookies with maxAge or expiresAt attributes. For example, we receive an authToken from our backend that is set to expire after 15 minutes. We set it up similarly to this:

```
useCookie('authToken', { path: '/', expires: authTokenExpiresAt })
```
Initially, my understanding was that by using `useCookie('authToken').value`, I could check both the existence and the value of the authToken. This seems to work as expected, allowing me to read the authToken.

However, I've observed a peculiar behavior. When refreshing a page (where I just want to receive the authToken via `useCookie('authToken').value`), the cookie correctly maintains its set expiry date. Yet, when navigating to a different page (e.g., using browser back button, NuxtLink, navigateTo), the expiry date gets removed, and the cookie defaults to being a session cookie.

Is this behavior intentional? If so, I think clearer documentation or guidance on handling such cases would be very helpful.

I have created a small reproduction of this issue here: https://github.com/jony1993/usecookie-bug-nuxt

Thank you for looking into this.

**Comment by abdaldeen** [comment]
@danielroe

I've come across a similar issue too.

It is illogical to be forced to set `expires` for the cookie so I can get the value of it.

we only need to get the value without any update on the cooke.

**Comment by ExEr7um** [comment]
@danielroe is there a way to simply read a cookie? Maybe `readonly` option for `useCookie`?

**Comment by franzus5** [comment]
@danielroe same issue for us, any news on this feature?

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/nuxt/pull/24503.
