### ISSUE TITLE
Server dynamic route matching

### ISSUE THREAD

**Issue by kamatil-dev** [nuxt/nuxt#24040]
### Environment

- Operating System: Linux
- Node Version:     v20.8.1
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  yarn@
- Builder:          -
- User Config:      ssr, nitro, experimental, components
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

server/
&nbsp;&nbsp;&nbsp;&nbsp;api/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[db]/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;user/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;index.ts
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;session/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;index.ts
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;demo/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;session/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;index.ts

### Describe the bug

when calling /server/api/demo/session/index.ts it supposed to use "/server/api/[db]/session/index.ts", but instead it gives me 404

**Comment by milos018** [comment]
@kamatil-dev It seems you already have a /server/api/demo route based on the file structure, so calling it with "demo" as the dynamic part would still look for the exact match, which you seem to already have. Does it work with other dynamic [db]? It would also help to have a reproduction for faster debug, if possible.

**Comment by angelhdzmultimedia** [comment]
Tried to help https://stackblitz.com/edit/nuxt-starter-trgjwj and faced the opposite scenario: Not getting a 404 WHEN I SHOULD!!! I should get 404 requesting `/api/demo/user`  because that route doesn't exist!
And I don't have a **capture all** handler on the demo route! (but when I do add a capture all ~/server/api/demo/[...slug].ts`, it captures it!).

I put the request inside try/catch, and the request to `/api/demo/user` isn't causing the catch statement to execute, not even a Nuxt Error! I returns a weird HTML text as response data... 👀 crazy stuff.

Subscribed to find out the outcome of this. Wishing success and health. 💚🔥

**Comment by milos018** [comment]
@angelhdzmultimedia

/api/demo/user will return and error because it will find the route match for /api/demo which you already defined, but the only child route is /api/demo/session and the /api/demo/user does not exist. What it does is check for "static" routes ('demo') and because it was found it will look further, but not go back and check if there is also a dynamic route. So, your /api/[db] route works for anything, except /api/demo/user. And /api/demo will work only with /api/demo/session.

Hope this helps.

**Comment by kamatil-dev** [comment]
in that case, is there a way to import handlers in dynamic route folder, into a **Capture all** file inside the static folder?

**Comment by milos018** [comment]
I am pretty sure yes, you will just have to organise the routes differently

**Comment by angelhdzmultimedia** [comment]
@milos018 

I made some deep tests, and I just realized it seems to be a bug with nitro/h3. I should get 404 on not existing routes, and instead I'm receiving this HTML data: 

```ts
<!DOCTYPE html>\n<html >\n<head><meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<link rel=\"modulepreload\" as=\"script\" crossorigin href=\"/_nuxt/C:/Users/AngelHdz/Downloads/nuxt-starter-trgjwj/node_modules/.pnpm/nuxt@3.8.0_@types+node@20.8.9_vite@4.5.0/node_modules/nuxt/dist/app/entry.js\">\n<script type=\"module\" src=\"/_nuxt/@vite/client\" crossorigin></script>\n<script type=\"module\" src=\"/_nuxt/C:/Users/AngelHdz/Downloads/nuxt-starter-trgjwj/node_modules/.pnpm/nuxt@3.8.0_@types+node@20.8.9_vite@4.5.0/node_modules/nuxt/dist/app/entry.js\" crossorigin></script></head>\n<body ><div id=\"__nuxt\"></div><script type=\"application/json\" id=\"__NUXT_DATA__\" data-ssr=\"false\">[{\"_errors\":1,\"serverRendered\":2,\"data\":3,\"state\":4},{},false,{},{}]</script>\n<script>window.__NUXT__={};window.__NUXT__.config={public:{},app:{baseURL:\"/\",buildAssetsDir:\"/_nuxt/\",cdnURL:\"\"}}</script></body>\n</html>
```

To confirm, I removed EVERYTHING under ~/server/api, and made some requests to non-existend routes, and got the above HTML data instead of 404 error. being thrown. I think I should open an new issue.

### Getting back to @kamatil-dev's  issue, 
you can play with this project https://stackblitz.com/edit/nuxt-starter-trgjwj
in which everything works as I think it should based on the provided info, I even added a catch-all under demo `/api/demo/[...slug]`, that catches the request to /api/demo/user and because that route doesn't exist, I throw a 404 manually. 
 But the rest of the routes work, `/api/demo/session`, `/api/[db]/user`, and `/api/[db]/session`.
 
 /api/demo is a **static route path**, not a dynamic one (with a route path parameter), so it's treated separatedly as it should.
 
 Now, if what you want is the handler from /api/[db]/session to handle /api/demo/session, you can convert /api/[db]/session to a middleware server/middleware/session https://nuxt.com/docs/guide/directory-structure/server#server-middleware
 that will run in every request and you can compare the event.path to check what paths should use the session middleware, so it will catch requests to /api/demo/session and /api/anything/session
 something like 
 ```ts
 if (event.path.endsWith('session'))
 ```
 
 You can also import the handler from /api/[db]/session as you mentioned,  and run it inside the /api/demo/session handler, but feels "hacky" to me (even though it's valid middleware logic, middleware are just function and you call them either with the req/res arguments, on in case of Nuxt/nitro/h3  the event argument).
 
 But here's how:
 `~/server/`
 ```ts
 import sessionHandler from '../[db]/session'

export default defineEventHandler((event) => {
  const result = sessionHandler(event)
  // Or if sessionHandler is async
  // const result = await sessionHandler(event)
  console.log('demo/session')
// Some logic here and/or return data
})

 ```
 
 
 Hope this helps you.  Have you all a nice rest of the day🔥💚

**Comment by kamatil-dev** [comment]
I have a more complicated project, that has multiple folders(paths) so the way i have solve it -inspired by @angelhdzmultimedia - , is by re-creating dynamic child folders inside the static one, and export default from the corresponding file

`export { default } from "../[db]/user";
`

thank you guys
