### ISSUE TITLE
Error 500 when url with embedded credentials

### ISSUE THREAD

**Issue by gitFoxCode** [nuxt/nuxt#24238]
### Environment

Latest version of Nuxt

### Reproduction

Build the site and try accessing it using **Firefox browser** as https://user:password@website_url.com

### Describe the bug

Error: 
```
500
[GET] "/_nuxt/builds/meta/649e1437-0874-4340-97bb-b78055f1859a.json": <no response> Window.fetch: /_nuxt/builds/meta/649e1437-0874-4340-97bb-b78055f1859a.json is an url with embedded credentials.
```

### Additional context

The problem does not appear on other browsers

**Comment by gitFoxCode** [comment]
@huang-julien It doesn't need reproduction, this is exactly happens everywhere, even on nuxt.com: 
1. Open firefox
2.  Go to `https://user:password@nuxt.com` 
3. Error
but in chrome everything works good

**Comment by manniL** [comment]
Does it work when disabling the [app manifest](https://github.com/nuxt/nuxt/blob/4dd87f6e281bacacafa9566a21388d5a7a53f911/packages/schema/src/config/experimental.ts#L212C5-L212C16)?

**Comment by gitFoxCode** [comment]
@manniL With `appManifest: false` its working properly, what effect does appManifest? I don't know if I can just turn off this option without consequences for the rest of the site

**Comment by manniL** [comment]
Seems like the problem is the `$fetch` call to the manifest then ([source](https://github.com/nuxt/nuxt/blob/4dd87f6e281bacacafa9566a21388d5a7a53f911/packages/nuxt/src/app/composables/manifest.ts#L29)).

I wonder how important the support of it is as user credentials shouldn't be passed via URL anyway. It works in Chrome because [they disabled it](https://medium.com/@lmakarov/say-goodbye-to-urls-with-embedded-credentials-b051f6c7b6a3) for more than 5 years :D

**Comment by gitFoxCode** [comment]
@manniL I only use this for automatic preview for PRs, ngnix creates a page that requires a login and the automatic bot creates a url that you just click on without having to enter any data, it's not some critical but developers using firefox have a bit of a degraded experience

**Comment by manniL** [comment]
After discussing this internally, we don't think we can avoid that behavior from a technical POV.
