### ISSUE TITLE
Hot reload is losing while setting nuxtignore

### ISSUE THREAD

**Issue by JarvisChao** [nuxt/nuxt#24230]
### Environment

- Operating System: Darwin
- Node Version:     v18.17.1
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  pnpm@8.9.2
- Builder:          -
- User Config:      devtools, runtimeConfig, app, css, vite, vue, imports, modules
- Runtime Modules:  @pinia/nuxt@0.5.1
- Build Modules:    -

### Reproduction

https://codesandbox.io/p/sandbox/determined-murdock-kzxprh?file=%2Fpages%2Fhome%2FBanner.vue%3A6%2C1

### Describe the bug

I have some folder like "home, components" in the pages folder, but I would like to exclude them from routes.
```
pages/
  home/
    banner.vue
    index.ts
  product/
    components/
      List.vue
      Card.vue
    index.vue
```
So I set them inside .nuxtignore but they lost the hot reload.
It's working great in nuxt2, don't know why.

**Comment by manniL** [comment]
You could use the `pages:extend` hook to tell Nuxt that these components are not pages instead of letting nuxt *fully ignore them**.

Example via @hecktarzuli's [blog post](https://deltener.com/blog/nuxt-enterprise-patterns-component-management/#_1-tell-nuxt-not-to-treat-components-as-pages) to "ignore" all `pages/**/components/*.vue` files as pages. 

```ts
hooks: {
  'pages:extend'(pages) {
    const pagesToRemove: NuxtPage[] = []
    pages.forEach((page) => {
      if (page.path.includes('component')) pagesToRemove.push(page)
    })

    pagesToRemove.forEach((page: NuxtPage) => {
      pages.splice(pages.indexOf(page), 1)
    })
  }
}
```
