### ISSUE TITLE
Reset cookie expire date when read data with 'useCookie'

### ISSUE THREAD

**Issue by mohammad-ashrafi2020** [nuxt/nuxt#24408]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.17.1
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/test-nuxt-cookie?file=app.vue

### Describe the bug

when get cookie data with `useCookie `composable , the  cookie  expire date change to session

**Comment by mohammad-ashrafi2020** [comment]
in stackblitz site cookie not set but on localhost everythings is ok

**Comment by mohammad-ashrafi2020** [comment]
@danielroe
@ChrisGV04

**Comment by ChrisGV04** [comment]
Hi @mohammad-ashrafi2020!

Your issue occurs because of a known behavior of cookies on the browser, which is that to edit a cookie you must use the same options as when you created it or they will return to browser defaults.

So when you call `useCookie` inside the `getCookieData` function, you didn't pass any options as you did inside `setCookie`, which causes it to change every option back to browser default, including the expiration date back to "Session".

I modified your code a little bit and now it works. I moved the `useCookie` outside of the functions so that both functions use the exact same cookie instance. That way, any modifications won't alter the expiration date.

```ts
const testCookie = useCookie('test-cookie', {
  expires: new Date(new Date().setDate(new Date().getDate() + 30)),
});

const getCookieData = () => {
  if (testCookie.value)
    alert(
      `data = ${testCookie.value} | refresh browser and check cookie expire date`
    );
  else alert('cookie not found');
};

const setCookie = () => {
  testCookie.value = 'mohammad ashrafi';
};
```

If you need to use the same cookie on the browser inside multiple components, I guess creating a composable wrapping it is a good idea so that you always get the same reference to the cookie.

I know it's confusing, but this is not Nuxt specific, I'm afraid. It's the default behavior of cookies as far as I understand.

**Comment by mohammad-ashrafi2020** [comment]
@ChrisGV04 Thank you for the explanation . However, sometimes we need to receive only one cookie from the browser and use its value. For example, the Bearer Token in a cookie and when the application starts, I check if this token exists to determine if the user is logged in or not. But in the latest update, I cannot do this anymore, and when I receive the cookie, its Expire Date disappears, so the user has to log in again after closing the browser. This was working correctly in versions prior to 3.8.1.

**Comment by ChrisGV04** [comment]
Oh, I see. I'm not aware of any changes to the `useCookie` functionality post v3.8.1 related to that topic. I'm only aware that we added functionality to set expired cookies to `undefined` client-side and fixed an issue with cookies with expiration longer than 24.8 days.

Usually authentication cookies are not recommended to be readable from the browser by setting `httpOnly` for security reasons, but if you really need to read the cookie on the browser and `useCookie` is not meeting your needs right now, maybe a temporary workaround could be to directly use `document.cookie` and read the raw cookie value. Here's a very simplified version of `useCookie` that can only get the current value of the cookie client-side.

```ts
import { parse } from 'cookie-es';

export function getCookieValue(name: string) {
  // Only run on the browser
  if (!import.meta.client) return undefined;
  const cookies = parse(document.cookie);
  const cookieValue = cookies[name] as any;
  return cookieValue;
}
```

**Comment by mohammad-ashrafi2020** [comment]
#24503
