### ISSUE TITLE
support `__NUXT_DATA__` encryption from nuxt config file

### ISSUE THREAD

**Issue by devops3199** [nuxt/nuxt#24475]
### Describe the feature

Hi, I understand such tag `<script id="__NUXT_DATA__" ... />` is mandatory for hydration and client-side rendering, but I reckon showing raw values can cause security pitfall. I ran into a situation where secret values needed during client-side rendering.

It would be great if nuxt provides an encryption feature like below.

```
// nuxt.config.ts
export default defineNuxtConfig({
  nuxtData: {
    encryption: {
      type: 'AES',
      key: 'secret',
    }
  }
});
```

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by manniL** [comment]
Won't help much because the data has to be decrypted on the client-side, making it eventually readable, e.g. via `window.useNuxtData()`.

If you want to "hide" your data, send less or use e.g. server components so you have HTML that is returned and not JSON. But that way, people can still scrape it ☺️
