### ISSUE TITLE
Consola does not respect CONSOLA_LEVEL ENV in production

### ISSUE THREAD

**Issue by mkierdev** [nuxt/nuxt#24702]
### Environment

Nuxt 3.8

### Reproduction

Set CONSOLA_LEVEL=4 inside your .env file

Use consola.debug() function (defaults to log level: 4)

Run production mode (build && start)

console.log(consola) -> it will show, that level is set to 3.

### Describe the bug

Passing CONSOLA_LEVEL inside ENV is not respected while running **production mode** (build && start).
ENV is passed during build and other env values are read correctly.

CONSOLA_LEVEL is respected during development and changes logging level accordingly.

**Comment by danielroe** [comment]
This is because in production Nitro stubs out the entire consola library with a micro version using unenv:

https://github.com/unjs/nitro/blob/bd5e14dbc71b28ad571162ba477ac5e0e6fa68c8/src/rollup/config.ts#L50C1-L52
https://github.com/unjs/unenv/blob/71669005a44de019890097c3b1df19d96f67829d/src/runtime/npm/consola.ts#L10-L15

This can be disabled by setting `nitro.alias.consola` to `consola`.

**Comment by pi0** [comment]
unenv (1.5.0+) leverages consola core: https://github.com/unjs/unenv/issues/93

**Comment by danielroe** [comment]
Yes, exactly. But we don't support `process.env` within there, right?

**Comment by pi0** [comment]
Ah yes indeed 👍🏼 ~> https://github.com/unjs/unenv/issues/154

**Comment by mkierdev** [comment]
If this is by design, are there any negative effects of using consola in production? Performance impact?
What other logging solutions should be used if not consola?

**Comment by pi0** [comment]
@mkierdev Only main reason is bundle size impact and mainly for worker targets. consola is performant and universal enough :) By default, we use consola's core basic logger in prod to remove (unnecessary) fancy colors from production bundle. Not supporting log level via this mock is a bug and needs to be resolved.
