### ISSUE TITLE
Add/fix HMR support for `definePageMeta`

### ISSUE THREAD

**Issue by miosenpai** [nuxt/nuxt#24794]
### Environment

```
------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/github-bybsea?file=pages%2Findex.vue

### Describe the bug

Not sure if this is a known/intended limitation but HMR does not work for changes made to `definePageMeta`'s parameters. For example, if I change `layout: 'default'` to `layout: 'blue'` in the reproduction, the page does not update until I do a manual reload.

There are some DX scenarios where having HMR for `definePageMeta` parameters could be helpful (e.g. experimenting with different transition classes for page/layout transitions).

**Comment by pernelkanic** [comment]
Can i take up this issue?

**Comment by OrbisK** [comment]
I am currently trying to familiarize myself a little with vite HMR. I thought I'd link it to the issue here. I thought I'd write down what I've found out and also where I ended up stuck (for now).

First the obvious:
1. the `file.vue?macro=true` `import.meta.hot.accept` is never called. 
2. even if it would be called it should cause problems because the meta data is not in `mod` but `mod.default` (?).
3. it is relatively easy to trigger a reload of all modules, but this is like a full reload

Where I am a bit stuck:
- even if in `handleHotUpdate` the self accept of the macro triggers and then write the value to __nuxt_page_meta, there is no update of the layout
- I still don't understand exactly when and whether a module has to be invalidated via the moduleGraph.
- the logic for the case that both page meta and “normal” content is updated is still unclear to me

Maybe someone can give me feedback on some of the points. If not, then I hope it will help the next editor 😄
