### ISSUE TITLE
Nuxt 3 generate 500 error

### ISSUE THREAD

**Issue by xushnudbek20** [nuxt/nuxt#25060]
### Environment

 `npm run generate`

### Describe the bug

After install i18n in my project, I got 500 error on page in `npm run generate`
![image](https://github.com/nuxt/nuxt/assets/52786242/7ab4598b-4825-4fb3-91e6-1282e66e9994)

My i18n configuration like this: 
![image](https://github.com/nuxt/nuxt/assets/52786242/ceee0911-b19d-46d3-963d-625f2f93b698)

**Comment by xushnudbek20** [comment]
In Project was error on header popper. I fixed it

**Comment by didiraja** [comment]
Answering here just for googling purposes, i was struggling with the same kind of problem: **error 500 on prerendering pages who works and builds correctly**.

After a few hours, discovered <ins>the problem was a missing .env (or correct env appointment) during generate</ins>, because my nuxt config were receiving the variables.

**Comment by L-A-M-J-O** [comment]
Hello, how are you, I also have that same error but what do you mean, environment variables, on the i18n?
