### ISSUE TITLE
Ability to define middleware options

### ISSUE THREAD

**Issue by estnml** [nuxt/nuxt#25552]
### Describe the feature

Currently in Nuxt 3, if we define a middleware and suffix it with ".global" it will work for all routes. But sometimes we may want to run that middleware only the pages that inside a route, without customizing the default file based routing system.

```
export default defineNuxtRouteMiddleware((to, from) => {
    console.log("This middleware will work for the pages inside the folders 'admin' and 'superadmin'.");
}, {
    areas: ["admin","superadmin"] // Indicates that this middleware will work only for the pages/admin/**/*.vue and pages/superadmin/**/*.vue
});
```

With these options, the nuxt middlewares can be extended in the future easily and help write cleaner codes.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
We're reluctant to add this particular feature to core because it would require more involvement in the routing/middleware layer and might be incompatible with modules like `@nuxtjs/i18n`.

You can implement this by creating your own `defineMyNuxtRouteMiddleware` which accepts a second option and performs an early return if required.

You could also create a nested route only containing `<NuxtPage />` and `definePageMeta({ middleware: ['some'] })` that applies named middleware to a chunk of routes.
