### ISSUE TITLE
Add isHydrating composable

### ISSUE THREAD

**Issue by daniluk4000** [nuxt/nuxt#25662]
### Describe the feature

In current implementation nuxtApp.isHydrating is not reactive. There are some cases when we need reactivity - for example, I want to prevent users from inputting anything to our inputs while app is hydrating to prevent mismatch.

I suggest to add new composable, named isHydrating, or useIsHydrating (useHydrationState?) and make it a ref which value will be set on deferHydration before `app:suspense:resolve` hook call.

I would be happy to implement this if suggestion looks good.

### Additional information

- [X] Would you be willing to help implement this feature?
- [X] Could this feature be implemented as a module?

Workaround could be same user-made implementation based on `app:suspense:resolve` hook.

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by danielroe** [comment]
This seems like a good idea to me. `useHydrationState` seems okay - will raise with rest of team for naming + other thoughts.

**Comment by danielroe** [comment]
I think for the moment, it is straightforward to add your own implementation. Please do update if you have more info on potential use cases. Here's an example:

```ts
const allowUserInput = ref(false)
onNuxtReady(() => { allowUserInput.value = true })
```

**Comment by daniluk4000** [comment]
So it will be onNuxtReady then?

**Comment by daniluk4000** [comment]
Oh it is existing composable, lol. How did I miss that

This one's great, I'll stick to it. 

Use case for me is:

```typescript
const hydrationState = useHydrationState() //it could also be not a function but a global ref instead, called, like, "hydrationState"
const isInputReadonly = computed(() => hydrationState.value) //Some other cases here
```

It is easier to do with separate composable, but also could be done with

```typescript
const allowUserInput = ref(false)
onNuxtReady(() => { allowUserInput.value = true })
const isInputReadonly = computed(() => allowUserInput.value) //Some other cases here
```

It is more code & perfomance is a bit worse (not much tho), but that will do. 

I have missed that this composable does the same as I suggest, so it is a workaround indeed.

@danielroe you can close this if first example above is not enough (code is cleaner), single global ref for isHydrating will also be better for performance & produce less code. Basically, useHydrationState will be just more simple alias for this one. 

For now, we'll stick to our own composable for that:

```typescript
const hydrationState = ref(false);
let hydrationWatcherInit = false;

export const useHydrationState = () => {
    const app = useNuxtApp();
    //hydrationState should be false at this time
    if (import.meta.server || !app.isHydrating) return hydrationState;

    //Avoid ref trigger if already true
    if (!hydrationState.value) hydrationState.value = true;

    //Avoid duplicate hook watchers
    if (!hydrationWatcherInit) {
        hydrationWatcherInit = true;
        app.hooks.hookOnce('app:suspense:resolve', () => {
            hydrationState.value = false;
        });
    }

    return hydrationState;
};
```

**Comment by DawidKopys** [comment]
Is this feature planned?
@danielroe you asked about more potentiall use cases so here it goes: 

We are using Playwright to implement e2e tests for our Nuxt application.
We are in very much early stages in our journey here, but we came across one problem:
- we want to click some button after loading the page
- our tests do click the button, **but it happens before hydration** - as a result, nothing happens and the test fails

[Playwright suggest to disable the button until after the hydration as the "right fix"](https://playwright.dev/docs/navigations#hydration:~:text=The%20right%20fix%20for%20this%20issue%20is%20to%20make%20sure%20that%20all%20the%20interactive%20controls%20are%20disabled%20until%20after%20the%20hydration%2C%20when%20the%20page%20is%20fully%20functional.) and I believe they are right.
It fixes e2e test because Playright does ["auto-awaiting"](https://playwright.dev/docs/actionability) and waits for the button to not be disabled before clicking it.

We have considered other options for waiting for hydration in our e2e tests, but:
1. none of them are as reliable (for example: waiting some arbitrary delay before clicking the button, waiting for `load` event)
2. they make tests more complicated
3. disabling the button until after the hydration would not only fix our e2e tests - it would also make sense from user perspective! Without it, user with slow device may get frustrated because a button he is clicking is not doing anything.
When we disable it until after hydration we are giving a user a clear hint the button will not do anything at the moment.

Having composable such as `useHydrationState` to take care of this logic would make disabling the button until after hydration a breeze.

**Comment by danielroe** [comment]
@DawidKopys We actually merged a couple of helpers to `@nuxt/test-utils` for exactly this use case. `createPage('/')` now automatically awaits until hydration. Additionally, `page.goto('/', { waitUntil: 'hydration' })` is supported. 

(See https://github.com/nuxt/test-utils/pull/739 for more details.)

Have you tried something like my comment above? What were the problems/issues with that way?

https://github.com/nuxt/nuxt/issues/25662#comment-3746862

**Comment by daniluk4000** [comment]
I also have my useHydrationState example above, basically implements my request

**Comment by DawidKopys** [comment]
@daniluk4000 On a second thought, maybe this scary cross-request state pollution is not an issue there and I am being overly cautious. You are not changing this state on server side at all and it is mutated on client side only. I will stick with your solution for now then. Thanks!

I ended up doing it this way:
```TypeScript
const isHydrating = useHydrationState()

const buttonDisabled = computed(() => isHydrating.value || import.meta.server)
```

**Comment by n0099** [comment]
https://github.com/nuxt/nuxt/issues/25662#issuecomment-1935779379
Pinia variant:
```ts
export const useHydrationStore = defineStore('hydration', () => {
    const isHydratingState = ref(false);
    const isHydrationHooked = ref(false);
    const nuxt = useNuxtApp();

    const isHydrating = () => {
        if (!(import.meta.client && (nuxt.isHydrating ?? false)))
            return isHydratingState;

        isHydratingState.value ||= true;

        if (!isHydrationHooked.value) {
            isHydrationHooked.value = true;
            nuxt.hooks.hookOnce('app:suspense:resolve', () => {
                isHydratingState.value = false;
            });
        }

        return isHydratingState;
    };

    return { isHydrating };
});
```
