### ISSUE TITLE
NuxtImg:  WARN Overriding NuxtImg component.

### ISSUE THREAD

**Issue by castrogarciajs** [nuxt/nuxt#25787]
Hello team, 

I get this warning in the console when using the `NuxtImg` component but I can't understand what it means.

info of nuxt: 
------------------------------
- Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  pnpm@8.9.2
- Builder:          -
- User Config:      app, devtools, modules, css, ui, colorMode, postcss
- Runtime Modules:  @nuxt/ui@2.9.0, @nuxt/image@1.0.0
- Build Modules:    -
------------------------------

```log
[10:40:23 AM]  WARN  Overriding NuxtImg component. You can specify a priority option when calling addComponent to avoid this warning.

[10:40:23 AM]  WARN  Overriding NuxtPicture component. You can specify a priority option when calling addComponent to avoid this warning.
```

**Comment by Hecatron** [comment]
I've just tried this under windows and linux and the issue is still there even after the above patch
For a reproduction
```sh
npx nuxi@latest init docs -t themes/docus
cd docs
pnpm install --shamefully-hoist
pnpm add @nuxt/image
```

then just add '@nuxt/image' to the modules section
as soon as you load the page it comes up with ` Overriding NuxtImg component. You can specify a priority option when calling addComponent to avoid this warning.`

**Comment by danielroe** [comment]
The fix is released in the latest version of Nuxt Kit but other modules may be using older versions. Try adding a resolution or override to pin the kit version to the latest one.

**Comment by onurusluca** [comment]
Also having this with [shadcn-vue](https://www.shadcn-vue.com/docs/components/breadcrumb.html)

```
[11:08:09]  WARN  Overriding Toaster component. You can specify a priority option when calling addComponent to avoid this warning.


[11:08:09]  WARN  Overriding Calendar component. You can specify a priority option when calling addComponent to avoid this warning.
```

**Comment by AlvinWang627** [comment]
> Also having this with [shadcn-vue](https://www.shadcn-vue.com/docs/components/breadcrumb.html)
> 
> ```
> [11:08:09]  WARN  Overriding Toaster component. You can specify a priority option when calling addComponent to avoid this warning.
> 
> 
> [11:08:09]  WARN  Overriding Calendar component. You can specify a priority option when calling addComponent to avoid this warning.
> ```

I have this warning too in nuxt3.
I remove this code from nuxt.config.ts.
The warn will disappear.
```
  shadcn: {
    /**
     * Prefix for all the imported component
     */
    prefix: "",
    /**
     * Directory that the component lives in.
     * @default "./components/ui"
     */
    componentDir: "./components/ui",
  },
```

**Comment by danielroe** [comment]
@AlvinWang627 Would you open a new issue with a reproduction? 🙏

**Comment by AlvinWang627** [comment]
> @AlvinWang627 Would you open a new issue with a reproduction? 🙏

I found the error, it's my problem.

I put `shadcn.ts` in the `modules folder` and also put it in `nuxt.config.ts.`
So I import shadcn modules twice.

**Comment by gregmsanderson** [comment]
For anyone else getting this kind of error

```
[11:08:09]  WARN  Overriding Toaster component. You can specify a priority option when calling addComponent to avoid this warning.


[11:08:09]  WARN  Overriding Calendar component. You can specify a priority option when calling addComponent to avoid this warning.
```

... and finding neither of the above solutions work, I realised that it can be caused by actual duplication. Despite the shadcn-vue component names being different, its `calendar` and `v-calendar` _both_ export `Calendar`, and `sonner` and `toast` _both_ export `Toaster`. For a demo I installed _all_ the shadcn-vue components using their CLI, and hence got that error from that duplication.

The solution was simply to delete one from each.
