### ISSUE TITLE
useHead: Persistent Body & Html Classes Across Layouts After Navigation

### ISSUE THREAD

**Issue by tberk** [nuxt/nuxt#25938]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.17.1
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    -
- Package Manager:  pnpm@8.15.3
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @nuxtjs/tailwindcss@6.11.4
- Build Modules:    -

### Reproduction

https://stackblitz.com/~/github.com/tberk/nuxt-layout-bug

### Describe the bug

When using the useHead composable in Nuxt 3 to set bodyAttrs classes in different layouts, the classes set in one layout persist and are incorrectly applied to other layouts after navigation. This behavior leads to unintended styling issues across different parts of the application.

Admin Layout:
```vue
<script setup lang="ts">
useHead({
  htmlAttrs: { class: 'h-full admin-layout-html-class' },
  bodyAttrs: { class: 'h-full overflow-hidden admin-layout-body-class bg-gray-900 text-white' },
})
</script>
```

Default Layout
```vue
<script setup lang="ts">
useHead({
  htmlAttrs: { class: 'h-full default-layout-html-class' },
  bodyAttrs: { class: 'h-full default-layout-body-class bg-gray-900 text-white' },
})
</script>
```

- Navigate from a page using the default layout to a page using the admin layout.
- Then, navigate back to the page using the default layout.
- The body and html retains the classes set by the admin layout's useHead, in addition to the classes defined in the default layout. This results in a mix of styles from both layouts being applied incorrectly.

HTML: h-full default-layout-html-class admin-layout-html-class
BODY: h-full default-layout-body-class bg-gray-900 text-white overflow-hidden admin-layout-body-class

**Comment by harlan-zw** [comment]
Can confirm there is a bug here, the workaround would be preferring a single useHead in app.vue with toggles.

```ts
// do static (should be in nuxt.config ideally)
useHead({
  htmlAttrs: { class: 'h-full' },
  bodyAttrs: { class: 'h-full bg-gray-900 text-white' },
})

// dynamic
const isAdmin = computed(() => {
  // logic
})
useHead({
  bodyAttrs: { 
     class: {
        'overflow-hidden': isAdmin
     }
  },
})
```

**Comment by ojvribeiro** [comment]
It's important to note, in @harlan-zw's example, the use of the computed property inside `bodyAttrs` without `.value`. Using `isAdmin.value` won't work.

**Comment by harlan-zw** [comment]
So finally had a chance to look at this one and was a wild one to debug, essentially we have a race condition due to the `page:finish` hook being called in parallel when two pages finish at the same time. In the reproduction, this is `pages/nested.vue` and `pages/nested/index.vue`, so it seems like it's intentional but it is a bit misleading.

You can see this highlighted in the demo with the below code.

```ts
<script lang="ts" setup>
const nuxtApp = useNuxtApp()
nuxtApp.hooks.hook('page:finish', (ctx) => {
  if (!nuxtApp.isHydrating) {
    console.log('page finished!', ctx)
  }
})
</script>
```

This has been fixed upstream by only supporting a single dom update at any time, avoiding the race condition.

Within Nuxt maybe there is a better hook to sync the DOM on rather than `page:finish` :thinking: Otherwise the upstream solution will have to do for now. 

https://github.com/nuxt/nuxt/issues/23620 is the same issue.

cc: @danielroe
