### ISSUE TITLE
Distinct more between client website, client server (ssr) and api (H3)

### ISSUE THREAD

**Issue by MickL** [nuxt/nuxt#26103]
### Describe the feature

I am using Nuxt 3 for developing both: A Vue website with SSR and a Rest API. Coming from Angular (Frontend with SSR) and NestJS (API) this seemed to be a fantastic step, developing both together in one place. However I have a bit of frustration doing so, and I would suggest to make a bigger distinction between the client, client SSR and the API:

- A server that runs for the routing and ssr of the Vue app
- A separate h3 server that handles HTTP requests to build an API
- The Vue app that gets hydrated on the client (preferably hydration is skipped if a page doesnt contain any interactivity, this is what Deno Fresh does)

Right now the server part is mixed up between SSR and API:

- I write a server middleware to protect my `/api` routes but it also runs for the Nuxt routing of the frontend app or for delivering an asset like favicon. And where is even this `__nuxt-error/` folder coming from? I would expect the server middleware to just affect my /api server handlers and nothing else.
- The server handlers often return a HTML website, for example when Nuxt is starting my api routes return a HTML website instead of a http error or timeout. Or a 404 also returns a HTML website. I want my API to return either JSON or a http error code.
- The nuxt config is mixed up between SSR server and API server
- Auto imports are a total pain. I cant jump into functions by clicking them in my IDE because I end up in this imports file. In Angular or NestJS I click a function and I see the definition of it and even the same api documentation written as comments as I would find on the website. This also means I dont always have auto completion in my IDE or type suggestions. Further if Nuxt is not running auto imports are not generated. What is even the benifit of auto imports in a world of IDEs that "automatically" add all imports anyway?
- I cant unit test a server handler function by its own (or if I can it is not documented)
- It takes 15-20s on a modern computer until an e2e test setup is ready. I simply want to make a fetch to my H3 server and see if the response is correct or not, why does it take so long?
- The "server" part has barely any documentation. There is just one page in the Nuxt docs and the H3 website doesnt have much explanation or examples as well. For example `getValidatedBody()` or `readValidatedQuery()` are amazing functions, especially together with libraries like zod, but the only docs are a blog post where they have been announced. `readMultipartFormData()` to handle file uploads or `useRequestFetch()` isnt documented at all.
- Finding other informations or examples is really hard. What to goolge for? "Nuxt server" could be anything and "h3" mostly doesnt give results.
- Missing docs: How does the build step work? I see a client and a server app being built, then another server built (Nitro) and files copied around. Why is there a .nuxt and .output folder and not just one? What is the task of Vite and Rollup and Nitro in the build step?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by pi0** [comment]
Hi, dear @MickL thanks for sharing all your feedback. I try to answer some of your concerns individually and I guess some are to be improved.

> A separate h3 server that handles HTTP requests to build an API

The simplicity of full-stack experience that is possible with Nuxt 3 + Nitro is because we share a single server. If they were separated, we would lose some benefits including the ability to in-server `fetch` another API route during `SSR` process and the need to set the base URL. 

We understood the implications of having both SSR and backend API in the same server and (unlike most of alternative frameworks that tightly couple backend with server components), with Nuxt, there is a separated `/server` directory that defines the "backend" boundary from rest of universal (CSR+SSR) app.

Still, if you expect a completely separated/isolated app, you have two choices:

- Create `server/api/[...].ts` with a [nested router](https://h3.unjs.io/guide/router#nested-routers)
- Build and deploy `server/` directory directly with [nitro](https://nitro.unjs.io/)

> I write a server middleware to protect my /api routes but it also runs for the Nuxt routing of the frontend app or for delivering an asset like favicon

You can guard your server middleware using a simple `if (event.path.startsWith('/api')` condition to only apply your middleware for your API routes. 

However please consider that global middleware are not best practices in a H3/Nitro app. You can implement auth with a `useAuth` composable and register it for authenticated API route using [object syntax](https://h3.unjs.io/guide/event-handler#object-syntax) -- it might take you a little while to adopt from traditional middleware model but is much much safer as has no global side-effects.

> The server handlers often return a HTML website, for example when Nuxt is starting my api routes return a HTML website instead of a http error or timeout

Normally when you fetch/curl `/api` routes Nuxt error handler smartly switches to JSON responses. When directly opening URLs in the browser, Nuxt uses an alternative HTML page for easier debugging. 

1. If it is not behaving like this, it might be a bug
2. If you certainly always want a JSON response, you can simply override `nitro.errorHandler`

> The nuxt config is mixed up between SSR server and API server

API/Server is configured with explicit `nitro: {}` namespace in config.

> Auto imports are a total pain. I cant jump into functions by clicking them in my IDE because I end up in this imports file

We are aware of some known issues with auto imports DX in IDEs and internally discussing to overcome them.

However, you can both easily opt-out from auto imports by setting `autoImports: false` or always explicitly import from `h3`.

> I cant unit test a server handler function by its own

Nuxt test utils provides a "nuxt" environment where you have all modules and integrations enabled. If you explicitly need **unit** tests, you probably want to directly import event handlers and unit test them in a custom setup however you will loose the modules usage in this context.

> The "server" part has barely any documentation

We recently made new docs for https://h3.unjs.io with examples section. If you feel anything is missing, feel free to directly raise an issue in h3 or nitro repo 👍🏼 

> How does the build step work? I see a client and a server app being built, then another server built (Nitro) and files copied around. Why is there a .nuxt and .output folder and not just one?

Defenitly deserves more docs and I'm glad you care enough to ask about these.

**Comment by MickL** [comment]
Thanks for the quick and detailed response! I understand the difficulties in making the separation more obvious. I am a bit frustrated and would love to just create my API using Nitro/H3 in a separate project, but then I would lose the ability to fetch an api route during ssr without an http step.

I think it would be great for the DX, as well as maintainability and testability, if frontend ssr server and api server are two different apps but "somehow" the ssr server can call functions from the api server without making an http request. This would also clearify the build step and the black holes at least I have understanding how the one server is handling SSR and API in one app.

Another as a possible solution you could just make the distinction in the DX more clear. For example differentiate the naming for "server" into two parts: API and SSR because right now it is a bit confusing. Or making separate nuxt-configs for ssr-server and api-server. Also all this playing together between Vue, Nuxt, Vite, H3, Nitro, and even Rollup is used even tho I thought with Vite there is no more need of Rollup, is hard to understand.

Talking about the docs, this is maybe a bit off topic but I want to refer to it one more time. A lot of things you mentioned are things that I never heard before and I am using Nuxt heavily for some time now and read most of its documentation. But it shows that docs and examples are missing especially when it comes to writing APIs within Nuxt (but probably alos within Nitro/H3). I want to point out two things exemplary:

> global middleware are not best practices in a H3/Nitro app. You can implement auth with a useAuth composable and register it for authenticated API route using [object syntax](https://h3.unjs.io/guide/event-handler#object-syntax)

I am not exactly sure what this means and how it would help me authenticating the user. I was following the Lucia Auth docs, so they were my point of reference in how to implement auth in Nuxt. I ended up getting frustrated between writing middlewares for the server and the client that first run on the api server, then in the ssr server asking the api server to get the authenticated user, then again in the browser asking the api server once again for the autenticated user.

> We recently made new docs for https://h3.unjs.io/ with examples section. If you feel anything is missing, feel free to directly raise an issue in h3 or nitro repo 👍🏼

This is great and I know documentation takes a lot of effort. But for me as a developer I am looking for informations but I find barely anything:

Example 1: https://h3.unjs.io/utils/request#getvalidatedqueryevent-validate
- No types: How does event and validate look like? What does it return?
- No explanation: How to validate? I know I can use Zod for example, but I know it from the announcement blog post
- No code examples: In the announcement blog post there were examples using zod

Example 2: https://h3.unjs.io/utils/request#readmultipartformdataevent
- No types for event or return value
- No explanation, for example how does it work with file uploads? Does it work with file uploads? I only know it does because I randomly found a comment in a Github issue.
- Example could be added for file upload

Example 3: I found `useRequestFetch()` in the Lucia docs but I cant find it on the h3 website or even with Google.

Regarding the docs I also want to mention the amazing api docs of Angular in contrast: If I look for a specific function, e.g. lets pick router's `navigate()` as an example: https://angular.io/api/router/Router#navigate

It shows explanation, parameters with typings AND explanation as well as examples. Further more, these docs are generated out of the comments in the code of Angular. This means if I am developing and I click with my IDE into `navigate()` function, I see the exact same docs right away while in Nuxt I end up in the imports file that gives me zero information and if I then click further into that I end up in gibberish with tons of generics that doesnt help me at all.

**Comment by pi0** [comment]
Thanks for your patience reply and for helping with this discussion to identify improvement points.

Keeping backend/Nitro DX separated or integrated with Nuxt, is a two-folded story and I think you are completely right to feel overwhelmed about an additional new concept to the same stack.

Nuxt was born when the new "SSR" frameworks came in and we wanted to make an easy and universal experience for mainly _front-end developers_ that can leverage server-side-rendering without or at least with less complexities. Still, there is "additional" learning and coding required when developing an SSR-enhanced website compared to a CSR website for example we need to take care about not sharing the global state and not sharing window.

Similar to SSR, FullStack development with backend/API integrated into the same stack, is a new concept, and Nuxt 3 is positioned to be one unified meta-framework that you can use to develop universal rendering and API routes in the same place. When using Nitro with Nuxt, Nuxt is responsible for loading config from a single `nuxt.config` file, adding Nuxt module integrations, and all necessary additional Nitro config that makes a full-stack development possible.

Regarding testing, it also comes to the fact that, testing a full-stack application (with both frontend and backend) is at least more heavy task than unit testing event handlers because without having a "nuxt" env, we lose all module integrations and nuxt built-in additions.

Regarding auth, I would recommend take a look at [nuxt-auth-utils](https://github.com/Atinux/nuxt-auth-utils) it is following most of best practices for Nuxt 3 API design and gives you out of the box composables for authenticating API routes.

Having all these said and the balance that Nuxt needed to keep to "control" both Rendering (SSR/CSR) and API from a single server/port, you can still always independently run nitro server using `npx nitropack dev server/`. Nuxt/Nitro is currently the **only** framework that allows users to develop and deploy API part independently while all other meta frameworks give you option of using their full-stack.

---

Regarding H3/Nitro docs, as I mentioned previously it is rather new and work in progress. We got this feedback from the community frequently that made initial docs and want to improve the examples for each of the built-in composables over the time. Any contribution to complete the docs is more than welcome or feel free to just directly make an issue listing the utils you feel deserve more details.

**Comment by MickL** [comment]
One more thing about the Nuxt auto import feature, it doesnt really work to disable it:
 
I tried disabling it but Nuxt still creates a `nitro-imports.d.ts` which then my IDE (WebStorm) picks up and thinks the functions are defined and doesnt recommend me to add the imports, while on the same time the compiler is complaining of unknown functions. So in the end the DX is even worse.

**Comment by MickL** [comment]
Sorry for spamming but another frustrating thing is that every time I updated to latest Nuxt there were crucial bugs:

3.10.0: https://github.com/nuxt/nuxt/issues/25724
3.11.0: https://github.com/nuxt/nuxt/issues/26345

**Comment by pi0** [comment]
I'm not sure #26345 is related to this topic. It is a new utility export used by nuxt directly.

**Comment by MickL** [comment]
Just found this, it is exactly what I was hoping for :) [#26444](https://github.com/nuxt/nuxt/issues/26444)

**Comment by pi0** [comment]
Glad you like this proposal. Would you still like to keep this conversation open? Ideally we can split it into smaller sub-topic if you think there are ideas we can make it more clear.

**Comment by MickL** [comment]
Just another thing would be to split up Nuxt SSR server and backend server more. At least as much as we could launch the Nitro backend api server separate without launching the Nuxt app. There also has been the idea by @Hebilicious that the backend could be totally replaceable by any other implementation:

https://github.com/nuxt/nuxt/issues/26444#issuecomment-2027957028

If we might one to have this as an open issue or at least discussion it would be great, then we could close this one.

**Comment by pi0** [comment]
You can already use `nitro build server/` I believe in a Nuxt project and extend/import `server/nitro.config` for `nuxt.config` for separate builds. (however, you will lose the benefit of the consistent module ecosystem of Nuxt + direct calls but will gain the freedom to deploy/test the server separately). If had any questions about this, feel free to open a discussion i think we could at some point even document this pattern for Nuxt.

I don't think it would be something feasible to split things any further for server builds. The idea of supporting an alternative HTTP framework (to replace h3) with something else like hono or fastify, had been in the roadmap of Nitro for a long time. If there are enough user requests we will consider it but it is already doable too since h3 has full middleware compatibility. For completely external backends like Laravel, you can use proxy route rules to redirect requests to them.

**Comment by MickL** [comment]
Not sure if possible, but my feature request would be: Having a separate Nitro server by default to make api testing dx more "ok" and not let a request to the SSR go through the backend api middlewares BUT let SSR still be "instant" by whatever kind of communication. (Even if it would be a http request it would be kinda "instant" anyway because both server apps are running on the same worker or am I wrong?).

**Comment by jsshapiro** [comment]
I wish to add a comment to this discussion that may be helpful for future readers.

Nuxt (and JamStack generally) can be confusing because there are (or can be) two distinct servers. One is the server that publishes your application. This is the one that performs server-side rendering if you choose to do that. The other is the server that publishes the services _behind_ your application. This is the one publishing the API that multiple applications might use. When you are building a single application in a full-stack way, you use the api/ directory to define your API, use server/ to implement your business logic, and the two servers are the same.

The Nuxt "layers" feature makes it really attractive to build multiple, distinct applications from a common base of components. For example, you might have a multi-tenant application in which your direct customers have access to an "admin" interface for their tenant while _their_ customers only have access to the per-tenant eCommerce site. Or you might want to have very small internal applications for specific purposes. Along the way, you may discover that you want to separate out the business logic server.

@pi0 suggests using nitro build, and that seems like a good idea. Alternatively, you could adopt a REST (possibly OpenAPI) or GraphQL communication layer. But his point about losing type information seems relevant, and I haven't (yet) seen a good post about how to manage that.

Still, the key point is that nothing in NuxtJS _requires_ you to build the API server from NuxtJS. You could choose to implement your caller-side API (I can't say client-side, because it's also called by the application server) in a layer, generate the code from swagger (or whatever), and then call it where needed. NuxtJS is still very useful for implementing the variations on pre-rendering in a structured way.

The great thing about JamStack-style frameworks is that they make simple things simple. And sometimes performant. The less great thing is that they tend to make more complex things harder. Nothing's perfect.
