### ISSUE TITLE
Improve docs regarding environment variables, useRuntimeConfig and process.env

### ISSUE THREAD

**Issue by DavidDeSloovere** [nuxt/nuxt#26149]
### Describe the feature

(if this is not appropriate for a feature request, I'll be happy to report this differently)

This request is a result of #25047 
The docs aren't super clear about the best practice for configuring runtime config using `process.env`, especially for Cloudflare (but probably not limited to).

From our joint findings,
having an environment variable NUXT_PUBLIC_VALUE_ONE defined is not enough,
the runtime config needs to be defined as following:

```ts
export default defineNuxtConfig({
  devtools: { enabled: true },
  runtimeConfig:  {
    public: {
      valueOne: process.env.NUXT_PUBLIC_VALUE_ONE,
    }
  }
})

```

I don't know enough how this actually works to say that this should be done always, for every app and every rendering and every hosting platform. If this is THE way, docs should show it; if this is A way, docs should mention if.

I have spent some hours on this, other probably have don't the same.

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by IonianPlayboy** [comment]
@DavidDeSloovere did you start already working on this ? Since you mentionned that you would be willing to do this yourself, I would rather ask for your approval before taking this issue.

If that's okay with you, I'm interested in looking into this. I feel like there is an opportunity to improve the documentation about configuration in general, by including feedback from #25812 as well.

**Comment by DavidDeSloovere** [comment]
All yours @IonianPlayboy 
I have not done anything because I'm not sure how it works. Was willing to contribute if in the way that someone could give me enough info to start from.

**Comment by manniL** [comment]
This should be sufficiently documented on https://nuxt.com/docs/getting-started/configuration - Anything you are missing on it?

**Comment by jakubednar** [comment]
It is also documented on this page https://nuxt.com/docs/guide/going-further/runtime-config.

**Comment by DavidDeSloovere** [comment]
What is not documented, is that you can (or should?) use process.env.VAR_NAME in the runtimeconfig. But if it's unknown when this should be done, then it's probably best not to mention it.

**Comment by chrisspiegl** [comment]
When defining the `runtimeConfig` with `process.env.NUXT_` variables… they don't get run on execution but rather are put right into the build process (and then deployed)/
```
runtimeConfig: {
  myVar: process.env.NUXTMY_VAR,
},
```

This leads to the variable value being part of the deploy rather than being read from Cloudflare… that's why it appears to be "working" but in reality, if you run a different `.env` variable in Cloudflare it would not be updated.

I checked this by searching for the variable value in the `dist` folder.
