### ISSUE TITLE
sendRedirect not redirecting in api route or server middleware

### ISSUE THREAD

**Issue by samk-dev** [nuxt/nuxt#26182]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.11.0`
- Nuxt Version:     `3.10.3`
- CLI Version:      `3.10.1`
- Nitro Version:    `2.9.3`
- Package Manager:  `npm@10.2.4`
- Builder:          `-`
- User Config:      `devtools`, `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-rayiqq?file=server%2Fapi%2Fforce-redirect.ts

### Describe the bug

After updating to Nuxt `3.10.3` the `sendRedirect` returns html instead of redirecting. This happens when used either in `server/api/*` or `server/middleware`

**Comment by teddygunawan** [comment]
@samk-dev 
Hello! I think you misunderstand the usage of sendRedirect in this context. In this case, because u call it using the fetch method on the client side, what happens is that the nitro server will send 302 alongside a location response header, which will cause the browser to try the fetch request on the redirected url instead. You can look at the network tab of developer console to confirm this. 

In another context, if for example you are trying to open that url instead, which in this case is /api/force-redirect, you can see that the page is properly routed to /login, this is also because of the header and status code. This is simply how the browser works.

as for the reason that it returns the index page, you can see from the sendRedirect spec that it mentions
> it adds the location header to the response and sets the status code to 302 by default.
> In the body, it sends a simple HTML page with a meta refresh tag to redirect the client in case the headers are ignored.

If you wish to do client side redirect, to change the way you code the redirection, e.g. return the url for the client to manually redirect to.

Hope this helps!

**Comment by manniL** [comment]
As @teddygunawan said!

**Comment by samk-dev** [comment]
@teddygunawan Thanks a lot for the great explanation
