### ISSUE TITLE
`imports` config is not consistent between page and server

### ISSUE THREAD

**Issue by eunjae-lee** [nuxt/nuxt#26367]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.11.0`
- CLI Version:      `3.10.1`
- Nitro Version:    `2.9.4`
- Package Manager:  `npm@9.5.1`
- Builder:          `-`
- User Config:      `devtools`, `nitro`, `imports`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/eunjae-lee/auto-import-test

https://github.com/nuxt/nuxt/assets/499898/dae82440-acc8-4120-8e29-56f5754cb88a

### Describe the bug

I put a folder into `imports.dirs` config, but on the server endpoints, the type is not being inferred. If I move it over to `nitro.imports.dirs`, the type is being inferred on the server, but the page breaks.

**Comment by danielroe** [comment]
The reason is that Nitro + the Vue part of your app are separate contexts. They therefore deliberately have different auto-imports. If you have a file which exports 'safe' utilities that can both be used in server routes _and_ in the Vue part of your app, you can add the directory to both `imports.dir` and `nitro.imports.dirs`.

It's not a bug but I realise it's a bit confusing. Maybe we can improve the docs here?

**Comment by eunjae-lee** [comment]
@danielroe thanks for the clarification. It makes sense that there are separate configurations. And yeah, it would be nice to have it clearer on the docs :) 

FYI, I referred to these two pages:

- https://nuxt.com/docs/guide/concepts/auto-imports
- https://nuxt.com/docs/guide/directory-structure/composables
