### ISSUE TITLE
Improved Directory Structure

### ISSUE THREAD

**Issue by Atinux** [nuxt/nuxt#26444]
### Discussed in https://github.com/nuxt/nuxt/discussions/20251

<div type='discussions-op-text'>

<sup>Originally posted by **Atinux** April 13, 2023</sup>
Nuxt 3 is now a fullstack framework thanks to [Nitro](https://nitro.unjs.io) with the ability to have [auto-imported modules](https://nuxt.com/docs/guide/directory-structure/modules) and [layers](https://nuxt.com/docs/getting-started/layers), I believe it's time to rethink the directory structure to give more separation for the "app" level.

This is the proposal I am thinking of:

```bash
.output/
.nuxt/
app/
  assets/
  components/
  composables/
  layouts/
  middleware/
  pages/
  plugins/
  utils/
  main.vue
  router.options.ts
content/
layers/
modules/
node_modules/
public/
server/
  api/
  middleware/
  plugins/
  routes/
  utils/
nuxt.config.ts
```

Do you see any downside of this approach?

The minimal starter would then be:

```bash
app/
  main.vue
public/
  favicon.ico
nuxt.config.ts
```

**Comment by HigherOrderLogic** [comment]
Shouldn't we also move the `content/` dir into the `app/` dir? I think that way, it would align better with the usage of each dir.

**Comment by Atinux** [comment]
Not sure for `content/` as I found it similar to `public/` and the data is not bundled.

It also allows having a minimal usage when used with a Nuxt Layer:

```ts
content/
  index.md
nuxt.config.ts <-- Using extends: 'my-docs-theme'
```

**Comment by Zihan-Hu** [comment]
(BTW should `middleware` dir be `middlewares`?)

**Comment by they-cloned-me** [comment]
Love it! 💚

What will be the best approach to share common utils that can be used in `/server` and `/app` e.g some string manipulation utilities.
Put’em in `/layers`?

**Comment by Strift** [comment]
Love the new proposal!

Would you need to follow this structure to upgrade from v3 to v4?

Laravel recently changed its boilerplate folder structure. Although the new version works with the previous folder structure, users fear that if they don't adapt to the new structure, future code might break because they have things in the wrong place.

**Comment by Atinux** [comment]
I believe we can easily detect the old format and have a way to upgrade to the new one by running either `nuxt dev` or with a `nuxi upgrade` command.

**Comment by ennioVisco** [comment]
> ### Discussed in #20251
> Originally posted by **Atinux** April 13, 2023 Nuxt 3 is now a fullstack framework thanks to [Nitro](https://nitro.unjs.io) with the ability to have [auto-imported modules](https://nuxt.com/docs/guide/directory-structure/modules) and [layers](https://nuxt.com/docs/getting-started/layers), I believe it's time to rethink the directory structure to give more separation for the "app" level.
> 
> This is the proposal I am thinking of:
> 
> ```shell
> .output/
> .nuxt/
> app/
>   assets/
>   components/
>   composables/
>   layouts/
>   middleware/
>   pages/
>   plugins/
>   utils/
>   main.vue
>   router.options.ts
> content/
> layers/
> modules/
> node_modules/
> public/
> server/
>   api/
>   middleware
>   routes/
>   utils/
> nuxt.config.ts
> ```
> 
> Do you see any downside of this approach?
> 
> The minimal starter would then be:
> 
> ```shell
> app/
>   main.vue
> public/
>   favicon.ico
> nuxt.config.ts
> ```</div>
> ```

I guess also a `tsconfig.json` is required for the minimal starter

**Comment by nvdg** [comment]
> I would say in `~/utils` if they are used both in server and app

Is this also the folder to place data types? For example data structures stored in cookies or used in api routes that are used by both server and client? I know there is support for the '~/types' folder but it isn't mentioned anywhere.

**Comment by Lootjs** [comment]
Can we keep server/plugins/ for server plugins? 👀

**Comment by manniL** [comment]
@Lootjs yes, `server/plugins` will not be removed 👍🏻

**Comment by Lootjs** [comment]
*sigh of relief*

**Comment by danielroe** [comment]
We're also discussing ideas like `ui`, `web`, `frontend`, `vue`, but still feeling that `app` is frontrunner here. Other ideas welcome.

**Comment by nvdg** [comment]
> 1. app/server - without analyzing what is the role of each directory I think it sounds more natural to say that UserSchema is part of the app. Server importing from app does not sound that bad, right?
> 2. client/server - I could choose server as it the source (where user is created) or I might go with a /shared folder from which both will import.
> 3. frontend/backend - as above but I think that there will be more preference over a shared folder.
> 

What I like about Nuxt is that it blurs the lines of a traditional frontend/backend, client/server setup. And with server side pre rendering the frontend is not necessarily running on the clients side. So in that line naming it client/server might make you think in that more traditional way. Something like interface/api might work since it doesn't imply where it is run just what it is.

**Comment by eunjae-lee** [comment]
In my mind, Nuxt app is a combination of vue's frontend and the backend. So seeing `app` and `server` separately makes me feel like this server is something outside this Nuxt app. But I like the server being separate as it's really server-only thing.

On the other hand, `app` folder contains lots of stuff that is actually shared across frontend and backend.

```
.output/
.nuxt/
content/
layers/
modules/
plugins/          <- I've moved plugins out on the same level as modules
node_modules/
public/
client/
  something-really-client-only-but-not-sure-what-it-is/
  assets/
  components/
  composables/
  layouts/
  middleware/
  pages/
  main.vue
  router.options.ts
shared/
  utils/
server/
  api/
  middleware/
  plugins/
  routes/
  utils/
nuxt.config.ts
```

But I actually prefer the current structure over this 😅


@Atinux 
> give more separation for the "app" level

could you probably give us more insights on what kind of separation for the app level you meant, and what kind of problems we're trying to solve here?

**Comment by Hebilicious** [comment]
@danielroe How about nuxt ? :D 

Reposting my thoughts from the initial discussion : 

I really like the fact that we now have `server/routes`, and `plugin` and `modules` are now clearly separated. 

I think that if we are changing the structure, we should consider more changes and bring in more benefits.

- `app` is a generic name
- There's now an additional level of nesting
- `app/router.options.ts` feels out of place
- content is not a part of nuxt/core, which other modules should be considered ?
- difference between `utils` and `composables` ?
- why not get rid of both utils and use `composables` everywhere?
- what about `app.config.ts` ? Is it deprecated ?
- why `main.vue` and not `index.vue` ?
- where would `tests` go ? That should be part of the directory structure imo
 
 Instead of `app` and `server`, I suggest `nuxt` and `nitro` ? 
 This makes things clearer imo : 
 - Explicitness of Nuxt and Nitro as TLD
 - Align standalone nitro and nuxt directory structure
 - Bootstrap the new .config directory structure proposal
 
 Here's what I'm thinking : 
 
 ```bash
 .output/
.build/
node_modules/
nuxt/
  assets/
  components/
  content/ #this should be next to pages
  composables/
  layouts/
  middleware/ 
  pages/
  plugins/
  tests/ # component tests
  index.vue # could be main.vue
nitro/
  public/ # this is more consistent with how nitro works
  api/
  middleware
  routes/
  tests/ # server only tests can go here.
  composables/ # align with vue conventions
layers/ # layers and modules could be nested under something like extends/
modules/
config/ # To align with Pooya .config proposal
  nuxt.ts 
  app.ts  # could be moved to runtime.config.public
  nuxt-router.ts
tests/ # global/integration/e2e tests can go here
nuxt.config.ts # we could support this as well
```

Minimal starter
```bash
nuxt/
  index.vue
nitro/
  public/
    favicon.ico/
.config/
	nuxt.config.ts
```

**Comment by therealokoro** [comment]
This is my current approach
![image](https://github.com/nuxt/nuxt/assets/41494675/c590e6a3-fd7b-40e7-8fde-92adc77eff0f)
![image](https://github.com/nuxt/nuxt/assets/41494675/83c798df-3a51-44e7-ab41-bef949f4c420)

As said by someone above, I feel `app` is more like an overall name, more like an alias to the word `project`.
An `app` could have the `client` and `server` side. It makes more science to me.

**Comment by wajeht** [comment]
can you include a `src` directory?

```
.
├── ./public
├── ./src/
│   ├── ./app
│   ├── ./middleware
│   └── ./server
└── nuxt.config.js
```

**Comment by Zihan-Hu** [comment]
`/app` dir is currently using by [`spaLoadingTemplate`](https://nuxt.com/docs/api/nuxt-config#spaloadingtemplate), would it be moved somewhere to avoid conflict with this issue?

**Comment by justin-schroeder** [comment]
Before I read this issue fully my gut reaction was it should be `app` because that is what first jumped into my mind, and now after reading the full issue I think `app` is still the winner because of ambiguity of the word.

Words that try to be more specific will fall short of encapsulating the full breadth of what is/can be done in the app directory. The narrowest alternative I can come up with is `vue` (this is where the vue part of the app lives after all) — but even that falls short of describing the full breadth.

I‘ll cast my vote towards `app`.

**Comment by Jamiewarb** [comment]
I do this already for all my Nuxt apps and find it really helpful. 

I use “app” as the top level name

**Comment by therealokoro** [comment]
Wonderful points by @manniL and others.

Well I don't know if this will be of any help, but here's what ChatGPT has to say 😅

![image](https://github.com/nuxt/nuxt/assets/41494675/fee5e90b-0f14-4f6e-9a32-bb0b6216940b)


Link to the chat => https://chat.openai.com/share/50d4f3aa-5f63-4a1b-99ae-13d3a69de1ce

**Comment by Saeid-Za** [comment]
Here's my take:

1. Initially, I thought about src, as I usually put everything in a src folder and create an alias in `nuxt.config` This is because there are numerous items at the root level. However, I wouldn't recommend src since the contents of plugins, server, and more are also part of our application's source. (I'm unsure about assets, though.)
2. Many suggest app, which I agree with, particularly as it has become a de facto of some sorts.
3. I also appreciate the idea of a client folder existing alongside the server folder.

That said, I believe app would be a more appealing default option.

**Comment by michalkuncio** [comment]
The "/app" directory name seems the most common, but the server directory is also part of the app, so it might be confusing at first.

What about the "/UI" directory? In the end, regardless of whether some components will be client- or server-rendered, everything in this directory will be connected to the UI and will be a part of it.

**Comment by ws-rush** [comment]
What about new ‘routes’ as alternative to ‘pages’, or maybe other option beside it, I really love remix v2 routes directory, I prefer it for big projects to work as vertical slice architecture 

I wish see it soon in nuxt

**Comment by woldtwerk** [comment]
I like it. The root became a little convoluted. This makes clearer what's server and what's client

**Comment by martinszeltins** [comment]
> We're also discussing ideas like `ui`, `web`, `frontend`, `vue`, but still feeling that `app` is frontrunner here. Other ideas welcome.

I agree that `app` sounds like the best one. Unless we split our app into multiple modules, in which case it would be strange to call each layer an app (if doing DDD) because in that case a layer is more of a module than an app.

**Comment by AymericB305** [comment]
> How about nuxt ? :D
> 

> Minimal starter
> 
> ```shell
> nuxt/
>   index.vue
> nitro/
>   public/
>     favicon.ico/
> .config/
>     nuxt.ts
> ```

@Hebilicious I liked this idea at first but, imho, it brings the same problems as calling them server/client: the "nuxt" part of your code may need nitro. I still think that "nitro" would be a good name for the server part, but I'm not sure it brings any benefits over the current name.

**Comment by Patrity** [comment]
app/ certainly has my vote. Love this proposal, I never found an issue with the structure until I saw this post though honestly.

**Comment by davestewart** [comment]
I totally agree with the app separation, but not with the `app` separation.

One of my sites is way more separated, but I keep things like middleware out of app:

![](https://pbs.twimg.com/media/GH6PvWwXAAAYTI6?format=jpg&name=medium)

However, I think the suggestion that layers should be a first class citizen is a great one, so I might suggest:

```
app/
  main.vue
base/
  public/
    favicon.ico
nuxt.config.ts
```

**Comment by shaunnbarron** [comment]
ui/
   app.vue
server/
   routes/
nuxt.config.ts

**Comment by gangsthub** [comment]
I agree with the proposed structure, but I also believe that there's the need to have shared `utils/` and, of course, `types/` between `app/` and `server/`.

I'd like to add that it would be nice if it was acknowledged from the beginning a "monorepo" structure with multiple `apps/` for large projects. Sometimes sharing things like `layers`, `content` (`types`), etc, but not necessarily, they could have their own. What do you think?

Also, since `content` is not part of "Nuxt core", you could showcase a full example with other common modules like [i18n] (https://i18n.nuxtjs.org/docs/guide/lazy-load-translations).

Thank you for your time! 🤗

**Comment by Hebilicious** [comment]
@manniL 
Thanks for replying to everyone !

For now, Nuxt and Nitro are tightly coupled, but I'd like to imagine a (distant) future where it would be possible to configure this, and use a different server engine (Laravel, Django, Elysia ...) officially through a configuration option. Since we support multiple bundlers, we could attempt multiple servers. If that ever happens maybe both Nitro and the other server would be present, so having this directory structure would remain clear.

app/router.options.ts would fit like a glove in the new .config directory, with every other configuration file.

App.vue is a great option too.

You're right with tests, it's very opinionated. We can be flexible as they will be detected anywhere anyways.

One more word regarding the relation between `nuxt` and `nitro` : Even though they are worked on by the same people, they are separated projects that lives in different repositories, with separated documentation. Having that distinction present in the directory structure makes it crystal clear.

@AymericB305 I would argue that Nuxt and Client are really different : Nuxt should be understood by all as a meta framework, SSR framework or universal framework, meaning that you can write something in /page that will be SSRd.
To me it feels like that`nuxt` would fit a directory name that could contain server code, and is a little bit more specific than `app`.

**Comment by Patrity** [comment]
> For now, Nuxt and Nitro are tightly coupled, but I'd like to imagine a (distant) future where it would be possible to configure this, and use a different server engine (Laravel, Django, Elysia ...) officially through a configuration option. Since we support multiple bundlers, we could attempt multiple servers. If that ever happens maybe both Nitro and the other server would be present, so having this directory structure would remain clear.

@Hebilicious Love this train of thought. My agency's stack is laravel + vue, but as the frontend developer, I would love the DX improvements that nuxt brings.

**Comment by ojvribeiro** [comment]
> How about nuxt ? :D

Don't we have a `.nuxt` folder already? Wouldn't it cause confusion?

**Comment by peteromano** [comment]
I personally stay away from "client/server" these days and especially not "front-end" / "backend", as these terms are getting more and more vague/ somewhat relative. 

I'm in the nuxt/nitro proposal camp if anything, although, I don't really see the value upside vs what we already have, I kinda like the flat structure, mostly to avoid having to think about exactly this discussion lol this notion feels a little like fixing something that isn't broken

A default top level base folder might not be a bad idea though for "app" or "src". Mostly just for aesthetics though, so that root repo directories don't look overwhelming/messy.

**Comment by HigherOrderLogic** [comment]
On the side note, this rfc would be equal to just changing the default `srcDir` and `serverDir`, so that people can easily revert to the original flat structure right?

**Comment by Gonzalo-Bruna** [comment]
IMO, considering that already Nuxt 3 uses the client/server nomenclature in some places, I guess that would be the correct option. Otherwise, other things such as the `ClientOnly` component would also have to be changed to whatever new nomeclature we use in V4.
This being said, I guess `app` wouldn't work well because it would feel like `server` is outside of the app, and it's not.
Therefore other good options I saw were `nuxt` (but might be confused with .nuxt), `ui` and `web`

**Comment by dargmuesli** [comment]
I'd love to see pi0's `.config` proposal implemented in v4!

**Comment by danielroe** [comment]
@dargmuesli It's already implemented!

**Comment by NicolaSpadari** [comment]
@danielroe I'm looking the nuxt docs and pi0's proposal but I can't seem to find any documentation about the config dir.
Is there a page I can check or a repo to use as example? (supported files, naming convention, etc)

**Comment by danielroe** [comment]
@NicolaSpadari We support loading Nuxt config from `.config/nuxt.ts` or `.config/nuxt.config.ts`.

**Comment by antoinerey** [comment]
@NicolaSpadari I believe what you're looking for is written here: https://github.com/pi0/config-dir. 🤗

**Comment by martinszeltins** [comment]
Since we are discussing directory structure, I would like to bring up an idea about perhaps `pages` should be called `views`. Since we are building full-stack apps now not websites. When reading the Nuxt documentation, it often describes building an `application` _(emphasis on application)_. And when reading the section about pages it says the following:

> Pages represent views for each specific route pattern.
https://nuxt.com/docs/getting-started/views#pages

I have always found it a bit odd that these "views" are called pages. Perhaps this comes from the term "webpage" or a classical website where a user browsers multiple pages. But since we are building apps with Nuxt, the term `pages` seems to be limited to the idea of a webpage. Many modern web apps looks more and more like native desktop apps and they certainly don't have pages so calling them that is a bit misleading. For example - there is no "pages" in Photoshop.

And since `Pages represent views`, why don't we call them `views`? I think views would work for both - classical web pages and modern web apps. In fact, I think pure Vue with Vue Router used to encourage to create a `views` directory for multiple routes. I wonder why Nuxt decided to call them `pages` instead.

I think this topic deserves a discussion and we should try to approach this with an open mind. Perhaps we're too used to calling them pages by now but I for one would vote for calling them `views`. What do you think?

**Comment by jits** [comment]
@martinszeltins — a quick opinion on `pages` vs `views`: I _think_ everything in the current `pages` folder is intended to be a _routable_ target? Whereas "views" could be seen to include partials (and potentially other non-routable elements), especially if coming from other frameworks like Ruby on Rails where the [`views` folder contains both routable targets and partials](https://guides.rubyonrails.org/getting_started.html#:~:text=Views%20are%20located%20in%20the%20app/views%20directory).

FWIW, I've made peace with the concept of "pages" in web apps, as I think it best describes what it is: a routable target, and also works well for SSR scenarios (where a request comes in for a path and a particular view is rendered, which can contain other views [aka componentsin Vue/Nuxt]).

**Comment by NicolaSpadari** [comment]
Ok i thought it was already implemented in nuxt for multiple config files.
I understand it's a proposal that libraries themselves have to adopt, thanks for the clarification

**Comment by 7836246** [comment]
I think it's change and not a lot of change

**Comment by becem-gharbi** [comment]
Not relevant to directory structure, I personally think that the `middleware` folder is better named in plural form like the other directories (pages, components, layouts, plugins ...).

**Comment by martinszeltins** [comment]
> I think it's change and not a lot of change

I think Middleware is just more proper English.

**Comment by mahmoudyusof** [comment]
> I'm also expecting app router like next 14 and route group. now if we need auth routes in auth folder then route become
> 
> ```
> /auth/login
> /auth/register
> ```
> 
> it will be good if
> 
> ```
> pages/
>     (auth)/
>         Login.vue
>         Register.vue
> ```
> 
> route now should be
> 
> ```
> /auth/login
> /auth/register
> ```
> 
> Only index.vue accessible in router
> 
> ```
> pages/
>     (auth)/
>         Login/
>             index.vue
>             style.css
> ```

I believe in the second scenario you wanted the paths to be:
```
/login
/register
```
as the `(auth)` directory is just for grouping purposes, I had the same request, actually, so yes that would be nice.

**Comment by hbilal9** [comment]
@mahmoudyusof exactly

**Comment by mahmoudyusof** [comment]
@hbilal9 Is there a workaround to do this now? I don't want to define an alias in each page independently.

**Comment by angelhdzmultimedia** [comment]
My 2 cents:

When we check the types for all `defineX` and `addX` (module authoring) functions like `defineNitroPlugin`, `defineNuxtRouteMiddleware`, `addServerPlugin`
we consistently find 2 types: **NuxtX** and **NitroX**.

I think that's the key🔑: 👉Rename `.nuxt` (.nuxt-output, .nuxt-generated?), and move app stuff to `nuxt` and server stuff to `nitro` inside `src`. Also add a `shared` to share types, schemas, utilities, between `nitro` and `nuxt`.
And move `modules` from `nuxt` to `src`.

Simple:
```
.config/
  nuxt.config.ts
  i18n.config.ts
  app.config.ts
.nuxt-generated/
src/
  nuxt/
    public/
      favicon.ico
    app.vue
  nitro/
    tsconfig.json
  shared/
package.json
tsconfig.json
```

Complex:
```
.config/
  nuxt.config.ts
  i18n.config.ts
  app.config.ts
.nuxt-generated/
src/
  nuxt/
    lang/
      en-US.json
      es-ES.json
    public/
      favicon.ico
    assets/
    plugins/
    middleware/
    pages/
      index.vue 
      profile.vue 
      admin-panel.vue 
    app.vue 
  nitro/
    api/
    routes/
    plugins/
    middleware/
    tsconfig.json
  modules/ (with the option to rename to features or domains)
    post/
    user/
    db/
      runtime/
        nitro/
          middleware/
            index.ts (Injects the models in the H3EventContext)
          plugins/
            index.ts (Initialize db and connect client)
    auth/
      runtime/
        pages/
          login.vue 
          register.vue 
        middleware/
          auth.guard.ts (Nuxt page middleware. "auth" in definePageMeta middleware array)
        stores/
          auth.store.ts (Pinia store)
        composables/
          auth.composable.ts
        nitro/
          api/
            login.post.ts
            register.post.ts 
            profile.get.ts 
            logout.delete.ts 
          middleware/
            auth.guard.ts 
      index.ts
  shared/
    types/
    schemas/
    utils/
 .env.dev
 .env.prod
package.json
tsconfig.json
```
(Controller/Service classes in place of Pinia stores or composables).

In my case, the whole nuxt app goes inside a `client` dir in the root of the workspace, because sometimes I work my server with other frameworks and only the frontend with nuxt in SPA mode, and server stuff goes inside `server` with that framework's own directory structure. So client and server are framework agnostic. I would delete `client/src/nitro` and `client/src/shared`, in favor of `root/shared` and `root/server` in that scenario:
```
client/
  src/
    nuxt/
server/
  src/
shared/
```

🔥👋💚 Ready for Nuxt 4, Nuxt 5, Nuxt 6, Nuxt 7, Nuxt 8. 👀 😁
Lots of health, peace, and success to the team and Nuxters™️ (contributors).

**Comment by JCtapuk** [comment]
> ## Hey all 👋🏻
> Thanks a lot for all your input and suggestions! I wanted to comment and share my personal opinion with regard to some of these here ☺️
> 
> @eunjae-lee
> 
> > In my mind, Nuxt app is a combination of vue's frontend and the backend. So seeing `app` and `server` separately makes me feel like this server is something outside this Nuxt app.
> 
> I'd say you _could_ simply take the `server` folder and run it a standalone Nitro app, yes. But of course, for SSR'ing your Nuxt `app`, Nitro is "needed", same for running Nuxt plugins on the server side. But this code is all in the `app` folder anyway. I [tried explaining that a bit ago here](https://www.youtube.com/watch?v=DkvgJa-X31k).
> 
> > But I like the server being separate as it's really server-only thing.
> 
> This exactly!
> 
> > On the other hand, `app` folder contains lots of stuff that is actually shared across frontend and backend.
> > I've moved plugins out on the same level as modules
> 
> I think moving `plugins` up isn't the way to go, as "Nuxt plugins" should stay within the Nuxt `app` while Nitro plugins belong in the `server` folder as these are two fundamentally different plugin types. ☺️
> 
> > could you probably give us more insights on what kind of separation for the app level you meant, and what kind of problems we're trying to solve here?
> 
> I am not @Atinux but separating the Nuxt app from the server helps understanding the "boundaries" between your "Nuxt/Vue" part (even if it might be SSR'ed) and the "server" part a bit more. Lots of people try using pinia or Vue composables in `/server`, which could be less tempting with the new structure from my POV.
> 
> @wajeht `app` will be treated as `srcDir` "internally".
> 
> @therealokoro `client` might suggest that the application is client-only, but as Nuxt is capable of SSR and the content in that folder will be SSR'ed, it could trip off people IMO.
> 
> @Hebilicious
> 
> > How about nuxt ?
> 
> Would that mean that Nuxt can "exist" without nitro or that Nuxt "does not include Nitro"? 🤔
> 
> > ```
> > * `app/router.options.ts` feels out of place
> > ```
> 
> Where else would you put it? 🤔
> 
> > ```
> > * difference between `utils` and `composables` ?
> > * why not get rid of both utils and use `composables` everywhere?
> > ```
> 
> The difference is a big one semantically (e.g. explained in [this video](https://www.youtube.com/watch?v=N0QrFKBZuqA)) - happy to see clear separation there.
> 
> > ```
> > * why `main.vue` and not `index.vue` ?
> > ```
> 
> The name of the "`App.vue`" replacement is still to be discussed. I personally think `App.vue` would still suit the best as `index.vue` could be confusing (as it is _not_ file-system based routing) and hard to find (when using fs-based routing you have so many `index.vue`)
> 
> > ```
> > * where would `tests` go ? That should be part of the directory structure imo
> > ```
> 
> IMO:
> 
> * Unit tests folder - nowhere, tests close to your components, `___tests__` if necessary
> * E2E-tests top-level.
> 
> > Instead of `app` and `server`, I suggest `nuxt` and `nitro` ? This makes things clearer imo :
> 
> * The more I think about it, the more I begin to like that! 🤔 Only the first question (Would that mean that Nuxt can "exist" without nitro or that Nuxt "does not include Nitro"? ) isn't resolved with that.

<root>/app/app.vue -> <root>/app/render.vue
Since it duplicates the name app, it’s not nice, I suggest changing it to render since it renders the server and the client

**Comment by davestewart** [comment]
FWIW I've been doing a lot of work with layers recently (on my 4th project with them) and there are quite a few inconsistencies and gotchas regarding path formats, core config options, auto-imports, etc, etc.

My feeling is that you want complete flexibility, get these problems with layers addressed, then it's a much improved experience for the user, likely a much-improved situation for the codebase, and effectively everything becomes a layer, whether it's one big on in the root, or any other combination you need.

**Comment by Shooteger** [comment]
To be honest, my colleagues and many friends around the globe who use Nuxt are totally fine with the current Nuxt folder structure.

Just ask yourself, what would really be the benefit implementing a possible breaking change or more "rules" which some would not follow.

The current system, where you do NOT have dozens of sub-folders is great! I know instantly where everything is. Components is clear, layers, server dir with a few sub-dirs... What would be a not a potential but a REAL benefit changing this with v4 soon?

Please correct if I am wrong, but I just don't see any really improvement by doing that, rather than more downsides and slightly bigger hurdle for new programmers getting used to this.

I would suggest focus on stability, performance and real new features, not wasting everyone's time in learning a new folder structure, while it has no overall benefits, rather than some few individual prefer it one way.

**Comment by martinszeltins** [comment]
> I would suggest focus on stability, performance and real new features, not wasting everyone's time in learning a new folder structure, while it has no overall benefits, rather than some few individual prefer it one way.

@Shooteger the folder structure will be customizable, so you won't need to learn a new structure, you will be able to use your exisitng one. It will be configurable.

**Comment by martinszeltins** [comment]
@danielroe I think you mentioned the wrong person 😅

Also, I wasn't aware of the performance issues on non-Mac OSes. Does it include Linux too? Or is Windows the only one suffering from it?

**Comment by Shooteger** [comment]
@danielroe 
Thank you for the clear statement and comment. There was absolutely no offence given. I just thought about if you would "force" the new structure it would waste time learning new (what it would with many, many people).

But as you just stated now, it is optional with automatic fallback and therefore not the case. Thank you very much and  peace 😎

**Comment by angelhdzmultimedia** [comment]
Lots of love, peace, health, and success to the amazing Nuxt team. 💚🔥👏🎉

**Comment by naranyala** [comment]
I hope the new directory structure will bring more raw performance improvements to the various existing javascript runtimes, thanks nuxt team

**Comment by dellumdeus** [comment]
Where would I place `~/types/index.ts` in this new folder structure?

**Comment by olivermaldonado** [comment]
A shared utils folder would be amazing. Would avoid all the re-exporting between server and client folders for sharing code between them.

I hope this clearer separation between client/server would address the issue that the IDE and typecheck command gets confused about what is available where. Right now the .nuxt/types are all mixed up. The IDE will not complain when mistakes happen using auto-imports from the server in client files, and viceversa, neither will typecheck. Those mistakes only blow up on runtime.

I think this was not the case before, but maybe I just noticed it recently.

Layers are amazing btw.

**Comment by serkodev** [comment]
In our monorepo, we have a Nuxt layer-only package (such as `ui`). Placing `components` and `composables` within the `app` directory feels a bit unconventional. 

I have two questions regarding this:

1. Will the current directory structure be deprecated in the future, meaning it will no longer be auto-detected?
2. For our `ui` Nuxt layer, would you recommend placing the directories in `rootDir` instead of `srcDir`? Or what would be the best practice considering the future direction of Nuxt UI?

Thank you!

**Comment by HigherOrderLogic** [comment]
> 1. Will the current directory structure be deprecated in the future, meaning it will no longer be auto-detected?

Iirc you can still change back to the original structure by changing the `dir` config.

**Comment by husayt** [comment]
> A shared utils folder would be amazing. Would avoid all the re-exporting between server and client folders for sharing code between them.
> 
> I hope this clearer separation between client/server would address the issue that the IDE and typecheck command gets confused about what is available where. Right now the .nuxt/types are all mixed up. The IDE will not complain when mistakes happen using auto-imports from the server in client files, and viceversa, neither will typecheck. Those mistakes only blow up on runtime.
> 
> I think this was not the case before, but maybe I just noticed it recently.
> 
> Layers are amazing btw.

Thanks for suggestion, this was indeed missing and now has been added in v 3.14. Thanks @danielroe

**Comment by ineshbose** [comment]
A question regarding migration:

Scenario: (say) in my Nuxt 3 project, I configure `srcDir: 'app/'` already (horrible structure, I know). This means that ~~`layers`,~~ `modules`, `server`, etc, will be in the `app/` directory (based on [Nuxt 3 docs](https://nuxt.com/docs/api/nuxt-config#srcdir)), correct? To move to the default Nuxt 4 structure, I would move the non-app directories out of `app/` back to `rootDir`, right?

If I do wish to continue with the existing structure of everything within `app/`, I would additionally need to point `dir.modules` to `app/modules/`, right?

I'm a little confused between the notion of a `srcDir` and an "app" dir. All directories are related to project source. Some directories are related to project's app source; tying `app/` as `srcDir` may be misleading me in this case, while I would expect a large project with this structure:

```ts
-| rootDir/
---| node_modules/
---| .config/
---| nuxt.config.ts
---| package.json
---| pnpm-lock.yaml
---| .husky/
---| .eslint.config.js
---| README.md
---| .gitignore
---| src/           # source directory
------| server/
------| modules/
------| content/
------| shared/
------| app/        # app directory
---------| assets/
---------| components/
---------| layouts/
---------| middleware/
---------| pages/
---------| plugins/
---------| public/
---------| store/
---------| app.config.ts
---------| app.vue
---------| error.vue
```

So the `app/` (app) directory is a supplementing separation of the `src/` (source) directory. Would my thinking be wrong?

**Comment by danielroe** [comment]
the `app/` name is the new `srcDir`. you are right in terms of how you would move your files/directories...

`srcDir` ... maybe likely now be thought of as `vueSrcDir` - we could consider renaming it with backwards compatibility at some point

**Comment by sandros94** [comment]
> `srcDir` ... maybe likely now be thought of as `vueSrcDir` - we could consider renaming it with backwards compatibility at some point

I mean... why not `appDir`? Considering that we already have `rootDir`, `serverDir`, `srcDir`?

Also, wouldn't this be a breaking change after Nuxt 4 gets released? Personally I do like the new Nuxt 4 default folder structure, but having optionally the @ineshbose suggested structure in bigger projects could be indeed useful.

**Comment by ineshbose** [comment]
> I mean... why not `appDir`? Considering that we already have `rootDir`, `serverDir`, `srcDir`?

I was also going to point out that there are some configuration/schema properties of Nuxt that could also be confusing - there's `dir.app` `dir.modules`, then `appDir` (which I missed is internal) and `modulesDir` (more for externals). We could take v4 as an opportunity to make it clearer? My thinking is

```
rootDir,
srcDir,
dir: {
  app: string | {
      pages: string
      plugins: string
      ...
      rootDir: string
  }
  modules: string
  server: string
  etc
}
_internal: { // a bit explicit about private schema props
  modulesDir,
}
```

**Comment by sandros94** [comment]
hold up, @ineshbose `rootDir` and `dir.app.rootDir`? 🤣

**Comment by ineshbose** [comment]
> hold up, @ineshbose `rootDir` and `dir.app.rootDir`? 🤣

badly named probably!

root `rootDir` is project's rootDir

dir.app as string is app/, or dir.app.rootDir would be app/ if I want to also configure, say, pages to be dir.app.pages to be routes/ for eg, so thats resolved to app/routes/

**Comment by danielroe** [comment]
> So where to start custom types for auto import? is it still in srcDir/~shared or srcDir/~app/utils ?

if it's shared with your server routes, put it in your shared folder, so `shared/types/your-file.ts`.
