### ISSUE TITLE
Hello, I did an update from 3.9.3 to 3.11 version. After updating Nuxt successfully, the dev environment is having some issues. The whole project is not responding, there are no console errors, inspect element is not working, I can't click any user interfaces, I can't also redirect to another pages. Thank you.

### ISSUE THREAD

**Issue by jmartindg** [nuxt/nuxt#26488]
Nuxt 3.9.3 to 3.11 upgrading issues

_Originally posted by @jmartindg in https://github.com/nuxt/nuxt/discussions/26403_

**Comment by mubaidr** [comment]
Did you try to recreate `node_modules` and `package-lock` file?

Please try:

```bash
npx nuxi upgrade --force
```
or
```bash
pnpm nuxt upgrade --force
```

**Comment by jmartindg** [comment]
> Did you try to recreate `node_modules` and `package-lock` file?
> 
> Please try:
> 
> ```shell
> npx nuxi upgrade --force
> ```
> 
> or
> 
> ```shell
> pnpm nuxt upgrade --force
> ```

already tried that, but it shows the same results

**Comment by mubaidr** [comment]
Then please create a reproduction to allow debug.

**Comment by jmartindg** [comment]
> Then please create a reproduction to allow debug.

I created a [Stackblitz](https://stackblitz.com/~/github.com/jmartindg/bsk-sample) for this issue. It shows the same errors, even my browser is not responding when i run npm run dev.

**Comment by mubaidr** [comment]
So, the problem is with the usage of vuetify `Menu` component. Menu expects `location` attribute to be type of [Anchor](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/util/anchor.ts#L8-L14). e.g. 'bottom', 'top' etc

But you are passing global `location` object. Which causes Vuetify to act weird.

Instad of:
```vue
<v-menu :location="location">
```
use:
```vue
<v-menu>
<v-menu location='bottom'>
<v-menu location='top'>
```

P.S. This should be reported to Vuetify Repo. Nothing to do with Nuxt/ Vue
