### ISSUE TITLE
False positive warning about calling `useRoute` within middleware

### ISSUE THREAD

**Issue by DamianGlowala** [nuxt/nuxt#26612]
### Environment

n/a

### Reproduction

https://stackblitz.com/edit/github-vmpomt?file=pages%2Findex.vue

### Describe the bug

When middleware contains `navigateTo('<url>')` to a page, which has a `$fetch` call using an interceptor, which in turn has a `useRoute` within it, a false positive warning is shown.

![image](https://github.com/nuxt/nuxt/assets/48835293/20678b50-904b-45ab-bb67-b85352614637)

**Comment by Mini-ghost** [comment]
After some attempts, it seems the error occurs on line 89 of the code below:

https://github.com/nuxt/nuxt/blob/386be0b866382caddf31eba9965a0fd5cef94d7f/packages/nuxt/src/app/composables/router.ts#L82-L92

However, the cause of the error is the `useRoute` inside `onRequestError`. It appears we cannot use `useRoute` in this place.

**Comment by Mini-ghost** [comment]
This warning occurs even if the middleware is removed. It seems the error originates from the `useRoute` inside `onRequestError`. It appears we cannot use `useRoute` in this context.

**Comment by Mini-ghost** [comment]
@danielroe 

Should we change the setting on line 89 to `false`? This is because, at that time, there was no `nuxtApp.runWithContext` due to the context. If we cannot obtain `nuxtApp` now, does that mean it's also unlikely to be within the middleware?

https://github.com/nuxt/nuxt/blob/386be0b866382caddf31eba9965a0fd5cef94d7f/packages/nuxt/src/app/composables/router.ts#L82-L92
