### ISSUE TITLE
Unable to apply custom layout with router.options.ts other than default

### ISSUE THREAD

**Issue by MrAnyx** [nuxt/nuxt#26647]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

Here is a minimal reproduction example : https://stackblitz.com/edit/github-tl6jyu

### Describe the bug

When I use the `app/router.options.ts` file to override the file-based page system to have more control over pages and urls, I can't apply any custom layout other than the default one. I could use the nested pages system from vue-router but I'm missing some layout features like the named slot which doesn't exist in nested pages.

I have renamed the `pages` folder to ensure that the default file-based pagination system is not used, but the problem persists.

Is there any configuration required to enable this in the `nuxt.config.ts` file ?

### Additional context

I may have missed something, I'm new to Nuxt 3.

**Comment by JacobGardos** [comment]
Hello @MrAnyx,

I came across your issue today and thought I might offer some assistance.

From what I gather, you've implemented [custom routing](https://nuxt.com/docs/guide/going-further/custom-routing#router-config) by creating a `app/router.options.ts` file, where you've configured `landing.vue` to serve as your homepage ('/').

However, when you try to utilize the `definePageMeta` composable to assign `layouts/custom.vue` as the layout, it seems ineffective, and the default layout continues to be used.

This behavior occurs because:

> Nuxt does not automatically apply metadata, defined through `definePageMeta` in your components, to routes generated from the routes function. To achieve this, you must use the `pages:extend` hook, which is [executed at build time](https://nuxt.com/docs/api/advanced/hooks#nuxt-hooks-build-time).

This excerpt from the Nuxt documentation clarifies that metadata specified via `definePageMeta` won't be attached to any routes you establish through custom routing. Instead, you must manually associate the metadata with your route in the `router.options.ts` file.

To specify your layout, simply use the `meta` key within your route definition, like so:

```ts
import type { RouterConfig } from '@nuxt/schema';

export default <RouterConfig>{
  routes: (_routes: any) => [
    {
      name: 'landing',
      path: '/',
      component: () => import('@/views/Landing.vue'),
      meta: {
        // Specify your meta options here, with typed suggestions available :)
        layout: 'custom',
      },
    },
  ],
};
```

I've taken the liberty of forking your minimal example and implementing the suggested changes for your review.

https://stackblitz.com/edit/github-tl6jyu-mvd9hk?file=app%2Frouter.options.ts

Please let me know if this solution works for you.

**Comment by MrAnyx** [comment]
Thank you so much @JacobGardos for this very clear explanation. Now i understand what is happening under the hood. Indeed I missed this part of the documentation.

The example you provided is clear. Thanks

Because of this misunderstanding, i migrated my application from the custom router to file based pages by with your explanation, i think i'm gonna switch back to the custom router.

**Comment by NaraTouch** [comment]
app/router.options.ts

This is working for me. I can modified /about => /about-us. 
But I still have one issue. 
How can I fetch data from my api for modified the existing route instead of using static data? 
Please help.


`import type { RouterConfig } from '@nuxt/schema';

export default {
  routes() {
    try {
      
      const existingRoutes = [
        {
          name: 'index',
          path: '/',
          component: () => import('~/pages/index.vue')
        },
        {
          name: 'index-alias',
          path: '/home',
          component: () => import('~/pages/index.vue')
        }
        {
            name: 'event',
            path: '/event',
            component: () => import('~/pages/event.vue')
        },

        {
          name: 'about',
          path: '/about',
          component: () => import('~/pages/about.vue')
        },
        {
          name: 'contact',
          path: '/contact',
          component: () => import('~/pages/contact.vue')
        }
      ];
      
      // New data that may contain updates
      const newData = [
        {
          name: "about", // existing route
          path: "/about-us", // updated path
          component: "about" // same component
        },
        {
          name: "login", // new route
          path: "/login",
          component: "login"
        }
      ];

      // Ensure the new data is an array
      if (!Array.isArray(newData)) {
        throw new Error('New data is not an array');
      }

      // Create a map for existing routes for easy lookup
      const existingRoutesMap = new Map(existingRoutes.map(route => [route.name, route]));
      
      // Update existing routes or add new ones based on new data
      newData.forEach(item => {
        existingRoutesMap.set(item.name, {
          name: item.name,
          path: item.path,
          component: () => import(`~/pages/${item.component}.vue`)
        });
      });

      // Convert the map back to an array
      const updatedRoutes = Array.from(existingRoutesMap.values());

      // Return the updated routes
      return updatedRoutes;
    } catch (error) {
      console.error('Error fetching routes:', error);
      return []; // Ensure this returns an array
    }
  },
} satisfies RouterConfig;`
