### ISSUE TITLE
Failed CSS preloads shouldn't throw errors

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt/nuxt#26972]
### Describe the feature

Currently in Nuxt 3 if a browser cannot load a CSS file that's loaded via JS it throws an error and the error page is shown.

`Error Unable to preload CSS for https://realtruck.com/_nuxt/index-CtQoRL55.css`

![image](https://github.com/nuxt/nuxt/assets/2112282/9e9070eb-605b-499e-8315-397fda7a4aa1)

This page has a scoped style that's included in the page.
![image](https://github.com/nuxt/nuxt/assets/2112282/801b268b-16c3-4736-b4d6-8d81a9456927)

I don't know if this issue is just for page CSS files or what, but I can say that failure to load CSS files should not throw errors.  The browser is able to render a page with missing assets (CSS, images, etc..) this should be no different.

**Rendering a page, even with some CSS missing is better than showing the error page.**

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by hecktarzuli** [comment]
Stackblitz doesn't seem to trigger the error page quite like our project, but I was able to reproduce a very basic POC using 1 known method to trigger the error.  (importing a CSS file into a component/page)

https://stackblitz.com/edit/github-wg3yu6-s33o9j

**Comment by alessioacella** [comment]
Same here

**Comment by falfituri** [comment]
Same here!

**Comment by yashwp** [comment]
Same error
![image](https://github.com/nuxt/nuxt/assets/13454790/9cb50de3-3be7-4baa-99c0-11d0e33a7cee)

**Comment by RamaHerbin** [comment]
same!

**Comment by andrei-nikic-co** [comment]
We have the same issue - "Unable to preload CSS ...". I can confirm that it's completely random, we haven't found a pattern for this issue too. The issue just disappears in a short period of time. We host the app on Vercel.

**Comment by ifbasit** [comment]
Facing the same issue, is anyone able to resolve it? 

<img width="1440" alt="Screenshot 2024-07-11 at 11 01 04 PM" src="https://github.com/nuxt/nuxt/assets/49987142/e99b3fcc-7a87-405d-a5c1-a0989df6c3d9">

**Comment by alireza2281** [comment]
having the same issue randomly to very little visitors and by the way i've got the error on importing sweet alert css in some pages
```
Error: Unable to preload CSS for /_nuxt/sweetalert2.CHx7238T.css at HTMLLinkElement.<anonymous>
 ```

**Comment by usrrname** [comment]
Same

**Comment by alessioacella** [comment]
I'm encountering a recurring issue with JSON files after performing a static build and using the local Nitro preview server. In addition to the blocking CSS error described in this issue, we often face the following error:

"Failed to import ... /builds/ meta .json file."

This problem arises every time we release a new build. Occasionally, it completely blocks progress, and sometimes it doesn't, but it definitely needs urgent investigation.

(Using nginx as proxy, ssr: false, nitro as default node server, latest nuxt3 build)

**Comment by Object905** [comment]
Same here. First thought that It's happening because of updates to the app (when user tries to load css/hs by hashed name of previous version), but since then migrated to cdn+s3, that keeps previous version static files and uploads before deploying new version, but this issue is still present.

**Comment by gergo-tar** [comment]
Same here. With cloudflare cdn
![image](https://github.com/user-attachments/assets/80c9c155-0afb-4d3f-86d4-f26fc2a72122)

**Comment by oaleynik** [comment]
We don't use Nuxt per se in our project, but we do use Vite + Vue3. This issue also appears a lot in Sentry logs.

**Comment by oaleynik** [comment]
Ok, I think there was a solution implemented: https://github.com/vitejs/vite/pull/12084. I will give it a try. Apologies for the noise.

**Comment by vhovorun** [comment]
+1 with css issue

**Comment by peralta** [comment]
I am unable to reproduce the issue, although some external crawlers are triggering the error on my site. Searching for `Unable to preload CSS _nuxt` on Google shows a few sites that are also impacted by the error as Googlebot crawls them.

**Comment by danielroe** [comment]
I would love to look into this but I do need a reproduction 🙏

**Comment by masylum** [comment]
have you fixed it already? I haven't seen this until today sorry. I have several fetchers, a basic http one (using https://github.com/sindresorhus/got) and a headless chrome one. The headless chrome one is built with pupeetteer and it cancels css requests:

 ```js
 const ABORT_TYPES = new Set(['image', 'stylesheet', 'font'])
await page.setRequestInterception(true)

page.on('request', (req: any) => {
  if (req.isInterceptResolutionHandled()) return
  const resourceType = req.resourceType()

  if (ABORT_TYPES.has(resourceType)) {
    return req.abort('blockedbyclient')
  }
  return req.continue()
})
await page.goto(url, { waitUntil: 'networkidle2' })

const html = await page.content()
```

**Comment by peralta** [comment]
Hey @masylum, thanks for providing details. I have not been able to validate the fix, although it is now released on nuxt v3.12.2 (I will be able to validate it once v3.12.3 is out). In any case, thank you for providing the details.

**Comment by vedmant** [comment]
It looks like this error appears when new app version is deployed and client didn't refresh the page, so when client navigates to next page it's trying to load CSS from the old build, which is not present anymore. I think it should be some function to detect new build and make a full refresh instead of throwing errors.

**Comment by clmrb** [comment]
> > It looks like this error appears when new app version is deployed and client didn't refresh the page, so when client navigates to next page it's trying to load CSS from the old build, which is not present anymore. I think it should be some function to detect new build and make a full refresh instead of throwing errors.
> 
> Exactly ! Got the same issue on a vue + capacitor app, will see if this is fixed by a `location.reload()` on the next release. Also this seems to happen only on iOS/macOS 🤔 Might have something to do with how each app stores update assets though.
> 
> Update: We use sentry as well, app was updated this week and we had 3k+ errors about css or js assets loading (this version has the reload feature but won't take effect until next update)
> 
> ![Image](https://github.com/user-attachments/assets/f066919a-6998-44a5-a349-54af744aec48)

Little update: it did somehow reduce errors in sentry but not entirely because sentry SDK can send the errors before the page fully reloads

However I did figure out that it's probably a cache issue on index.html.

index.html > new version > loading cached index.html > trying to load old-hash1234.(js|css) > not found > vite fetch error

I'll try to disable cache on index.html (nginx, apache...) for webapps but for cross-platform apps there might be a setting to force the webview to avoid or invalidate index.html cache

**Comment by albinbicaj** [comment]
**Fixed by combining three things:**

1. **Root cause**: `index.html` was being cached, so returning users kept referencing old asset hashes that no longer existed after a new deploy → `vite:preloadError` (CSS/JS chunk 404).

2. **Prevent it**: Set `Cache-Control: no-store, must-revalidate` on `index.html` only (hashed `/assets/*` files stay `immutable` — they're safe to cache forever since the filename changes on content change). Also kept previous deploy's assets around for a 14-day grace window so even a stale cached `index.html` still resolves.

3. **Self-heal what still slips through**: Listened for the `vite:preloadError` event and auto-reload the page (no user action needed — app state is already persisted to sessionStorage so nothing is lost). Also added proactive polling of a small `version.json` file so drift gets caught even without a failed import.

4. **For the couple of pages where a failure would be worst** (landing page + success page — small, ~4KB each): switched from `loadable(() => import(...))` to a plain static `import` in the entry bundle, so there's no separate lazy chunk that can 404 for those specific routes at all. Left the bigger, less critical pages lazy-loaded since eager-bundling them wasn't worth the size cost — the reload mechanism already covers those.
