### ISSUE TITLE
getCachedData causing repeated requests

### ISSUE THREAD

**Issue by dextersiah** [nuxt/nuxt#27200]
### Environment

- Operating System: Darwin
- Node Version:     v20.11.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      app, devtools, experimental, typescript, modules, css, runtimeConfig, components, googleFonts, i18n, alias, nitro, build
- Runtime Modules:  @pinia/nuxt@0.4.11, @nuxtjs/tailwindcss@6.12.0, @nuxtjs/google-fonts@3.2.0, @nuxt/image@1.5.0, @vueuse/nuxt@10.9.0, @nuxtjs/i18n@8.3.0, dayjs-nuxt@2.1.9
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-fu2dhl?file=composables%2FapiFetch.ts

### Describe the bug

I've created a composable around `useFetch` to simplify the usage of `getCachedData`. However I've noticed that there was a repeated request sent if  getCachedData is passed as the options for `useFetch`. 

If the getCachedData is not passed as an option, the request is only sent once. 

### Additional context

I initially stumble upon this bug after noticing that a weird behavior whereby if i refresh the page it would display my data as usual and the data request is fetched on the client once again causing a flicker when using v-if / v-else

### Logs

```shell-script
------------------
With getCachedData
------------------

hit apiFetch
Cache disabled || invalidateCache /api/test false false
Cache disabled || invalidateCache /api/test false false
Cache disabled || invalidateCache /api/test false false
hit server api
hit apiFetch
Cache disabled || invalidateCache /api/test false false
Cache disabled || invalidateCache /api/test false false
Cache disabled || invalidateCache /api/test false false
hit server api
hit server api


---------------------
Without getCachedData
---------------------
hit apiFetch
hit server api
```

**Comment by huang-julien** [comment]
Hey :wave: I see that there's some hydration issues in your reproduction. Can you try fix it ?

**Comment by dextersiah** [comment]
> Hey 👋 Thanks for the reproduction. I see that there's some hydration issues in it. Can you try fix it ?

Hey @huang-julien I've fixed the hydration issue. Forgot to wrap the content in a single root element

**Comment by Martichou** [comment]
Any update planned on this one? Also getting the same behavior. 
The inside of getCachedData get called 4 times which is pretty sad :( 

@dextersiah you found any workaround or something?

**Comment by Martichou** [comment]
I've debugged a bit more and seems like the issue is caused by https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/app/composables/asyncData.ts#L243 which calls the `getCachedData` function.

Also I don't understand why they don't store the result of the first call to `getCachedData` and use it instead afterwards.

```ts
    // Avoid fetching same key that is already fetched
    if ((opts._initial || (nuxtApp.isHydrating && opts._initial !== false)) && hasCachedData()) {
      return Promise.resolve(options.getCachedData!(key, nuxtApp))
    }
```
Like in the above, you first call `hasCachedData` which calls the `getCachedData` and then you call the `getCachedData` again a second time? 

Seems like this was added by https://github.com/nuxt/nuxt/commit/b52548d915426629a493b3e9a28a0a606e8e3843 but doesn't explain the reasonning for fetching that many times.

Am I just stupid or can this all be the root cause of this issue?
