### ISSUE TITLE
Img @error not working

### ISSUE THREAD

**Issue by samedkucuk** [nuxt/nuxt#27390]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-qxufaf?file=app.vue

### Describe the bug

Img @error not working

**Comment by danielroe** [comment]
The reason is that the `error` event occurs before Vue hydrates the page. This is not a bug. You can use `onerror` but you must write pure JS to handle the error.

In nuxt/image we add a data-attribute if there is an error and then handle this subsequently. See https://github.com/nuxt/image/blob/main/src/runtime/components/nuxt-img.ts#L153.
