### ISSUE TITLE
useAsyncData unexpected behaviour when callback return falsy value

### ISSUE THREAD

**Issue by VladStepanov** [nuxt/nuxt#27594]
### Environment

- Operating System: Darwin
- Node Version:     v20.2.0
- Nuxt Version:     3.12.1
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  pnpm@9.3.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

[Codesandbox link](https://codesandbox.io/p/devbox/asyncdata-deduplication-bug-2ywm5w?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxdgf65800073b6jeonz2s2q%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxdgf65800023b6j09sj83ci%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxdgf65800043b6jiezwwyiw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxdgf65800063b6ju6e6pzsm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxdgf65800023b6j09sj83ci%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxdgf65700013b6jbkfgrlj5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxdgf65800023b6j09sj83ci%2522%252C%2522activeTabId%2522%253A%2522clxdgf65700013b6jbkfgrlj5%2522%257D%252C%2522clxdgf65800063b6ju6e6pzsm%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxdgf65800053b6j3f7t5aal%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxdgf65800063b6ju6e6pzsm%2522%252C%2522activeTabId%2522%253A%2522clxdgf65800053b6j3f7t5aal%2522%257D%252C%2522clxdgf65800043b6jiezwwyiw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxdgf65800033b6jovogrjn0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clxdgf65800043b6jiezwwyiw%2522%252C%2522activeTabId%2522%253A%2522clxdgf65800033b6jovogrjn0%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

- reload page
- view server logs, `callback log` message should be printed
- view client logs, `callback log` message should not be printed, but it is printed

### Describe the bug

When useAsyncData callback returns any falsy value(undefined, null, 0, false) that causes callback to execute both server and client side when only server side is expected

**Comment by danielroe** [comment]
Why are you not returning something from useAsyncData?

**Comment by VladStepanov** [comment]
> Why are you not returning something from useAsyncData?

It is a liitle bit non documentation way.  
Anyway this behaviour is unexpected

**Comment by danielroe** [comment]
This is [documented](https://nuxt.com/docs/api/composables/use-async-data#params) and expected behaviour:

![CleanShot 2024-06-13 at 18 01 27@2x](https://github.com/nuxt/nuxt/assets/28706372/2ecd5bed-0e69-4461-aeb9-d436f136e764)

You (I suspect) are relying on useAsyncData to dispatch a side-effect like calling a pinia action. You shouldn't do that. useAsyncData is not guaranteed to _execute_ the function on transitioning to the page. It might be extracted at build/generate time, for example. Or perhaps run in advance _before_ navigating to another page.

**Comment by VladStepanov** [comment]
@danielroe thanks for clarification!
Maybe it's better to raise an exception or log a warning if undefined value returned? Because this behaviour is not obvious

**Comment by danielroe** [comment]
Agreed! We could log a warning in dev mode? I think we might also consider updating types to exclude false return values.

**Comment by kalnode** [comment]
> Why are you not returning something from useAsyncData?

Here's one context: I'm using the same page for both (A) creation and (B) editing of a post and I don't want to abstract further. The page uses `useAsyncData`.

For Context B, a post id already exists and there's something to pull from the API. I want SSR and I already use `useAsyncData` everywhere else in my app, so want to keep that pattern.

For Context A, no post id exists yet and no SSR is needed, but `useAsyncData` (see B above) is there and getting triggered on page load. Within `useAsyncData` Nuxt warns that I must return something (truthy value), but there'll never be anything to return so I return string 'none' just to appease warnings. Rest of the page cascades as normal.

One could say "Ok, separate the data pulling from the page" but then I would I have multiple files and more things to manage.

**Comment by xak2000** [comment]
@danielroe

> Why are you not returning something from useAsyncData?

I believe the example of @kalnode is good enough.

I have a similar case. So, I created a composable to load data by `groupId`, where `groupId` can be `null` because it is an optional query parameter and the component is totally valid even when this `groupId` is not defined, in which case the composable will just return `null` instead of calling the API.

```ts
export async function useFetchGroup(groupId: MaybeRefOrGetter<string | null>) {
  return await useAsyncData(
    () => `/api/groups/${toValue(groupId)}`,
    async () => {
      const groupIdValue = toValue(groupId)
      if (groupIdValue != null) {
        return $fetch(`/api/groups/${groupIdValue}`, {
          headers: useApiRequestHeaders(),
        })
      } else {
        return Promise.resolve(null)
      }
    },
  )
}
```

What should I return from the composable if not `null` or `undefined` in this case?

One workaround would be to return a custom "null value" such as string `'nope'`? But then every caller of my composable should know about some magic return value that it should check for. I don't think this is a good solition. `null` is already well-known value for cases like this.

Honestly, I believe even `undefined` should be allowed. It is the job of `useAsyncData` to distinguish between the `null`/`undefined` returned by the `handler` and a situation when handler was never called (if this is the reason why "the request may be duplicated on the client side" restriction exists). The framework should not assume if/why anyone would need to return any possible value from a data-loading function and should not restrict it. Especially for such generic-purpose composable as `useAsyncData`, which is basically a building block for any SSR-friendly data loading (not even necessarily from a server).
