### ISSUE TITLE
Route query is not updating

### ISSUE THREAD

**Issue by ElYaiko** [nuxt/nuxt#27656]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-vcfhxz?file=app.vue

### Describe the bug

When using `NuxtLayout > NuxtPage` and updating the route query and redirecting to a new page the new query set (a: 'new') is not detected, however this works well when not using a NuxtLayout.

**Comment by martinszeltins** [comment]
Maybe it's just me but I don't understand the issue. What exactly is meant by `the new query set (a: 'new') is not detected`? What is the expected behavior? What should I see?

This is what I see:
![image](https://github.com/nuxt/nuxt/assets/34019878/45922742-1870-45ad-9f3a-ab5b8c19117b)

**Comment by FlorianWerndl** [comment]
Hi @ElYaiko. I've updated the reproduction to make it work: https://stackblitz.com/edit/github-vcfhxz-wgd28u
It btw. is recommended to use `navigateTo` instead of `router.replace` / `router.push`

**Comment by danielroe** [comment]
The reason is that your component is _outside_ the page component, and you are not accessing the route in a reactive way (the route value updates as soon as the page component has loaded fully).

See this example: https://stackblitz.com/edit/github-vcfhxz-thv9pi?file=components/test.vue.

Let's track in https://github.com/nuxt/nuxt/issues/21340.
