### ISSUE TITLE
Runtime Crash When Passing `to.matched` from Middleware to `router.resolve` Without Error Message

### ISSUE THREAD

**Issue by Rock070** [nuxt/nuxt#27717]
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-xswdtj?file=pages%2Fproducts%2F%5Bproduct%5D%2Fbuy.vue

### Describe the bug

In the example, I can navigate to the non-dynamic route `/about` without any issues, but I am unable to access the dynamic `/products/apple/buy page.`

When using to.matched from middleware as a parameter for `router.resolve`, the type check passes, but it crashes at runtime without any error message. This seems to occur when registering dynamic routes. However, when wrapped in a try-catch block, the following error message is displayed:

```sh
Error: Missing required param "product"
    at Object.stringify (vue-router.js:891:21)
    at Object.resolve (vue-router.js:1225:22)
    at Object.resolve (vue-router.js:2360:34)
    at test.global.ts:8:26
    at Array.some (<anonymous>)
    at test.global.ts:4:14
    at router.js:153:61
    at fn (nuxt.js:182:44)
    at Object.runWithContext (chunk-6LRXACK2.js:5421:18)
    at callWithNuxt (nuxt.js:187:24)
```

**Comment by Mini-ghost** [comment]
Your issue occurs when navigating from page A to page B (dynamic routing). However, if we directly enter page B, we won't encounter this error.

This might be caused by vue-router.

We can see more details here: https://github.com/vuejs/router/blob/249bf2da5382758fc55a6690c4179a63313f0f24/packages/router/src/router.ts#L440

The `resolve` function in vue-router requires the current route information when it runs. When we directly enter page B, `currentRoute.value` is the same as the `to` route we receive, so there is no issue with missing `params`. However, when navigating from page A to page B, `currentRoute.value` is still the original page when the middleware runs, causing the missing `params` error.

Therefore, we can also pass `currentLocation` to `resolve`. Just do this in your global middleware, and it should work correctly:

```ts
export default defineNuxtRouteMiddleware((to) => {
  const nuxt = useNuxtApp();
  const router = nuxt.$router;
  to.matched.some((route) => {
    const routeTo = router.resolve(route, to);
    return routeTo.path === 'products-apple';
  });
});
```

**Comment by danielroe** [comment]
Yes, I think this is a vue-router issue and should be reproducible without Nuxt.

Let me know if not and I'll reopen!
