### ISSUE TITLE
Enabling compatibilityVersion: 4 not working as expected when using layers

### ISSUE THREAD

**Issue by ananthachetan** [nuxt/nuxt#27904]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.13.1`
- Nuxt Version:     `3.12.2`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.6`
- Package Manager:  `pnpm@9.4.0`
- Builder:          `-`
- User Config:      `alias`, `app`, `components`, `css`, `extends`, `future`, `imports`, `devServer`, `runtimeConfig`, `pinia`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-nuxt-4-layers-compat-issue

### Describe the bug

Steps to reproduce the issue:

1.  Configure a project with layers.
2. Enable compatibilityVersion: 4 in the base layer. 
3. Move to the new project structure defined in the documentation in both the base layer and the repo extending it.
4. Start the server and observe it running with compatibility version 4.
5. Observe that the app.vue file is not loaded at all from the extended layer.

Expectation:
The nuxt.config.ts configuration defined in the base layer will be merged with the nuxt.config.ts of the repo extending it.

Observation:
The compatibilityVersion: 4 property is not honoured in the repo extending the base layer.

Workaround:
Explicitly set the property in the nuxt.config.ts of the repo extending the base layer to get it working.
`    future: {
        compatibilityVersion: 4,
    },`

**Comment by danielroe** [comment]
For now, you need to define the compatibility version in each layer that opts into the new structure.

This will obviously not be required after upgrading to v4.

**Comment by bernhardberger** [comment]
> For now, you need to define the compatibility version in each layer that opts into the new structure.
> 
> This will obviously not be required after upgrading to v4.

It would be nice if that was documented for now.. I've been trying to get answers to this in this GitHub, in the nuxt Discord channel and even in the comments of your core team members' YT Videos talking about Nixt compatibility 4 - to no avail.

It needed a random rant post on reddit and someone mentioning this ticket to find any information on the effect of layers to compatibility mode.

This info should come straight from docs imo.

**Comment by manniL** [comment]
@bernhardberger 💯, docs would be extremely helpful there! PR welcome! 🙌

**Comment by bernhardberger** [comment]
@manniL I'd happily submit a docs PR if I knew the actual side effects of not opting in in every layer.

I have a project that has **local** layers. In those layers, I didn't opt-in into the compatibility mode and didn'tchange the dir structure, only in nuxt.config.ts of the main project extending those layers.

However, I don't see any actual breakage like mentioned in this issue. 

I'm just not sure if I now reap the benefits or not - no clue whatsoever. I have no errors, but the project is sluggish as hell, especially in dev-server and sometimes typescript and IDE completion acts up. No clue tho if that's related.

Does the whole project fall back to v3 compatibility if you have a mixed setup? Why is this even working in my case? I think that auto-fallback without breakage or at least some kind of build warnings, whilst meant well, is more confusing than not.

I've been trying to figure out which mode I'm in since I migrated (or how it now turns out, probably didn't really migrate..?) to v4 compat structure.

Imho, it should at least spit a warning during build/dev that it's auto-falling back to v3 mode when opting in to v4 compat mode.

I can submit a PR adding a hint to the docs that one needs to opt in in every layer and project extending those layers as well as migrate the file structure in every layer but I don't thkng that's enough info and I'd rather not do that when I don't understand the side-effects of not opting in and without knowing why in my case it doesn't completely fall apart.

**Comment by manniL** [comment]
(re-opening as it should be documented)

**Comment by dschreij** [comment]
@bernhardberger 

>I'm just not sure if I now reap the benefits or not - no clue whatsoever. I have no errors, but the project is sluggish as hell, especially in dev-server and sometimes typescript and IDE completion acts up. No clue tho if that's related.

We had the same problem. The sluggishness in our case was caused by a nested folder structure. We had our base layer placed in the `~/layers/base` folder and did a `pnpm install` there. With the `node_modules` folder present, everything became slow, resource intensive, etc. After we deleted the node_modules folder we noticed a large performance increase.

We now opted to not use the ~layers/.... way but use a monorepo structure instead. Where each layer has its own folder in a `packages/` dir, and heave never looked back since.
