### ISSUE TITLE
[nuxt] `useId` might not work correctly with components that have `inheritAttrs: false`.

### ISSUE THREAD

**Issue by nethriis** [nuxt/nuxt#27910]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v20.10.0`
- Nuxt Version:     `3.12.2`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.6`
- Package Manager:  `pnpm@9.4.0`
- Builder:          -
- User Config:      `devtools, css, modules, tailwindcss, fonts`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.12.0, @nuxt/fonts@0.7.1, @nuxt/icon@1.0.0, nuxt-headlessui@1.2.0`
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-i7frha?file=pages%2Findex.vue

### Describe the bug

When using `provideHeadlessUseId(() => useId())` in the `app.vue` file I got the following warning:
```
[nuxt] `useId` might not work correctly with components that have `inheritAttrs: false`.
```

**Comment by danielroe** [comment]
This is a fair warning - when `useId` from Nuxt is used, if it is called in component, it needs to be used with a component with a single root node in order to ensure a stable id between server + client (as it encodes the id in the attributes of the node).

I can't say whether this works fine with how headless ui is using it, but I don't see any hydration errors, so you might be fine to ignore the warning.

Regardless, I don't think it's a Nuxt bug - we're just warning about a possible misuse of the composable;

**Comment by nethriis** [comment]
Ok, thanks for the explaination
