### ISSUE TITLE
404 error after running `npx nuxi generate` with `app.baseURL` set.

### ISSUE THREAD

**Issue by khopha** [nuxt/nuxt#27923]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, app
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-zk6sfo

Steps:
1. Set `app.baseURL` in nuxt.config.ts.
2. Run `npx nuxi generate`.
3. Run `npm run preview`.
4. Click the links in the generated HTML.

### Describe the bug

The links in the generated HTML navigate to a 404 error. After removing **base** from the URL, it works correctly. For example, **localhost/base/about** results in a 404 error, whereas **localhost/about** is correct.

I'm wondering if the issue might be with the `npm run preview` command not being able to set the baseURL.

**Comment by s-en-o** [comment]
@khopha  If you want to change the application base url, you should have a folder matching the name of what you set on on `baseURL` and put the pages in that folder.

I have attached a screenshot example below from your code:
![image](https://github.com/nuxt/nuxt/assets/4535187/72820601-7186-41e4-8ed6-6ddc1a2fd4d6)

**Comment by khopha** [comment]
> @khopha If you want to change the application base url, you should have a folder matching the name of what you set on on `baseURL` and put the pages in that folder.
> 
> I have attached a screenshot example below from your code: ![image](https://private-user-images.githubusercontent.com/4535187/344501506-72820601-7186-41e4-8ed6-6ddc1a2fd4d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MDY4MTUsIm5iZiI6MTcxOTgwNjUxNSwicGF0aCI6Ii80NTM1MTg3LzM0NDUwMTUwNi03MjgyMDYwMS03MTg2LTQxZTQtOGVkNi02ZGRjMWEyZmQ0ZDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDFUMDQwMTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTllNDVkZDVjYmRlNjA4OWY2MzQwODM2NjY5YzAwMTY4MTIyOTNlNWMwYzI1NDk0Zjg3Yzc4OGM1NTYzY2I1ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hZQhFUFJFncOqyAglEIgW9SPWNGBjIAI2eGBiJ6g-BM)

@s-en-o 
I tried what you suggested above, but it didn't work. As you can see in your screenshot, it is showing the default Nuxt page, not the page I created (pages/index.vue, pages/about.vue). I think the pages directory shouldn't be inside a custom directory like that.

**Comment by danielroe** [comment]
I think it's more that when _serving_ the generated pages you should make sure that the server uses that baseURL - so you could copy `.output/public` to `.output/public/mybaseurl` and then run `npx serve .output/public` and access `/mybaseurl`.

Nuxt assumes you're not going to use `serve` to serve your static files, and that you're likely going to copy them somewhere else that's accessible from your `/mybaseurl`.

However, I do think there might be merit in generating a directory inside `.output/public` with the name of your baseURL - and at a minimum, improving the previewing of a static build so that it works. Both of these are upstream nitro issues however, so would you raise an issue upstream at https://github.com/unjs/nitro, and I'll follow-up there? 🙏

**Comment by danielroe** [comment]
Thank you. Let's track in https://github.com/unjs/nitro/issues/2580.
