### ISSUE TITLE
Lighthouse report with a very long "Render Delay" time.

### ISSUE THREAD

**Issue by willgan916** [nuxt/nuxt#28036]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.18.2
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      devtools, compatibilityDate
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

1. create a new project: npx nuxi@latest init nuxt_test
2. start the project by "npm run dev"
3. Open the project at Chrome and run lighthouse and select "Device" with "Mobile"

### Describe the bug

In Performance item, the "Largest Contentful Paint" is very large with a very long "Render Delay" time.

![无标题](https://github.com/nuxt/nuxt/assets/39150342/4414a007-e458-4a1c-850f-1861657d1b66)

**Comment by manniL** [comment]
Please avoid benchmarking/testing in dev mode as it will not yield to realistic results ☺️

**Comment by willgan916** [comment]
After I pack the project as SSG and put it on the server, the same issue exits.

**Comment by willgan916** [comment]
After I pack the project as SSG and put it on the server, the same issue exits on the mobile. However on the desktop, everythins is OK.

**Comment by julisch94** [comment]
I'm sorry to add another reply to this closed thread but I'm having the same issue and I'm on production build.
I've run `npm run build` and I've deployed my page to Netlify. https://club-live-band.netlify.app/

I used to have an almost perfect rating using a common Vue application but I'm in the process of migrating because I was hoping to improve my stats even more. However, they have become worse. Any idea how I can tackle this? 😇  
<img width="742" alt="image" src="https://github.com/user-attachments/assets/a183711a-eda8-41ed-b72a-127a6b7a736a">

**Comment by dencs08** [comment]
Same for me, fresh nuxt 3 project, doesn't matter if on dev, build or deployed on the server, render delay seems to spike up even on a fresh nuxt [v3.14.159](https://github.com/nuxt/nuxt/releases/tag/v3.14.159) project.

**Comment by udrzbarik** [comment]
@TheAlexLichter hello, is there any answer to how to approach this?

**Comment by AlexChelan** [comment]
I still have this issue on the latest nuxt version
