### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by Sorio6** [nuxt/nuxt#28132]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      compatibilityDate, devtools, modules, ui, nitro
- Runtime Modules:  @nuxt/ui@2.17.0, @nuxtjs/supabase@1.3.4
- Build Modules:    -
------------------------------

### Reproduction

-

### Describe the bug

I added the `@iconify/json` package to my project and when I restarted it, this error message appeared:
```
<--- Last few GCs --->

[18388:000002B5D25FA330]    71699 ms: Scavenge 2043.2 (2083.2) -> 2041.6 (2083.2) MB, 5.03 / 0.00 ms  (average mu = 0.308, current mu = 0.286) allocation failure; 
[18388:000002B5D25FA330]    71708 ms: Scavenge 2043.4 (2083.2) -> 2041.7 (2083.7) MB, 4.58 / 0.00 ms  (average mu = 0.308, current mu = 0.286) allocation failure; 
[18388:000002B5D25FA330]    71715 ms: Scavenge 2043.5 (2083.7) -> 2041.8 (2087.7) MB, 3.76 / 0.00 ms  (average mu = 0.308, current mu = 0.286) allocation failure; 


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6362C436F node::SetCppgcReference+15695
 2: 00007FF63623C686 EVP_MD_meth_get_input_blocksize+76102
 3: 00007FF63623E471 EVP_MD_meth_get_input_blocksize+83761
 4: 00007FF636CAB281 v8::Isolate::ReportExternalAllocationLimitReached+65
 5: 00007FF636C94A18 v8::Function::Experimental_IsNopFunction+1336
 6: 00007FF636AF60A0 v8::Platform::SystemClockTimeMillis+659696
 7: 00007FF636B02323 v8::Platform::SystemClockTimeMillis+709491
 8: 00007FF636AFFC84 v8::Platform::SystemClockTimeMillis+699604
 9: 00007FF636AF2DC0 v8::Platform::SystemClockTimeMillis+646672
10: 00007FF636AFAA4A v8::Platform::SystemClockTimeMillis+678554
11: 00007FF636B4C5DE v8::Locker::IsLocked+6366
12: 00007FF6367D9166 v8::CodeEvent::GetFunctionName+122774
13: 00007FF5D6D1AAFA

 ERROR  [unhandledRejection] read ECONNRESET                                                                                  12:15:44 PM  

  at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
```

**Comment by lustremedia** [comment]
What happens if you remove the @iconify/json package?

Did you google the error message?
I don't think this is a nuxt issue?
Further how much ram do you have?
What Node Version are you running etc etc?

Google says for example: 
_Most times when you face this error it’s probably because of a memory leak, an addition/version upgrade of a library or a difference in how Node.js manages memory between versions (e.g. Node.js version <= 10 and Node.js version > 10)._

**Comment by Sorio6** [comment]
When I removed the `@iconify/json` package. My project run normally. If I reinstall it, it bug again.

console.log(process.memoryUsage()); give this without the `@iconify/json`  :
```
{ rss: 537538560,
  heapTotal: 63926272,
  heapUsed: 38108920,
  external: 6816901,
  arrayBuffers: 537161 }

  heapUsed: 38108920,
  external: 6816901,
  arrayBuffers: 537161 }
```

If  I delete node_modules folder and rebuild the project, I have the same error.

How can I install the `@iconify/json` package without bugging my project?

**Comment by lustremedia** [comment]
So the problem seems to be with iconify/json not with nuxt ... how do you include it into your project? or do you just install it and the project fails? Try to set the node memory limit higher tha  default. Check the websites I posted in my last comment, and read throught it.Again, I dont think it is a nuxt issue rather than a node issue.
-------- Original message --------From: Sorio6 ***@***.***> Date: 7/13/24  14:16  (GMT+01:00) To: nuxt/nuxt ***@***.***> Cc: Tuvia ***@***.***>, Comment ***@***.***> Subject: Re: [nuxt/nuxt] FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory (Issue #28132) 
When I removed the @iconify/json package. My project run normally. If I reinstall it, it bug again.
console.log(process.memoryUsage()); give this without the @iconify/json  :
{ rss: 537538560,
  heapTotal: 63926272,
  heapUsed: 38108920,
  external: 6816901,
  arrayBuffers: 537161 }

  heapUsed: 38108920,
  external: 6816901,
  arrayBuffers: 537161 }

If  I delete node_modules folder and rebuild the project, I have the same error.
How can I install the @iconify/json package without bugging my project?

**Comment by Sorio6** [comment]
I solved this error by recreating a new project and copying and pasting each of my files/folders. I installed the iconify/is package and it now works.

**Comment by GerryWilko** [comment]
I also ran into this issue when using Nuxt Icon and the following [`@iconify-json/fluent`](https://icon-sets.iconify.design/fluent/) library.

This is a very large icon library and it seems memory usage grows when in the prerenderer during build. In my case I am only using one icon from this Fluent library but presumably it is having to load the whole library to load this one icon?

If I just let this icon get loaded at runtime by Nuxt icon all is well but then you get the Nuxt icon warnings in the console.
