### ISSUE TITLE
Scroll behavior Bug introduced wit PR 28083

### ISSUE THREAD

**Issue by misurito** [nuxt/nuxt#28306]
@danielroe @boogie-ben Pull Request https://github.com/nuxt/nuxt/pull/28083 introduces a bug. 
`Number.parseFloat('auto')` ( valid syntax for `getComputedStyle(elem)` padding/margin ) will amount to **NAN**

### Reproduction
N/A

_Originally posted by @misurito in https://github.com/nuxt/nuxt/issues/28083#issuecomment-2248868657_

**Comment by misurito** [comment]
### Reproduction
Not sure if reproduction is needed here since it is simply faulty logic found in PR ( Passing  "auto" to parseFloat will show issue ). Auto is a valid result of getComputedStyle(document.documentElement).scrollPaddingTop.

<img width="674" alt="Screenshot 2024-07-24 at 4 56 44 PM" src="https://github.com/user-attachments/assets/f0bebd1a-5768-48ca-8215-d033f1ff287f">
<img width="610" alt="Screenshot 2024-07-24 at 4 58 43 PM" src="https://github.com/user-attachments/assets/a2e587b3-5a72-4237-bd7f-4453d8571350">

**Comment by boogie-ben** [comment]
This is a good question. We can make a falsy check on the computed result: `Number.parseFloat('string') || 0`

However, this issue brings up another scenario where the `scroll-margin-top` of the hash element or the `scroll-padding-top` of the document has values like '1em', '1vh', and other length values that are not in pixels. This calculation logic will be incorrect because vue-router's scrollBehavior only accepts pixel values. Should we pay attention to this situation? @danielroe

**Comment by boogie-ben** [comment]
I just realized that `getComputedStyle(elem)` converts length attribute values like `em` and `vh` to pixel values, so this issue can be resolved directly.
