### ISSUE TITLE
Nuxt3.12.0 cant use nuxt-socket-io

### ISSUE THREAD

**Issue by yuiyideyui** [nuxt/nuxt#28513]
### Environment

npx nuxi@latest init <project-name>

### Reproduction

websocket ---  failed: Invalid frame header

### Describe the bug

websocket ---  failed: Invalid frame header

**Comment by vaaski** [comment]
This issue isn't very descriptive. If you want people to help you, please provide more context and perhaps [a reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction).

However I think I might know what's going on here, because I've recently looked into socket.io with Nuxt myself.

You are probably using [nuxt-socket-io](https://nuxt.com/modules/socket-io) which is not compatible with Nuxt 3, as per the warning on top of the page. [Here is how you can set up socket.io with Nuxt 3](https://socket.io/how-to/use-with-nuxt).
