### ISSUE TITLE
Plugin types break if I add @nuxtjs/i18n to modules

### ISSUE THREAD

**Issue by frasza** [nuxt/nuxt#28672]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.16.0
- Nuxt Version:     3.13.0
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.1
- Builder:          -
- User Config:      modules, devtools, compatibilityDate
- Runtime Modules:  @nuxtjs/i18n@8.5.0
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/frasza/plugin-type

### Describe the bug

I have axios plugin that provides its instance to the app and in case I add `@nuxtjs/i18n` to the nuxt config modules array, the plugin type becomes `unknown`.

**Comment by danielroe** [comment]
would you open in https://github.com/nuxt-modules/i18n instead? I think they plan a hotfix to address...

cc: @BobbieGoede

**Comment by frasza** [comment]
Sure - https://github.com/nuxt-modules/i18n/issues/3070. Thanks!

**Comment by BobbieGoede** [comment]
@danielroe 
This seems to be caused by type imports in `plugins.d.ts`, it breaks whenever imports use `.mjs` instead of `.js`. 

I was able to reproduce this locally (using the provided [repo](https://github.com/frasza/plugin-type)) without `@nuxtjs/i18n`, the types added by `@nuxt/devtools` when running nuxt dev will cause the same issue.

Is this something that should be resolved on the module end or on Nuxt's side?

**Comment by pavelimmobilien** [comment]
I can confirm that all `.mjs` imports in `.nuxt/types/plugins.d.ts` break all provided plugins.

**Comment by danielroe** [comment]
The issue is that the wrong declarations are generated - see:

https://unpkg.com/browse/@nuxt/devtools@1.3.14/dist/runtime/plugins/

![CleanShot 2024-08-23 at 12 04 08@2x](https://github.com/user-attachments/assets/e2b74a24-c565-4f31-b112-60174630ce80)

This should be `devtools.server.d.ts` and `devtools.server.js` OR `devtools.server.d.mts` and `devtools.server.mjs`.

Investigating to see whether this is a module-builder issue.

**Comment by Archetipo95** [comment]
I think I had a related issue this morning with algolia nuxt module
```
../../node_modules/.pnpm/@nuxtjs+algolia@1.10.2_@vue+server-renderer@3.4.38_vue@3.4.38_typescript@5.5.4___magicast@0.3_gmv53hnb7zexxkglosjulg7kzy/node_modules/@nuxtjs/algolia/dist/runtime/components/AlgoliaDocSearch.vue:10:60 - error TS2307: Cannot find module '@docsearch/react' or its corresponding type declarations.
```

Unfortunately I don't have a reproduction and my fix was to remove the algolia module because was no longer used

**Comment by danielroe** [comment]
@Archetipo95 The issue might be that the version of `@docsearch/react` used in the module did not expose correct types for TypeScript bundle module resolution. You could file an issue upstream on https://github.com/nuxt-modules/algolia.

**Comment by frasza** [comment]
Solved with https://github.com/nuxt-modules/i18n/pull/3071

**Comment by antony-k1208** [comment]
I am not sure if this is related to the issue, but I am facing similar Typescript errors after upgrading to Nuxt 3.13.0.

Since then all the provided data from plugins is not available anymore, when using `useNuxtApp`: https://stackblitz.com/edit/nuxt-3-13-0-plugin-provide-issue.

Just by changing the Nuxt version back to 3.12.4 the type error disappears.
