### ISSUE TITLE
Dynamic route drops 404 at --preset github_pages

### ISSUE THREAD

**Issue by fb-sean** [nuxt/nuxt#29233]
### Environment

Github Pages 

and

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.0
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
-----------------------------

### Reproduction

- Fork: https://stackblitz.com/edit/github-gcu9d8?file=layouts%2Fdefault.vue
- Run: npm run build-preview
- Open: /bot/hey (can be any query)
- Open Console 
- See the 404 error

### Describe the bug

When running it in dev mode you wont see any 404 but when running the builded source it drops an 404.

**Comment by danielroe** [comment]
This is unfortunate but unavoidable. Because it's being statically prerendered, you'll need to add any pages like `/bot/hey` to the `nitro.prerender.routes` array or they won't be generated. Nuxt doesn't have any way to know what those pages should be, and GitHub Pages needs explicit files or it will return a 404. (There's no Nitro server to handle the requests dynamically.)
