### ISSUE TITLE
Auto install `@nuxt/image` prompts hangs `nuxt build`

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt#29283]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.17.0`
- Nuxt Version:     `3.13.2`
- CLI Version:      `3.14.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `bun@1.1.29`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

- https://github.com/unjs/h3/tree/7324eeec854eecc37422074ef9f2aec8a5e4a816/docs
- `bun install` > `bun run build`

### Describe the bug

Even though no `<NuxtImg>` is used, Nuxt seems wrongly detecting usage it and prompts to install (which is another issue)

When running build command, interactive prompt is asked but also not even awaited (IMO we should avoid any prompt) and build will be stuck

![Image](https://github.com/user-attachments/assets/3d4af8d2-285f-423d-9ba4-461389709df5)

**Comment by danielroe** [comment]
Agreed we shouldn't prompt/hang on build - likely we should error out.

The underlying issue is coming from `@nuxtjs/mdc` which uses `<NuxtImg>` in `ProseImg.vue` which is used to render every `<img>` in transformed markdown. If `mdc.components.prose` is enabled in this module (true by default) then this is added as a global component, whether or not you use it in your project.

cc: @benjamincanac as I think you had a similar issue reported (likely it would occur for anyone using nuxt/content without installing nuxt/image).

cc: @farnabaz - if we fix this (by erroring the build) then likely it will cause fatal errors for every user of `@nuxtjs/mdc` - can you think of a solution?
