### ISSUE TITLE
HMR - Transition - Async function give me Uncaught (in promise) TypeError: leavingVNode.el is null

### ISSUE THREAD

**Issue by jules-contact** [nuxt/nuxt#29289]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.9.0`
- Nuxt Version:     `3.13.2`
- CLI Version:      `3.14.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `pnpm@9.11.0`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-iucia4?file=pages%2Findex.vue

### Describe the bug

HMR does not work when i have a async fetch in the page and a leave page transition

Try to update the console.log message and you get the 'Uncaught (in promise) TypeError: leavingVNode.el is null' error

### Logs

Uncaught (in promise) TypeError: leavingVNode.el is null

**Comment by Nonolanlan1007** [comment]
Still the error with the latest version of Nuxt

**Comment by yschroe** [comment]
@danielroe Not sure if I am missing something, but I can't trigger the reported error message. Neither in the linked repro, nor in v4.5.0. If I change the console.log message to trigger HMR, it works without error. I guess this was fixed directly in Vue?

The page turns blank, but this is because this is set in `app.vue`:

```ts
function onBeforeEnter(el: any) {
  el.style.opacity = 0;
}
```

**Comment by danielroe** [comment]
I think this is fixed 🙏 

nuxtathon closed @yschroe
