### ISSUE TITLE
Reactivity with different behaviour in Pages vs Components

### ISSUE THREAD

**Issue by educkf** [nuxt/nuxt#29610]
### Environment

It is happening in two environments of mine

------------------------------ 
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------
- Operating System: Windows_NT
- Node Version:     v22.3.0
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-ltkw9t?file=app%2Fpages%2Findex.vue&file=app%2Fcomponents%2Fsidebar.vue

### Describe the bug

I have a page and a component pointing to some data on a composable, and they point to it in the exact same way. But in one place, it is reactive, and in another place it is not. On component it works fine, but not on page. There it is not reactive.

**Comment by antalasztrik** [comment]
This bug is probably not related to the differences between "Pages" and "Components". I'd think that both of these components should behave like normal Vue components when it comes to reactivity.

The reason this happens, is because state it not shared between different calls of a composable function. The value of `settings.columns` is going to be different in each component, so updating it in one component does not update it for the other. This is outlined at the end of the [Mouse tracker example](https://vuejs.org/guide/reusability/composables.html#mouse-tracker-example) section:
![Image](https://github.com/user-attachments/assets/4215b9eb-df48-4635-b636-8c09a58c793c)

You can read more about state management in Vue [here](https://vuejs.org/guide/scaling-up/state-management.html) or even better, learn how to use it in [Nuxt](https://nuxt.com/docs/getting-started/state-management)! 
For the example you provided you are probably fine going with Nuxt's built in [useState](https://nuxt.com/docs/api/composables/use-state) composable, but for more complex shared states you might want to take a look at [Pinia](https://pinia.vuejs.org/introduction.html), which has [great integration](https://pinia.vuejs.org/ssr/nuxt.html) with Nuxt.

**Comment by danielroe** [comment]
great explanation! thank you ❤

**Comment by educkf** [comment]
Sorry for taking so long to reply! 
Indeed, great explanation! Thank you very much!
