### ISSUE TITLE
Nuxt is still under active development?

### ISSUE THREAD

**Issue by ronenteva** [nuxt/nuxt#29730]
It's been very quiet here recently, did something happen behind the scenes?

**Comment by xjccc** [comment]
Let the bullets fly for a while.

**Comment by ronenteva** [comment]
@xjccc any idea if there's something going on?

**Comment by danielroe** [comment]
Absolutely under active development. I've been in SF for GitHub Universe.

What makes you think it's not under active development? 🤔

**Comment by manniL** [comment]
✔ Regular commits
✔ Active Community (here, on Discord and on Social Media)
✔ Healthy Ecosystem
✔ Plans for future versions

**Comment by ronenteva** [comment]
It was a genuine question, if you guys say all is good, then I guess all is good 👍

**Comment by manniL** [comment]
> It was a genuine question, if you guys say all is good, then I guess all is good 👍

@ronenteva That's totally fine - but how did the question came up in the first place?

**Comment by mavyfaby** [comment]
> > It was a genuine question, if you guys say all is good, then I guess all is good 👍
> 
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/ronenteva?size=32">@ronenteva](https://github.com/ronenteva) That's totally fine - but how did the question came up in the first place?

I think he means that there's no commits from maintainers from these past days.

**Comment by ronenteva** [comment]
It is not uncommon for successful dev teams behind great projects to get an investment or something that shifts their attention somewhere else.

If you exclude deps and docs updates, it seems that there were significantly less commits in the last few weeks than there were before.

Nuxt 4 was expected to be released in June, and in September the release date simply became "to be announced".
While the delay itself is really nothing, the lack of communication made me a bit worried.
(the answers are probably on discord, but I'm not active there)

Also I know you aim to publish a patch release every week or so, but there hasn't been one in like 6 weeks.
Again, no complaints and personally I'm not waiting for any specific fix, just explaining why I asked.

**Comment by danielroe** [comment]
As far as those specific points, we're currently waiting on Nitro v2.10 for our next minor release, which has been expected imminently for a while. You can track the outstanding TODOs in https://github.com/nuxt/nuxt/pull/29077. We are waiting on Nitro v3 for the Nuxt v4 release. You're right that we've discussed it often in the Discord office hours and on Twitter, but I understand you might not have heard that. Nevertheless, it's also normal for team members to decrease at times throughout the year, for example if they are speaking at conferences, or focusing on a different project in the Nuxt ecosystem.

Next time I suggest asking about an ETA rather than asking if the project is under active development - which it _clearly_ is. Regardless of your (good) intention it comes across as a bit of a slap in the face to people who are coding, answering issues, commenting on pull requests and merging PRs.

**Comment by daniluk4000** [comment]
Hearing someone questioning if one of most active frameworks I know is under active development feels so weird. Especially in terms of what we had happening in Vue not so long ago ([300 PRs](https://github.com/orgs/vuejs/discussions/7050), [400 PRs](https://github.com/orgs/vuejs/discussions/8560), [500 PRs](https://github.com/orgs/vuejs/discussions/9437)). You could also say Vue is dying even now - but to do that you also have to close your eyes and ignore the whole picture, which includes Vite, Rolldown and Vapor. 

> While the delay itself is really nothing, the lack of communication made me a bit worried.

Honestly the current state of the engine you don't _really_ need Nuxt 4. We were honestly waiting for Summer release only to plan for upgrade window in our company - but since we have compatibility flags we can do them instead. Right now, I want those huge h3 improvements :D

Also, Nuxt is one of the most transparent folks I know. You can easily get what to expect in Nuxt 4 PR. I do agree that Nuxt 4 ETA communication is not that clear, but if you follow Nuxt history a bit more, current situation is much better than what we had with Nuxt 3 release and it's nice to see team learning from mistakes, including migration preparations.

Speaking of decreased commits count: it's worth remembering that this repository is only a part of whole ecosystem. 

Here's some of contributors October activity. Sometimes I'm worried about how are they even managing to work like this every month. 

<details>
  <summary>danielroe</summary>
  
![Image](https://github.com/user-attachments/assets/7d8ff78c-3b54-4773-a41d-ffa10b41bd34)
</details>

<details>
  <summary>atinux</summary>
  
![Image](https://github.com/user-attachments/assets/5e587e68-f243-49fc-8e93-4e252359489b)
</details>

<details>
  <summary>pi0</summary>
  
![Image](https://github.com/user-attachments/assets/08e8e719-4558-4171-8edc-3e9ab71369d9)
</details>

Despite everything, we had many UnJS releases that are preparing the ecosystem for Nuxt 4. 

Keep up the good work, team💪
