### ISSUE TITLE
fixPrepatch is too aggressive about reseting component state

### ISSUE THREAD

**Issue by nandin-borjigin** [nuxt/nuxt#4878]
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[https://github.com/Nandiin/nuxt-issue](https://github.com/Nandiin/nuxt-issue)

### Steps to reproduce

1. `yarn dev`
2. Navigate via tabs, and note that parent component state is not reset (_pathChanged = true, _queryChanged = false hence _dataRefresh = false)
3. At either tab, select one of the query ranges (7 days/1 month/all) and then navigate to another tab. Note that parent component state is reset.

![Untitled.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/f8467d60-23b6-11e9-b478-49939ef6e5f4.png)

### What is expected ?

Parent component state should not be reset when navigating sub routes.

### What is actually happening?

Parent component state is being reset.

### Additional comments?

Related issue: https://github.com/nuxt/nuxt.js/issues/1408

I understand the necessity to have `fixPrepatch` called after each route navigation (via `router.afterEach`). But it's too aggressive now and causing some unexpected unconventional behaviors. And it's not clearly documented and needs a lot of human efforts to locate the problem.

Please add a some proper documentation and an option to disable it component-wisely.

My current workaround is to use `Object.defineProperty` to override `_dataRefresh` property on component constructors (overriding its setter function to noop), but it's somehow hacky and goes hackier when using class component syntax.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8560">#c8560</a>)</em></sub></div>

**Comment by Nandiin** [comment]
Please let me know if you guys need any additional information to proceed on this.

**Comment by noe132** [comment]
Hey guys, here's a little test I did about how `data` and `asyncData` was called while navigating whether `path` or `query` was changed.  
All routing was done on client side by click `<nuxt-link>` or by `router.push`.  
Every page component has following logging code:  
```javascript
export default {
    data() {
        console.log('<pagename> data')
        return {}
    },
    asyncData() {
        console.log('<pagename> asyncData')
    },
}
```
The `page` directory structure, with 2 static routes `/page1` and `/page2` and dynamic route `_.vue`: 
```
+-- pages
    +-- index
    |   +-- _.vue
    |   +-- page1.vue
    |   +-- page2.vue
    +-- index.vue
```
```vue
<!-- index.vue -->
<template>
    <div>
        <nuxt-child />
    </div>
</template>
```
test project available at: [https://codesandbox.io/s/qzllmxvk6](https://codesandbox.io/s/qzllmxvk6)


### Tests Conditions
#### route path didn't change
- from `/page1` to `/page1?query=blablabla`
- from `/dynamic1` to `/dynamic1?query=blablabla`
```
nothing was called
```

### route path change but w/o query change (query both same or empty)
- from `/page1` to `/page2`
- from `/page1?query=blablabla` to `/page2?query=blablabla`
- from `/dynamic1` to `/dynamic2`
- from `/dynamic1?query=blablabla` to `/dynamic2?query=blablabla`
```
<to-page> asyncData
<to-page> data
```

### router path change and query change
- from `/page1` to `/page2?query=blablabla`
- from `/dynamic1` to `/dynamic2?query=blablabla`
```
index asyncData
<to-page> asyncData
index data
<to-page> data
```

from the test result above, if both route `path` and `query` changed while at one route navigation, the parent route `data` and `asyncData` will be called. Static routes and dynamic routes are acting the same.  

**However, what's interesting is if you try do something like**  
try navigating from `/page1` to `/page2?query=blablabla` by:
1. navigate from `/page1` to `/page1?query=blablabla`
2. navigate from `/page1?query=blablabla` to `/page2?query=blablabla`

from the test result above we can know that step 1 won't call any of those function, and step 2 was routing with only path change, so the results will be
```
page2 asyncData
page2 data
```
which is actually different from navigating from `/page1` to `/page2?query=blablabla` directly.


If `/page1` to `/page1?query=blablabla` doesn't trigger either of `data` or `asyncData`, then navigating  
from `/page1` to `/page2?query=blablabla`  
should be exactly same as  
from `/page1?query=blablabla` to `/page2?query=blablabla`  

So what would be the expected behavior? Any thoughts about this?  
From what I think is that navigating from `/page1` to `/page2?query=blablabla` shouldn't trigger parent route's `data` and `asyncData` function.

**Comment by OrkhanAlikhanov** [comment]
>My current workaround is to use Object.defineProperty to override _dataRefresh property on component constructors (overriding its setter function to noop), but it's somehow hacky and goes hackier when using class component syntax.

I would also like to disable nuxt running `fixPrepatch` at all as I am watching route params and managing the component's state myself. @pi0 is it planned to add an official way to do that? Maybe a component prop? I don't see any side effects of having an option to disable it at page component level. What do you think?

**Comment by vzakharov** [comment]
Gosh, it took me ages to locate this, and I still don’t know how to fix this. I don’t want my data reset when I “route” to the same component with the same key, how can I dsiable this?

**Comment by michaelleb** [comment]
Hello, is there any documentation on how this should work and how to disable this behavior? 
I have just lost a day in figuring out this unexpected behavior.

Here is a simplified structure that I have:
+-- pages
|   +-- articles
|    |    _slug.vue
|    |     index.vue
I   articles.vue // specific article is rendered in NuxtChild

The issue I have is that when navigating 
from /articles/article-1
to /articles/article-2
dynamic route reuses the _slug.vue component inside NuxtChild, the reused component computes values, mounts nested components, and lets me update values in data, but then wipes them with fresh data initialization due to fixPrepatch.

The desired behavior is that it should mimic the mounting of a new component. Specifically,  the data should be initialized before calculating computed properties and before the template calculates its if-else values and mounts nested components.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
