### ISSUE TITLE
Use JSON to pass data from SSR to improve performance

### ISSUE THREAD

**Issue by CyberAP** [nuxt/nuxt#6168]
### What problem does this feature solve?

Using JavaScript to pass data from SSR to an app through global context is not efficient.
JSON, on the other hand, offers a much better performance and could be used instead. [Explanation in v8 blog](https://v8.dev/blog/cost-of-javascript-2019#json), [Benchmarks](https://github.com/GoogleChromeLabs/json-parse-benchmark) (performance increase up to 2 times)
This is especially important for apps with a lot of state.

### What does the proposed changes look like?

This code:
```html
<script>window.__NUXT__ = { data: {} /* some state */ }</script>
```

Turns into this:
```html
<script id="NUXT_STATE" type="application/json">
{ data: {} }
</script>
```
```js
// somewhere in app init
const stateEl = document.getElementById('NUXT_STATE');
const state = JSON.parse(stateEl.textContent);
app.state = state;
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9586">#c9586</a>)</em></sub></div>

**Comment by Timkor** [comment]
What about circulair references? Or types which are not supported by JSON?

**Comment by CyberAP** [comment]
For circular references we have: https://github.com/WebReflection/circular-json
This could be enabled in a nuxt config for those who really need that.

For unsupported JSON types could you elaborate a little bit more? What's the usecase?

**Comment by manniL** [comment]
Thanks for the information! We read that article as well but things are a bit more complicated here. For Nuxt 2, we decided to go with [`devalue`](https://github.com/Rich-Harris/devalue) ([our fork](https://github.com/nuxt/nuxt.js/issues/5954)) instead of pure `JSON.stringify` for a couple for reasons. This won't change in Nuxt 2 to avoid breaking changes.

**Comment by CyberAP** [comment]
@manniL could you unveil these reasons if possible? I'm really curious when JSON is not appropriate as a DTO.

**Comment by aldarund** [comment]
circular-json seems to be replaced by flatted.  I tested flatted and devalue on 120kb payload. Without circular.
devalue -> 1600 ops
flatted -> 630 ops
Reasons for devalue instead of json listed on the devalue page itself.

repeated references ([value, value])
undefined, Infinity, NaN, -0
regular expressions
dates
Map and Set

For example undefined values just got stripped by json.stringify

**Comment by 404-NF** [comment]
@aldarund how about use json.strigify(value, function(key,value){ xxxx }) instead devalue;
use strigify replacer can support special types;
in my test, most of develop scene devalue takes 60%-70% more time than common json.stringify. it takes several times than render.
it's not only effct the `time per request` but also `request per second`. it looks like devalue become the most performance problem for me.

**Comment by danielroe** [comment]
This is now implemented in Nuxt 3.
