### ISSUE TITLE
Ability to ignore files/directories for rebuilds/compiles.

### ISSUE THREAD

**Issue by sustained** [nuxt/nuxt#6326]
### What problem does this feature solve?

I'm working on a Nuxt module.

I am [generating JSON files at build/compile-time](https://github.com/sustained/nuxt-dynamic-markdown/tree/0f8b9a409027be97abd14851b392f578eb4f25b9/lib/module.js#L152).

The JSON files [are stored in `~/static/json`](https://github.com/sustained/nuxt-dynamic-markdown/tree/0f8b9a409027be97abd14851b392f578eb4f25b9/lib/module.js#L439).

They are generated based on Markdown files stored in the `~/contents` directory - [which I add to options.build.watch](https://github.com/sustained/nuxt-dynamic-markdown/tree/0f8b9a409027be97abd14851b392f578eb4f25b9/lib/module.js#L95).

I was trying to make it so the JSON is regenerated whenever a file in `~/contents` is changed.

But the very act of writing the JSON files to the `~/static/json` directory itself [triggers a recompile/rebuild itself](https://github.com/sustained/nuxt-dynamic-markdown/tree/0f8b9a409027be97abd14851b392f578eb4f25b9/lib/module.js#L164).

&lt;aside&gt;Also, since it's vaguely relevant, I thought I could perhaps get access to a list of files which have changed (so that I could programmatically determine which files to regenerate instead of blindly regenerating everything). So I looked it up online and [found a method of doing so (`compiler.watchFileSystem.watcher.mtimes`)](https://github.com/sustained/nuxt-dynamic-markdown/tree/0f8b9a409027be97abd14851b392f578eb4f25b9/lib/module.js#L630) but I couldn't get it to work (always returns an empty array).&lt;/aside&gt;

I tried adding `~/contents/json` to `.nuxtignore` [per the documentation](https://nuxtjs.org/api/configuration-ignore/) but it didn't work - changes to the directory continued to trigger rebuilds.

### What does the proposed changes look like?

I'm not sure  how the API should look however [Chokidar does have an ignored option](https://github.com/paulmillr/chokidar#api) and so we just need some way to pass that through, [in addition to `build.watch`](https://nuxtjs.org/api/configuration-watch/).

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9700">#c9700</a>)</em></sub></div>

**Comment by sustained** [comment]
Sorry to be impatient but any thoughts or input on this?

It's holding back development of my module somewhat.

Would be nice to know if it is already possible somehow and I'm just missing something, or if some workaround is possible, or if such a feature makes sense or would even be considered etc.?

Thanks!

**Comment by pi0** [comment]
I think you need to ignore with a pattern like `contents/json/*.json` (~ not supported)

Also it is highly recommend using buildDir (.nuxt instead of project to emit this assets)

**Comment by sustained** [comment]
Hmm, not sure that I did include the `~` in the `.nuxtignore` but I'll give it a try without and report back.

Also I'll look into emitting the assets to the `buildDir`. Thanks!

**Comment by sustained** [comment]
@pi0 

It doesn't work with `static/json/*.json` in `.nuxtignore`.

And that is not a good solution to my problem anyway because I can't expect every user of my module to add a `.nuxtignore` file.

What can I do? :frowning_face:

**Comment by sustained** [comment]
Also is the `buildDir` solution viable? I load these JSON files at runtime in `asyncData`. I suppose that is an important detail.

**Comment by pi0** [comment]
@sustained Indeed that's also considered for module authors and supported. Instead of `.nuxtignore`, you can push to `this.options.ignore` array from module.

If loading from asyncData, you have to know build hash (resolve json files with require) otherwise if not possible, yes only solution is static/.

**Comment by sustained** [comment]
@pi0 Yeah, I tried that before (and just tried it again) and it doesn't work either - the changes are still detected causing an infinite loop.

That's why I requested the feature!

**Comment by AlexVipond** [comment]
@sustained I'm having the same issue. My Nuxt config file extends the webpack config with a custom plugin that generates files for me on webpack's `watchRun` hook, which is right after webpack detects a change, but right before it recompiles.

In my case I'm generating files in `pages/docs` and in `assets/json`, but the effect is the same—webpack gets caught in an infinite compilation loop.

I tried using the `watchers` property documented here: https://nuxtjs.org/api/configuration-watchers

```
// nuxt.config.js

export default {
  // rest of my config
  
  watchers: {
    chokidar: {
      ignored: [
        'pages/docs',
        'assets/json/**/*.json',
        'node_modules',
      ]
    },
    webpack: {
      ignored: [
        'pages/docs',
        'assets/json/**/*.json',
        'node_modules',
      ]
    }
  }
}
```

However, this doesn't work. I also tried using `build.extend` to set `webpackConfig.watchOptions` directly, but that didn't work either.

Possible root causes I could think of:
- Webpack's `ignored` option doesn't work
- Nuxt is overriding user-provided `ignored` values somewhere
- Nuxt is not using user-provided `ignored` values
- All or some of the above? Or something else?

**Comment by sujeetpillai** [comment]
I had the same issue and the following worked for me

```
nuxt.config.js
export default {
// rest of my config
  build: {
    extend(config,{isDev, isClient}){
        config.watchOptions = {ignored : [
        'dir_to_be_ignored/'
      ]}
    }
  }
}
```

**Comment by Jamiewarb** [comment]
Also having this issue

**Comment by kevcodez** [comment]
Running into the same issues, tried every solution in this thread.

App keeps rebuilding on changes in `.git` directory.

**Comment by GregorSondermeier** [comment]
I started working in a new company and wanted to get familar with a not so big existing vue+nuxt project. I'm working on Ubuntu 20.04. I checked out the project, ran `npm i` and `npm run dev` and the console started shouting at me with hundreds of thousands of warnings like this:

`Error from chokidar (/path/to/project/node_modules/yarn-or-npm/node_modules/cross-spawn/lib): Error: ENOSPC: System limit for number of file watchers reached, watch '/path/to/project/node_modules/yarn-or-npm/node_modules/cross-spawn/lib'`

Increasing the number of file watchers on the OS level is frankly an inacceptable workaround rather than a solution to this problem because it doesn't address the underlying problem that stuff is being watched which most likely is never going to be changed while the app is running locally. Who knows what this does to my system performance?

I found the documentation and discussions about this problem to be a bit all over the place. Multiple solution proposals and config properties exist, like [this one](https://nuxtjs.org/docs/configuration-glossary/configuration-ignore) or [this one](https://nuxtjs.org/docs/configuration-glossary/configuration-watch/), but none of these properties did the trick.

However, after way to much fiddling around, in the end, this worked for me:

```
// nuxt.config.js

  ...
  watchers: {
    webpack: {
      ignored: /(node_modules)|(.git)/
    }
  }
  ...
```
This excludes the _node_modules_ and _.git_ folders from being watched, so whenever there is a change in there you would need to restart the app. But IMO this is desired behavior anyway.

Links for reference:
* https://nuxtjs.org/docs/configuration-glossary/configuration-watchers/
* https://webpack.js.org/configuration/watch/#watchoptionsignored

**Comment by alexcroox** [comment]
Has anyone got this to work recently?

I've tried:

```
 watchers: {
    webpack: {
      ignored: /(node_modules)|(.git)/
    }
  }
  ```
  
  ```
  extend(config, { isDev, isClient }) {
      config.watchOptions = {
        ignored: ['node_modules/', '.git/'] // and various glob variations like **/node_modules/**/* etc
      }
    }
```

Fully restarting Nuxt, if I edit a file in node_modules directly it still triggers a rebuild

**Comment by nivv** [comment]
This is annoying. Can't ignore the .git directory. which causes rebuilds.

![image](https://user-images.githubusercontent.com/4033930/166641341-cd307814-ac93-4050-bc2c-19acb710116f.png)

**Comment by mikeslattery** [comment]
This reads `.nuxtignore`

```javascript
  watchers: {
    webpack: {
      ignoreInitial: true,
      ignored: require('fs')
        .readFileSync('.nuxtignore')
        .toString()
        .split('\n')
        .concat(['node_modules/', '.git/', 'dist/', '.nuxt/'])
        .filter((v) => v.trim() !== '' && !/^#/.test(v))
        .map(
          (v) =>
            new RegExp(
              v
                .replaceAll('.', '\\.')
                .replaceAll('**', '#')
                .replaceAll('*', '[^/]*')
                .replaceAll('#', '.*')
                .trim()
            )
        ),
    },
  },
```

**Comment by Chippd** [comment]
For anyone (including future me) looking to solve this. In my case, the .nuxtignore file didn't work, nor did any of the solutions here. 
What worked for me was adding an `ignore` array to the nuxt.config.ts file. I was getting TS errors when using some of the other solutions here. 

For reference currently running 
Nuxi 3.0.0-rc.12                                                       
Nuxt 3.0.0-rc.12 with Nitro 0.6.1

```
ignore: [
  "path/to/ignore/**"
],
```

Good luck future Chris.
