### ISSUE TITLE
Proposal to use koa instead of connect.

### ISSUE THREAD

**Issue by georgyfarniev** [nuxt/nuxt#6587]
### What problem does this feature solve?

Hello. Please don't close this topic immediately.

I know that it was mentioned before, I know opinion of **nuxt** developers, I respect it and I'm extremely grateful to them for creating this wonderful framework. Thanks a lot, guys.

However, connect are very old and very limited in it's capabilities and not flexible. I would like to propose usage of **koa** once again instead of connect, and here is a benefits that both devs and users of **nuxt** will get:

1. **Koa** is very lightweight server and it's very fast. It's well maintained and modern framework. As reason to choose connect, **nuxt** developers mention that it's lightweight, but I would like to know why **koa** are not considered lightweight as well. It's code base is pretty small, about 2K SLOC, and it's very well designed.
2. **Koa** has many useful features out of the box, such as query parser, and pretty good set of existing middlewares for all purposes. Connect, in contrast, doesn't have even query parser out of the box. Also koa supports async middlewares.
3. Koa can be good replacement for custom made server, such as nuxt/metal, which seems to be abandoned now.

Also, here is a good article that explains benefits of using koa: https://medium.com/@grantminer/why-you-should-use-koa-with-node-js-7c231a8174fa

So users will be able to save a lot of time when creating **serverMiddleware** and don't need two servers and composing **koa** as **serverMiddleware** or even worse, using custom server and **nuxt** rendering API.

I just want to understand why migration to **koa** considered a problem. Even if we will count deps for connect and **koa**, a little bit more dependencies are not big evil compared to frontend dependencies such as **babel**, **webpack** and other stuff.

My goal is to make nuxt better so more people will use it and proposed change will save them a lot of time and reduce resulting application complexity.

So I would like to know your opinion about questions above. Thanks for your attention.

UPD: Please share your opinion with us, especially if you downvote.

### What does the proposed changes look like?

Use **koa** inside **nuxt** and enable **nuxt** users to write serverMiddleware for **koa**.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9926">#c9926</a>)</em></sub></div>

**Comment by itshizhan** [comment]
good idea

**Comment by pimlie** [comment]
I think this topic is probably more suitable for a broad discussion in `https://github.com/nuxt/rfcs/issues`. Because why Koa and not Fastify? Why Fastify and not Hapi (who are also a sponsor of Nuxt.js)?

The main issue I see with Koa is that it will be breaking change because their middleware signature is different, so it would probably only be possible to migrate with Nuxt v3 unless we add monkey patching to keep supporting the old middleware signature.

Also, you can ofc already use Nuxt.js programmatically to support other servers: https://nuxtjs.org/api/nuxt#using-nuxt-js-programmatically

**Comment by georgyfarniev** [comment]
@pimlie I will move this issue to rfc later, thanks for pointing me out.

>Also, you can ofc already use Nuxt.js programmatically to support other servers: https://nuxtjs.org/api/nuxt#using-nuxt-js-programmatically

But how to use it with typescript runtime (nuxt-ts) then? And also developers say that this is not recommended way to use nuxt.

**Comment by pimlie** [comment]
> how to use it with typescript runtime (nuxt-ts) then

No idea, thats why this this topic is more suited for a rfc because there are so many factors involved when migrating to another server framework

> this is not recommended way

Recommended doesnt mean impossible. If you feel strongly about `connect` not being the right tool then you can already use another frameworks this way. The reason we say its not recommended is because there will be things that wont work out of the box (like due to different middleware signatures). So when we say _not recommended_ we are actually politely explaining to you that any issue which results from using another server framework then connect has a very low priority for us to try to understand and/or resolve. Or in other words, fine to switch but expect that you will be (mostly) on your own when it comes to issues because of it.

**Comment by danielroe** [comment]
Instead of using connect, we now have https://github.com/unjs/nitro, using https://github.com/unjs/h3, for Nuxt 3. I think we can close this issue safely.
