### ISSUE TITLE
incremental updating 

### ISSUE THREAD

**Issue by halower** [nuxt/nuxt#6741]
### What problem does this feature solve?

when the release versions are frequent and the deployment point is not local, I hope to support the incremental update deployment instead of the full package and release every time

**Comment by pimlie** [comment]
Could you explain how you'd expect this to work?

**Comment by VesterDe** [comment]
I have an opinion on this. I currently have a Laravel site where users may edit some entities (let's call them docs). The docs have end up being `nuxt export`ed, but I don't want to be running `nuxt export` each time 1 user edits 1 doc. So, I wrote this script for incrementally building only 1 doc:

```
const { loadNuxt } = require("nuxt");
const fs = require("fs");

async function run() {
  const nuxt = await loadNuxt({
    for: "start",
    _nuxtConfigFile: "nuxt.config.js",
    envConfig: { dotenv: "../.env" },
  });
  const docs = [...process.argv];
  docs.shift();
  docs.shift();
  docs.forEach(async (p) => {
    const { html, error, redirected } = await nuxt.renderRoute(`/doc/${p}`);
    fs.writeFileSync(`../public/_nuxt/doc/${p}/index.html`, html);
  })
}
run();
```

This works... kind of... The problem is that the render process also created some payload files, which contain state, and nuxt content type things. These payload files seem to get a different hash each time I render, so they will have incorrect links after an incremental render... until the next full `nuxt export` that is.

The payload files are not returned from the render process (I presume?), so I can't put them where they belong either.

Pitty, this seems extremely close to working perfectly for me.

**Comment by danielroe** [comment]
This is now possible with incremental static generation, which is supported in Nuxt 3/Nitro: https://nitro.unjs.io/. You can configure individual routes (or the entire site) to be served with `swr` strategy via `routeRules` (or set them to `static` for build once on request and cache).
